### ISSUE TITLE
Updating whole table doesn't result in runtime error

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#102]
The documentation says:

> You need to provide .where, .findBy, or .find conditions before calling .update. To ensure that the whole table won't be updated by accident, updating without where conditions will result in TypeScript and runtime errors.

However, in fact there is no runtime error:

```ts
await db.user.create({ name: "foo" })
await db.user.update({ name: "bar" }) // ts error, but no runtime error
console.log(await db.user)
```

```
(2.3ms) INSERT INTO "user"("name") VALUES ($1) RETURNING * ['foo']
(0.6ms) UPDATE "user" SET "name" = $1 ['bar']
(0.2ms) SELECT * FROM "user"
[ { id: 1, name: 'bar' } ]
```

**Comment by romeerez** [comment]
Added a `throw` into `update` and `delete` methods when there are nowhere conditions prior to them, empty where is still there.

**Comment by capaj** [comment]
Thanks @romeerez feels much safer now!
