### ISSUE TITLE
Support subquery in update arguments

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#105]
### Problem

`update()` statement doesn't accept subquery as an argument:

```ts
await db.user.create({ name: "foo" })
await db.user.create({ name: "bar" })
await db.user.find(1).update({ name: "baz" }) // works
await db.user.find(1).update({ name: db.user.find(2).get("name") }) // ts error and runtime crash
```

Unlike #104, I didn't manage to find any simple workaround for doing updates with a subquery. So unlike all previous issues that I opened, this one is critical (for me) for switching from Objection.js to Orchid.

### Expected

All queries above work. The last query generates (omitting placeholders):

```sql
UPDATE "user" SET "name" = (SELECT "user"."name" FROM "user" WHERE "user"."id" = 2) WHERE "user"."id" = 1
```

This is how Objection.js works, and is generally what user would expect.

Similarly, subquery should be supported in `create` (if that requires different implementation I can open a separate issue for that.)

### Logs

```
(3.9ms) INSERT INTO "user"("name") VALUES ($1) RETURNING * ['foo']
(8.8ms) INSERT INTO "user"("name") VALUES ($1) RETURNING * ['bar']
(6.2ms) UPDATE "user" SET "name" = $1 WHERE "user"."id" = $2 ['baz', 1]
file:///Users/semenov/gh/orchid-graphql/node_modules/.pnpm/pqb@0.11.32/node_modules/pqb/dist/index.mjs:2953
    return `'${JSON.stringify(value).replace(singleQuoteRegex, "''")}'`;
                    ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Socket'
    |     property '_writableState' -> object with constructor 'WritableState'
    |     property 'afterWriteTickInfo' -> object with constructor 'Object'
    --- property 'stream' closes the circle
    at JSON.stringify (<anonymous>)
    at quote (file:///Users/semenov/gh/orchid-graphql/node_modules/.pnpm/pqb@0.11.32/node_modules/pqb/src/quote.ts:34:24)
    at Array.map (<anonymous>)
    at makeMessage (file:///Users/semenov/gh/orchid-graphql/node_modules/.pnpm/pqb@0.11.32/node_modules/pqb/src/queryMethods/log.ts:62:38)
    at Object.onError (file:///Users/semenov/gh/orchid-graphql/node_modules/.pnpm/pqb@0.11.32/node_modules/pqb/src/queryMethods/log.ts:95:14)
    at then (file:///Users/semenov/gh/orchid-graphql/node_modules/.pnpm/pqb@0.11.32/node_modules/pqb/src/queryMethods/then.ts:167:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

- pqb 0.11.32
- orchid-orm 1.9.40
- orchid-core 0.4.13

**Comment by romeerez** [comment]
I'll prioritize it then, it shouldn't take long.

**Comment by romeerez** [comment]
Published, now you can pass a query or a callback with a query to `update` and `updateOrThrow`, [here is the doc](https://orchid-orm.netlify.app/guide/create-update-delete.html#update), and pass a query to `create`, `createMany` and other methods, [docs for create](https://orchid-orm.netlify.app/guide/create-update-delete.html#create).

**Comment by IlyaSemenov** [comment]
@romeerez Wow, that was fast!

I see some problems, I'll list them below then if needed I can create separate issues:

1. The documentation mentions:

```ts
await db.table.where({ ...conditions }).update({
  // use query that returns a single value
  // returning multiple values will result in PostgreSQL error
  column3: db.otherTable.get('someColumn').take(),
});
```

This indeed works, but it gives typing error:

```ts
await db.post.find(1).update({
  text: db.post.get("text").take(), // works, but gives type error
})
```

```
Type 'SetQueryReturns<GetResult<DbTable<typeof PostTable>, "text">, "oneOrThrow", ColumnShapeOutput<{ value: TextColumn; }>>' is not assignable to type 'UpdateColumn<SetQueryReturns<WhereResult<DbTable<typeof PostTable>>, "oneOrThrow", ColumnShapeOutput<Pick<{ id: PrimaryKeyColumn<IdentityColumn<IntegerColumn>>; text: TextColumn; }, "id" | "text">>>, "text", { ...; }> | undefined'.
  Type 'SetQueryReturns<GetResult<DbTable<typeof PostTable>, "text">, "oneOrThrow", ColumnShapeOutput<{ value: TextColumn; }>>' is not assignable to type '{ meta: QueryMetaBase; internal: QueryInternal; windows: {}; baseQuery: Query; all: <T extends Query>(this: T) => SetQueryReturns<T, "all", ColumnShapeOutput<T["result"]>[]>; ... 294 more ...; isSubQuery: boolean; }'.
    Types of property 'then' are incompatible.
      Type 'QueryThen<ColumnShapeOutput<{ value: TextColumn; }>>' is not assignable to type 'QueryThen<string>'.
        Type 'ColumnShapeOutput<{ value: TextColumn; }>' is not assignable to type 'string'.
``` 

---

2. In the case above, I don't see why `take` is needed at all alongside `get`. The documentation for `get` says:

> .get returns a single value, **it will add LIMIT 1 to the query**, and accepts a column name or a raw expression

However in fact when used as a sub-query for update, it doesn't add LIMIT 1:

```ts
await db.post.find(1).update({
  text: db.post.get("text"), // no type errors, but doesn't add LIMIT 1
})
```

```sql
UPDATE "post" SET "text" = (SELECT "post"."text" FROM "post") WHERE "post"."id" = $1 [1]
```

I think it should be fixed to add `LIMIT 1` and the documentation must be changed. Typings work already. 😃 

---

3. Is there a way to refer to the same **row** being updated? My use case is updating a JSON sub-field:

```ts
class PostTable extends BaseTable {
  readonly table = "post"
  columns = this.setColumns((t) => ({
    id: t.identity().primaryKey(),
    data: t.json((t) =>
      t.object({
        foo: t.number(),
        bar: t.number(),
      })
    ),
  }))
}

await db.post.create({ data: { foo: 1, bar: 2 } })

await db.post.find(1).update({
  data: (q) => q.jsonSet("data", ["foo"], 3), // ts error, runtime crash
}
```

**Comment by romeerez** [comment]
1. `take` is not needed, I'll remove it from the docs. It expects a single value, but `take` makes it load a single record instead.

2. At some point I thought that adding `LIMIT 1` implicitly might hide problems that are better to be thrown, and removed that `LIMIT 1` from the code, but need to also remove it from docs. Not 100% sure about it though, in some cases implicit limit may hide a problem, in other cases it may be intended, so need to put more thought into it.

3. It's expected a full new here, such query that has `FROM table` inside, and you're trying to build a piece of SQL to update JSON. `q` is the same `update` query and I suppose it fails because of endless recursion when trying to construct SQL from it. For the piece of SQL I'd suggest to use a raw SQL, because currently there is no better way for this case.

**Comment by romeerez** [comment]
The third point about `jsonSet` - could you suggest something, is it possible in knex/objection? I copied the method from knex, but not sure if it can be used inside update.

**Comment by IlyaSemenov** [comment]
>  is it possible in knex/objection? 

There is a global helper in Objection:

```ts
await PostModel.query().insert({ data: { foo: 1, bar: 2 } })
await PostModel.query()
	.findById(1)
	.update({ data: knex.jsonSet("data", "$.foo", 3) })

console.log(await PostModel.query())
```

```
  knex:query insert into `post` (`data`) values (?) undefined +34ms
  knex:query update `post` set `data` = (json_set(`data`, ?, ?)) where `post`.`id` = ? undefined +3ms
  knex:query select `post`.* from `post` undefined +1ms
[ PostModel { id: 1, data: '{"foo":3,"bar":2}' } ]
```

Obviously this is not typed, but at least this is not raw query. I suppose exporting similar global helper in `pqb` will help to a certain extent.

---

> could you suggest something

Yes.

I believe `(q)` in `db.table.update({ field: (q) => ... })` could be implemented as a special type of query which is bound to the outer query so `q.select()` and `.jsonXxx` work automagically. After all, that is already the case with `q.relatedTable`. Consider this example:

```ts
import { createBaseTable, orchidORM } from "orchid-orm"

const BaseTable = createBaseTable()

class UserTable extends BaseTable {
  readonly table = "user"

  columns = this.setColumns((t) => ({
    id: t.identity().primaryKey(),
    name: t.string(1, 100),
  }))
}

class PostTable extends BaseTable {
  readonly table = "post"

  columns = this.setColumns((t) => ({
    id: t.identity().primaryKey(),
    title: t.text(1, 1000),
    content: t.text(1, 10000),
    user_id: t.integer().foreignKey(() => UserTable, "id"),
  }))

  relations = {
    user: this.belongsTo(() => UserTable, {
      required: true,
      primaryKey: "id",
      foreignKey: "user_id",
    }),
  }
}

const db = orchidORM(
  {
    databaseURL: process.env.DATABASE_URL,
    log: true,
  },
  {
    user: UserTable,
    post: PostTable,
  }
)

await db.$adapter.query(`
drop table if exists "user";
create table "user" (
  id serial primary key,
  name text not null
);
drop table if exists post;
  create table post (
    id serial primary key,
    title text not null,
    content text not null,
    user_id integer not null
  );
`)

await db.user.createMany([{ name: "Alice" }, { name: "Bob" }])

await db.post.create({ title: "foo", content: "TODO", user_id: 1 })
await db.post.create({ title: "bar", content: "TODO", user_id: 2 })

await db.post.where().update({
  // Works, sets each post title to the respective user name
  content: (q) => q.user.get("name"),
  // No TS error, but runtime crash
  content: (q) => q.get("title"),
})

console.log(await db.post)

await db.$close()
```

In the example above, from end-user point of view I don't see what's the logical difference between getting related table field and **this** table field.

The related query generates:

```sql
UPDATE "post" SET "content" = (SELECT "user"."name" FROM "user" WHERE "user"."id" = "post"."user_id")
```

Meaning that it already knows it runs in the context of the current user.

I would expect the non-related query to generate:

```sql
UPDATE "post" SET "content" = "title"
```

Or, perhaps there can be middle ground such as using `.relatedTable`-style construct for referring to self?

```ts
await db.post.where().update({
  content: (q) => q.$self.get("name"), // or q.$row
})
```

I suppose this could even generate `.relatedTable`-style SQL, no big deal:

```sql
UPDATE "post" SET "content" = (SELECT "post"."title" FROM "post" WHERE "post"."id" = "post"."id")
```

**Comment by romeerez** [comment]
I removed the confusing `take()` from the update/create docs, and changed `get` behavior to indeed add the `LIMIT 1` to queries.

Modifying JSON in the update callback is yet to be done.

**Comment by romeerez** [comment]
Published update to support json methods in the `update` callbacks, check out the `jsonColumn` example [here](https://orchid-orm.netlify.app/guide/create-update-delete.html#update).

There are many other things that could be handled when updating the record, feel free to open new issues for it if there's something more you want to achieve.
