### ISSUE TITLE
New method: modify()

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#107]
### Feature request

Similar to Objection.js/Knex, I would like to have `query.modify()` ([knex](https://knexjs.org/guide/query-builder.html#modify)]. 

This works similar to how `query.where()` with a functional callback, but not limiting to where-only methods.

### Use case

```ts
const users = await db.user.select("id", "name").modify((q) => {
  if (ctx.foo) {
    return q.select('foo').order({ create_time: 'ASC' })
  } else {
    return q.select('bar').order({ create_time: 'DESC' })
  }
})
```

I realise that the example above gives a union of `SelectResult` as a resulting type, but in many cases that is acceptable.

If you somehow don't want to introduce complex return types, I suppose that it will be possible to restrict typings of the modifier callback to return `T` so that at least all methods that don't modify `T` work (such as: `order`, `limit`, `offset`, etc.)

**Comment by romeerez** [comment]
Just to know if that could work, I did such a little test:

```ts
const ctx = { foo: true };

const modify = (q: typeof db.user) => {
  return ctx.foo ? q.select('name') : q.select('password');
};

const q = modify(db.user);

const result = await q.take();

if ('name' in result) {
  result.name = 'name';
} else {
  result.password = 'password';
}
```

Works as expected, good.

Why not add it:
- this feature may help initially when combining the query, but complicate things later when dealing with the union response
- I have fierce battles with TS and in more complex cases TS is winning: it refuses to process deeply nested queries, or queries with many chains in them. If we write selects sequentially like `select('foo').select('bar').select('baz')` there is a limit, TS will refuse after maybe 7-8 such selects. I didn't check this yet so maybe it's not the case, but if this feature will half this limit, better to not implement it. Anyway, this feature seems to make the work for TS much harder, which is something I'd like to avoid.
- Kysely has [this `$if` method](https://www.kysely.dev/docs/recipes/conditional-selects). Maybe there is a reason why it is better for TS - need to research.

**Comment by IlyaSemenov** [comment]
I see. That's why the second idea was to limit this to non-type-modifying methods only. I mean, there is already a where builder. I would similarly like to e.g. change ordering on the fly, without reassigning temporary queries into temporary variables or using `makeHelper` for one-off scenarios. This shouldn't introduce any burden on TS.

**Comment by romeerez** [comment]
[Kysely release 0.25](https://github.com/kysely-org/kysely/releases/tag/0.25.0):

> The $if method should no longer cause performance issues or excessively deep types

So they indeed had performance and types issues with it and had to do something to optimize it. In the case of `modifyQuery`, a user has more options on what to do inside the callback and what to return, so I'd expect it would be much harder if even possible to optimize.

> That's why the second idea was to limit this to non-type-modifying methods only

I overlooked it, yes, then there would be no problems. But semantically not very well to disallow `select`.

And I have an additional idea for it, thanks to kysely for inspiration. There is [$assertType](https://www.kysely.dev/docs/recipes/excessively-deep-types) which takes the result type in a generic.

So we could have such a `modifyQuery` that doesn't affect on result type by default, and it may even try to resolve unions when the callback has multiple `select`'s, but it also allows providing a result type via generic, that solves the pains for TS and allows to build flexible queries.

**Comment by IlyaSemenov** [comment]
I just thought that the proposed `modify` helper is already possible with `makeHelper`:

```ts
const helper1 = db.user.makeHelper((q, ctx: Context) => {
  if (ctx.foo) {
    return q.select('foo').order({ create_time: 'ASC' })
  } else {
    return q.select('bar').order({ create_time: 'DESC' })
  }
})

const users = await helper1(db.user.order().select("id", "name"), ctx)
```

The inline method is kind of syntax sugar doing exactly the same. So I believe there is no reason to allow `makeHelper` to return union types but prevent users from doing the same with quick inline method...

**Comment by romeerez** [comment]
Oh, indeed! There is a `makeHelper` that already allows that. Yes, I agree, adding a `modifyQuery` that has similar types as the `makeHelper` would be more-or-less trivial and won't introduce more troubles than there already are.

Another interesting question is how to be about the `ctx`, so you could assign a `currentUser` or similar to it at the beginning of request processing, and then access it in various query helpers. I imagine that in the future `ctx` will reside on queries, and be accessed as `q.ctx`, so it won't require an additional argument in the helpers.

**Comment by romeerez** [comment]
I don't know where to find the time for everything, but sure, at some point it should be there.

**Comment by IlyaSemenov** [comment]
Consistently with `makeHelper`, it could be not `modifyQuery` but `useHelper` (it will naturally accept a helper function then). This will also be consistent with the proposed [useRepo](https://github.com/romeerez/orchid-orm/discussions/101#discussioncomment-6017568).

**Comment by romeerez** [comment]
Not sure about the naming, `modify` (for the `modifyQuery` in Objection) sounds perfect to me, `makeHelper` could be renamed if we have better options, `useRepo` is good. I'd prefer the names that are subjectively sound better to a consistency.

**Comment by IlyaSemenov** [comment]
Agreed, `makeHelper` sounded a bit too generic in the first place, but then how else would you call it... `makeModifier`? Anyhow, totally your call, I was just throwing some ideas. :)

**Comment by romeerez** [comment]
Ready, added the [modify](https://orchid-orm.netlify.app/guide/query-methods.html#modify) method.
