### ISSUE TITLE
Bringing the pacakges under a single namespace

### ISSUE THREAD

**Issue by jmcdo29** [romeerez/orchid-orm#11]
First of all, very excited for this ORM and set of libraries. I saw your post on reddit and am very much looking forward to tinkering with this. 

Would you consider making the `@orchid` organization on `npm` and publishing your packages under `@orchid/pqb` or `@orchid/orm` etc? This way it's clear where they are coming from. 

Totally just a suggestion, but I think the branding could do well :smile:

**Comment by romeerez** [comment]
I was thinking about this too, but `@orchid` is taken.

`@orchid-orm/orm` - no.

Renaming it to something new? I renamed it once already, and I like the new name, it means something to me.

**Comment by jmcdo29** [comment]
> I was thinking about this too, but `@orchid` is taken.

Oh interesting. I didn't find it on npm hence my suggestion. You might be able to message the owner and see if they'll release it. I did that with `@ogma`

**Comment by romeerez** [comment]
When I'm trying to create an organization "orchid" it pops up with "this name is not available", but there are no packages with this org, so I can't even find them

**Comment by micalevisk** [comment]
try this out https://github.com/search?q=%22%40orchid%2F%22+path%3Apackage.json&type=code

**Comment by jmcdo29** [comment]
Hmm, dang. I did see an `@orchidjs` which I guess npm might be making sure there's no confusion with. It's a shame, but understandable. I like the name `orchid` a lot so I wouldn't suggest changing that, especially if it means something to you.

I'll close this out as the suggestion can't take place. Looking forward to what comes from this ORM
