### ISSUE TITLE
New method: none()

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#111]
As a developer, I would like to have a new method in `QueryMethods` that is guaranteed to make no database query and return empty result set when the query is evaluated (or `undefined` for `SetQueryReturnsOneOptional`, or throw for `SetQueryReturnsOne`).

That will repeat what Django has been having for years: https://docs.djangoproject.com/en/4.0/ref/models/querysets/#none

The use case is creating chainable query builder functions, where one of the chains might decide that it should not return any data at all. Consider this:

```ts
function get_foos(ctx: Context) {
  return ctx.allowFoos ? db.foo.order({ create_time: "DESC" }) : db.foo.none()
}

httpServer.get("/foos1", (ctx) => {
  return get_foos(ctx).select("data1")
})

httpServer.get("/foos2", (ctx) => {
  return get_foos(ctx).select("data2")
})
```

Related ticket for Objection.js which was never implemented: https://github.com/Vincit/objection.js/issues/2184

(In fact, I might try to come with a PR for this if there were some initial guidance. As promising as it is, I see Orchid suffering from the bus factor of 1. Not sure if this issue is a good one for start though.)

**Comment by romeerez** [comment]
How is it different from the following:

```ts
function get_foos(ctx: Context) {
  return ctx.allowFoos ? db.foo.order({ create_time: "DESC" }) : Promise.resolve(undefined)
}
```

Or, if the function is `async`, it will be wrapped into Promise automatically:

```ts
function async get_foos(ctx: Context) {
  return ctx.allowFoos ? db.foo.order({ create_time: "DESC" }) : undefined
}
```

**Comment by romeerez** [comment]
Here is this method from Ruby: https://apidock.com/rails/v4.0.2/ActiveRecord/QueryMethods/none

It returns an empty array as shown in the example, and this makes sense.

So our `none` should act like the following:

```ts
type Table = { ... } // type of our table

// return type stays unchanged, app can still expect Table[], but it will be an empty array
const arr = await db.table.none()

// this should change the type from `Table` to `Table | undefined`
const one = await db.table.find(123).none()

// findOptional already returns `Table | undefined`, and the `none` doesn't change that
const one2 = await db.table.findOptional(123).none()

// this should change return type from `number` to `number | undefined`
const value = await db.table.get('id').none()

// and so on, there are also `getOptional`, `rows`, `exec`
```

At first glance, it seemed relatively simple, but after a closer look this make require having some fun with the types and the checks, so I'd not say it's a simple addition.

I'm trying to make some progress with a big task of callbacks so won't be eager to jump into this one any time soon, I'd love you to try making the first feature PR in the whole history of Orchid ORM, and I'll try to help with difficulties.

**Comment by IlyaSemenov** [comment]
What I had in mind didn't involve changing types:

```ts
// I'd prefer this to crash with some kind of NotFound exception
// same as if the SQL query returned no rows
const one = await db.table.find(123).none()
```

Essentially the effect should be the same as adding ``.where(db.table.sql`1=2`)``.

This is because I see this primarily used for security purposes, such as limiting access to objects with a condition, and in some case limiting access completely with `.none`. I see that happening in some kind of middleware/helper/modifier (outside of normal business flow) and don't want to disrupt types and force user to do unnecessarily checks for undefined result. If user-land code says `db.table.find(123)` then usually user means it.

I just checked (in action) that Django works like that, too, and crashes with `DoesNotExist`. Not sure about Ruby ActiveRecord, I don't have any projects and the documentation doesn't make it clear how `NullRelation` chains with the `.find` method.

That said, what you suggest of course also makes sense, it just serves a little different purpose I think.

**Comment by romeerez** [comment]
Agree, let it throw when it's chained to `find`, `take`, `get`, etc.

**Comment by romeerez** [comment]
Ready! [none](https://orchid-orm.netlify.app/guide/query-methods.html#none)

**Comment by romeerez** [comment]
This is the 100th closed issue! :tada:
