### ISSUE TITLE
t.record in json types is documented incorrectly

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#112]
The documentation says:

> If you want to validate the values of an object against some schema but don't care about the keys, use t.record(valueType):

```ts
        // type will be { [k: string]: number }
        record: t.record(t.number()),
```

This is however not true:

<img width="492" alt="image" src="https://github.com/romeerez/orchid-orm/assets/128121/4d55054e-1e7c-4216-bcfa-b5a88f0c1543">

and complex types when I don't care about the keys are also not possible:

<img width="927" alt="image" src="https://github.com/romeerez/orchid-orm/assets/128121/19f32994-c1f2-470e-aa26-4d6a4ad0820c">

Explicitly providing the key type works fine:

<img width="527" alt="image" src="https://github.com/romeerez/orchid-orm/assets/128121/b97b3f5f-3027-4990-bb7a-32fd384606ce">

- orchid-orm 1.10.2
- typescript 5.0.4

**Comment by romeerez** [comment]
Apparently, it was solved along the way, can't reproduce. Please reopen if it still exists on your side.

**Comment by IlyaSemenov** [comment]
Right, I can't reproduce it either now (I've upgraded orchid-orm since then).
