### ISSUE TITLE
migrate redo does not update the table definition file.

### ISSUE THREAD

**Issue by akutruff** [romeerez/orchid-orm#115]
I'm not sure if this is by design or not, but when following the quickstart, I added a new migration for the `sample` table as instructed.  It worked fine.  However, when I rolled it back, and then added another column in the same migration file, `migrate up` did not update the `sample.table.ts` file.  Is this intended? The [docs](https://orchid-orm.netlify.app/guide/migration-commands.html#redo) say:

>redo[#](https://orchid-orm.netlify.app/guide/migration-commands.html#redo)
>Shortcut for rollback + migrate. It is useful when you edit a migration and want to reapply it.

That lead me to believe that the table file should be updated for the sake of rapid iteration.  Otherwise, I have to manually copy/paste or delete the file manually each time.

**Comment by romeerez** [comment]
I hope it's not a big trouble for you, auto code updater is indeed yet to be improved and sometimes doesn't do things that are expected. For a good part: it does its best to not screw up the existing code. Automatically undoing and re-applying new changes for the migration was a confusing task for the code updater, so this is skipped in the case of redo.

**Comment by akutruff** [comment]
Hmm.  From looking at the source it looks like you’re parsing the actual typescript and trying to preserve user edits to .table.ts files as well. Is that correct? If so I can see the challenges and fragility there.On Jun 8, 2023, at 3:39 PM, Roman Kushyn ***@***.***> wrote:﻿
I hope it's not a big trouble for you, auto code updater is indeed yet to be improved and sometimes doesn't do things that are expected. For a good part: it does its best to not screw up the existing code. Automatically undoing and re-applying new changes for the migration was a confusing task for the code updater, so this is skipped in the case of redo.

**Comment by romeerez** [comment]
> Is that correct? If so I can see the challenges and fragility there

Yes, super fragile and done with an abnormal code that's very hard to maintain.

In some cases it works well and helps a lot: if you already have a database in the existing project, this will generate all the table files, all the columns, all the foreign keys, some relations, and so on with just one command.

In some cases, it helps partially, and in some cases, as you noticed with `redo`, it's leaving it up to the developer.

**Comment by romeerez** [comment]
Finally, the old appCodeUpdater is gone and now migrations can be generated from tables defined in the code - [docs](https://orchid-orm.netlify.app/guide/orm-and-query-builder.html#generate-migrations).
