### ISSUE TITLE
Proposal for new migrations design

### ISSUE THREAD

**Issue by akutruff** [romeerez/orchid-orm#120]
Rejected and moving to separate project.

**Comment by akutruff** [comment]
Let me know if this sounds like it would make the cut and if so, I'll start punching keys.

**Comment by IlyaSemenov** [comment]
### Concept

Storing database structure snapshots is what others have been doing too, so this is not heresy and madness.

For example, Django South migrations had [ORM freezing](https://south.readthedocs.io/en/latest/ormfreezing.html) 14 years ago. By the way, new Django built-in migrations do not store snapshots verbatim, instead they derive the previous state by traversing the full graph starting from the initial migration and 'applying' migration primitives (such as `AddTable`, `AddColumn`, `AlterColumn`, `DropTable`, etc.) to the virtual representation of the database. Either way, this is far more progressive to migration libraries that I've seen in Node.js ecosystem which basically do a sequential running of SQL chunks (with different kinds of bells and whistles attached).

### Runtime detection of changes

My primary concern is runtime `getChanges`. I think that changes should be code-generated rather than detected in runtime.

_"specifying that a rename is occuring will replace the default which would have dropped the title and added the subject"_: how would a user know that the default was dropping the title? How would they know that dropping the title was there **at all**? They could have changed several fields and forget about this one. Boom! All titles are gone.

Instead, I believe the code generator should emit something along the lines:

```ts
/**
 * Old versions: post_20230609162219
 * New versions: post_20230609162218
 */
change(async (db) => {
  await db.dropColumn('post', 'title')
  await db.addColumn('post', 'subject', (t) => t.text(3, 100).unique())
})
```

Then user is supposed to review this and update accordingly if they wish.

### Copying the actual table typescript files

Migrations operate with tables and their columns, but not with the rest. Why would we copy the entire files? That brings the following challenges:
- `*.table.ts` import other tables (for defining foreign keys and relations). These will break, they must be rewritten to import the versioned tables instead.
- `**.table.ts` may include other imports and have other non-related stuff. For example, I keep JSON fields data interfaces in the table files, possibly importing some helpers for them. This will also break.

So I believe the versioned tables should be code-generated rather than copied, emitting minimum table class only having `table` and `columns` (and probably `relations` to simplify data migrations), importing the last versions of the versioned relation tables.

### Do we need the actual versioned table files?

Considering the approach of code-generating versioned table classes, do we actually need to store them in separate files?
I believe they perfectly belong to the actual migration files. So each migration may simply export the new versions of all tables it affected. No heresy and madness . :)

### Merging migrations

Two developers may add a migration for the same table (in the same state) in two separate git branches. Once the branches are merged, it will be not clear what to take as the "previous" version of that table when generating a next migration. Django solves that with `makemigrations --merge` command which generates a special kind of "merge" migration before use may proceed with "normal" migrations. I suppose we will need something like that, too.

**Comment by akutruff** [comment]
Oh cool.  I didn't know that this in some sense had been tried before.

> My primary concern is runtime getChanges. I think that changes should be code-generated rather than detected in runtime.

Well, that leads us right back to the core problem of the current approach, right? We want to be able to edit files and if the code generator is also going to be trying to edit the same file as we work, we'll end up with the same level of fragility.  

Runtime change detection will always be more robust against code generation.  What if code generation gets things wrong?  What if it changes my code that I wrote?  With `getChanges` the same exact logic that drives code generation can happen for determining the delta but now the user has ultimate freedom in how to customize and workaround the inevitable things that they need to do that we didn't anticipate.  Also, now the user has the opportunity to use middleware to do their own diffing as well.  I am using 10 TimeScaleDB hypertables in my project right now and to create those tables, I have to always call `SELECT create_hypertable()`  With middleware, I could put in the table definition file with a Javascript Symbol field called HYPER_TABLE or something that my middleware can read to automatically create migrations.  Alternatively, making the code generator have middleware and making the user deal with ASTs sounds like trouble.

>They could have changed several fields and forget about this one. Boom! All titles are gone.

I know I wrote a lot in my proposal, but I actually addressed this:  

"Note as a safety measure, there could be an option that a user must explicitly declare / approve dropped columns by having to write postChanged.someColumn.drop()"

When the user runs `db migrate` the cli can also output in the terminal detected warnings and even spit out what you put above but do so in the terminal so the user can quickly copy paste it to rectify the error:

```bash
> db migrate
SAFETY ERROR: You have either dropped or renamed something.  You must explicitly declare that in your migration.

If you intended to drop the the thing, please add the following or use changes.rename()

--- Post Table

changes.dropColumn('post', 'title')
```

Git will also show in the diff what has changed just like it does today.

>helper methods that are aware of how to reverse things back to the previous state

Agreed.  I think this is accomplishable by a combo of storing a bit of schema history in the migration table while also continuing to provide a way for users to provide custom down migration code just like it is designed today. (I like how you did that by the way.  Having it in the same place is very clean.)

#### Copying table files

> Migrations operate with tables and their columns, but not with the rest. 
Sorry, not following what you mean here.  What do you mean by "rest?"  Are you talking about indexes, or enums or something? Those should work perfectly fine as well.  

> *.table.ts import other tables (for defining foreign keys and relations). These will break, 

Good point, using `index.ts` in the tables directory and managing imports that way fixes it.  (Using index.ts regardless is a better practice.)

If they are importing via an 'index.ts' instead of via path imports, then the versioning code can manage an `index.ts` in the versions folder and use subdirectories instead.  That actually ends up being much much cleaner.

I won't list all the file contents but here's the gist - all imports now just use this style `import { PostTable, CommentTable } from '.'` and no longer import from individual files.  

File structure now with subdirectories:
`
tables/index.ts
tables/post.ts
tables/comment.ts

versions/101891581_createPost/index.ts
versions/101891581_createPost/post.ts
versions/101891581_createPost/comment.ts
`

`/versions/101891581_createPost/index.ts`
```
// DO NOT EDIT Generated file.
export * from 'post'
export * from 'comment'
```

`versions/101891581_createPost/post.ts`
```
import { CommentTable } from '.';
// rest of code
```

> table files, possibly importing some helpers for them. This will also break.

Would have to look at the bundler you're using, but you can use absolute path imports or just use imports from a package rather than using paths.  In general moving away from complicated relative paths in general is a good way to go.  However, these should still be able to work just fine.

>I believe the versioned tables should be code-generated rather than copied, emitting minimum table class only having table...

I say let the user define the tables file they want and give them complete access to those table files.  Why do we know better than them?  Code generation should always be a last resort, and is not necessary here.

>Considering the approach of code-generating versioned table classes, do we actually need to store them in separate files?

Yes, if we want to be as good of a DX as Prisma which we can be, and I'd say this design has the potential to surpass Prisma.  Having a single source of truth and directly editing it will always be the most natural and clear way to work for humans.

> Merging migrations
Yeah, this should be addressed and needs to be taken into account.  Sqitch keeps a file with the migration order in them.  I think using a rebase style approach where one migration must update it's timestamps to be after the other could get the job done as well.  I think this is mostly decoupled from the rest of the design.

**Comment by romeerez** [comment]
The current auto-code-updater tool does a great job to generate files from an existing database with `db pull`, and it tries to help with editing files as much as it can, but not completely, that's true it's not the best DX.

I agree it would be a great DX improvement and loved by the community to make it somehow similar to Prisma or Drizzle, which are generating migration files from the app code.

For me, migrations DX improvement has low priority, as I'm fine writing them manually and there are a lot of other things to do. This would require thorough research, being very careful to not screw up anything, be designed to be as easy and as straightforward as possible, so I was leaving it for the future.

As the first step for this improvement, need to research how Prisma and how Drizzle are doing it, look at other tools, and find the best way.

I didn't yet test how Prisma or Drizzle are behaving, but I read somewhere that the Drizzle cli is interactively asking the user when there is ambiguity. So definitely need to test them out, compare, and be inspired.

The migration should be obvious and clear. When reviewing PR of a colleague, you should be able to read it and understand it exactly.

```ts
import { change } from '../dbScript';
import * as previous from '../versions/post_20230609162218';
import * as current from '../versions/post_20230609162219';

change(async db => {
  //returns the default changes that are detected
  const postChanges = getChanges(previous.PostTable, current.PostTable);

  //specifying that a rename is occuring will replace the default which would have dropped the title and added the subject. 
  postChanges.renameColumn('title', 'subject');

  await db.applyChanges(postChanges);
});
```

Okay, I can see that we're renaming a column here. But what else? It does something else. We can read the old table, new table, diff them - all in our head - and still, we're not sure if the ORM will apply the diff in the exact same way as we calculated in the head.

So instead of these new methods, let's generate migrations with the existing methods.

```ts
import { change } from '../dbScript';

change(async (db) => {
  await db.changeTable('table', (t) => ({
    newColumn: t.add(t.text()),
    oldColumnName: t.rename('newColumnName'),
    dropColumn: t.drop(t.integer()),
  }));
});
```

From this, we can see exactly what's going to happen with our precious important production database.
And if the generator did something unwanted, it can be edited.

**Comment by akutruff** [comment]
You have got diffs on the actual table files.

I’m offering to write this so…

**Comment by akutruff** [comment]
Git diffs I meanOn Jun 10, 2023, at 12:39 PM, Andy Kutruff ***@***.***> wrote:﻿You have got diffs on the actual table files.I’m offering to write this so… On Sat, Jun 10, 2023 at 12:35 PM Roman Kushyn ***@***.***> wrote:
The current auto-code-updater tool does a great job to generate files from an existing database with db pull, and it tries to help with editing files as much as it can, but not completely, that's true it's not the best DX.
I agree it would be a great DX improvement and loved by the community to make it somehow similar to Prisma or Drizzle, which are generating migration files from the app code.
For me, migrations DX improvement has low priority, as I'm fine writing them manually and there are a lot of other things to do. This would require thorough research, being very careful to not screw up anything, be designed to be as easy and as straightforward as possible, so I was leaving it for the future.
As the first step for this improvement, need to research how Prisma and how Drizzle are doing it, look at other tools, and find the best way.
I didn't yet test how Prisma or Drizzle are behaving, but I read somewhere that the Drizzle cli is interactively asking the user when there is ambiguity. So definitely need to test them out, compare, and be inspired.
The migration should be obvious and clear. When reviewing PR of a colleague, you should be able to read it and understand it exactly.
import { change } from '../dbScript';
import * as previous from '../versions/post_20230609162218';
import * as current from '../versions/post_20230609162219';

change(async db => {
  //returns the default changes that are detected
  const postChanges = getChanges(previous.PostTable, current.PostTable);

  //specifying that a rename is occuring will replace the default which would have dropped the title and added the subject. 
  postChanges.renameColumn('title', 'subject');

  await db.applyChanges(postChanges);
});
Okay, I can see that we're renaming a column here. But what else? It does something else. We can read the old table, new table, diff them - all in our head - and still, we're not sure if the ORM will apply the diff in the exact same way as we calculated in the head.
So instead of these new methods, let's generate migrations with the existing methods.
import { change } from '../dbScript';

change(async (db) => {
  await db.changeTable('table', (t) => ({
    newColumn: t.add(t.text()),
    oldColumnName: t.rename('newColumnName'),
    dropColumn: t.drop(t.integer()),
  }));
});
From this, we can see exactly what's going to happen with our precious important production database.
And if the generator did something unwanted, it can be edited.

**Comment by romeerez** [comment]
@akutruff responding via email produces junky duplication here in github, try removing everything that's quoted when responding.

> You have got diffs on the actual table files.

Do you mean you've already implemented the diffing of one table version against another?

> I’m offering to write this so…

That's awesome, just. I'm responsible for where this project goes, and the research is on me - need to try out mentioned ORMs, note what's good about them, and what's not so good, discuss it with you, and make decisions.

You're going to use a diff between the previous source code and the updated source code. I'm not yet convinced if that's better than diffing current code against a current database schema, what if it's better. Need to research.

**Comment by IlyaSemenov** [comment]
@akutruff 

> Well, that leads us right back to the core problem of the current approach, right? We want to be able to edit files and if the code generator is also going to be trying to edit the same file as we work, we'll end up with the same level of fragility.

Not exactly so: the current generator generates db tables which is what user is more likely to customize, compared to migrations which are typically one-off-and-forget and are therefore a better target for code generation.

However, I see your point now. You're telling that user will be able to progressively edit the table and redo the same migration without have to update it, as the logic will be incapsulated into `getChanges()`?

I am afraid this approach will make it impossible/very hard to come up with non-trivial migrations. Sometimes one needs to run some kind of raw SQL in between the migration queries, such as for filling defaults of a new non-nullable field (create it as nullable, fill and alter to be non-nullable). While typical scenarios as I mentioned could be implemented with some kind of predefined hooks, great effort will be needed to make it truly flexible.

**However, I think this could live as one of the options**, for those who prefer either one. After all, the migrations generator may emit runtime `getChanges()`, and it also may emit build-time constructs (basically hard-wire what `getChanges()` would have done in runtime). Internally they will be using the same primitives and the same diff mechanism.

**Comment by akutruff** [comment]
> That's awesome, just. I'm responsible for where this project goes, and the research is on me - need to try out mentioned ORMs, note what's good about them, and what's not so good, discuss it with you, and make decisions.

Of course.

**Comment by akutruff** [comment]
> I am afraid this approach will make it impossible/very hard to come up with non-trivial migrations. Sometimes one needs to run some kind of raw SQL in between the migration queries, such as for filling defaults of a new non-nullable field (create it as 

I don't think you're getting this design then.  EVERYTHING is user editable including the migration files.  I explicitly accounted for that as nothing should be .  The `getChanges()` just returns data that you can take or leave.  You can then apply the changes when you wish.  You can run raw SQL in the migration well before or after you apply changes.   That's the whole point.

**Comment by IlyaSemenov** [comment]
> Would have to look at the bundler you're using, but you can use absolute path imports or just use imports from a package rather than using paths. In general moving away from complicated relative paths in general is a good way to go. However, these should still be able to work just fine.

No, I mean a different thing. Let's say I have table `foo.table.ts` in which I'm putting some extra stuff. For that stuff, I do `import helper from 'some-helper'`. The new migrations module copied that file as a versioned one. Now years pass by, that table could have been long deleted, and say I decided to upgrade `some-helper` or uninstall it altogether. The migrations break. Am I supposed to port the changes into all versioned copies of `foo.table.ts`? Not a pleasant DX. That's why I believe only the table class should be stored and not anything else.

**Comment by IlyaSemenov** [comment]
> You can run raw SQL in the migration well before or after you apply changes. That's the whole point.

As I demonstrated in my example, sometimes I need to run SQL **in between** the migration primitives. Not before and not after the whole set of changes, but in the middle of them. I don't see how that is possible with `getChanges()`. Am I supposed to like insert my commands 'at position 5' in some kind of array that `getChanges()` return? Fragile and counter-intuitive.

**Comment by akutruff** [comment]
Oh no, I didn't realize that I wasn't talking to romeerez this whole time!!  No wonder I'm confused.  Stupid mobile!

**Comment by akutruff** [comment]
> Am I supposed to like insert my commands 'at position 5' in some kind of array that `getChanges()` return? Fragile and counter-intuitive.

No, it's just savascript.  `applyChanges()` is just a helper.  If you want to include it in a transaction, it's up to you.  You can do whatever you want. It's completely up to you.

**Comment by IlyaSemenov** [comment]
>  I didn't realize that I wasn't talking to romeerez this whole time

You were talking with me and him, too :). If you and/or @romeerez prefer I can step aside in this discussion, no problem.

**Comment by IlyaSemenov** [comment]
> No, it's just savascript. 

Will you please outline how would a migration look if I had the table `user` and then I inserted two fields to it: `middle_name` (nullable for simplicity) and `country_id` (non-nullable foreign key, which has to be filled with raw SQL once)? Will it involve `getChanges()` at all?

**Comment by akutruff** [comment]
Yes, I would like to hear more from romeerez before I get into the weeds more.

**Comment by romeerez** [comment]
I don't like the `getChanges` and `applyChanges`, (commented that above), because it makes the migration file non-obvious.

@akutruff the ORM could write a migration with all the changes explicitly included, and it would be a better DX, why not, am missing something?

**Comment by akutruff** [comment]
> I don't like the `getChanges` and `applyChanges`, 

All the ways you can see what's happening:

1. Git history of post.ts
1. The schemas are in the source tree and you can look at them.
1. The migration file contains anything non-obvious, that doesn't follow the defaults.  Most of your migration files won't have anything but the boilerplate in them.  

Don't read this as snarky, because I don't mean it to be, but it's the same thing - How Orchid and other ORMS form relations in the underlying tables is non-obvious, but we learn the abstraction and default to save on repetition.  The same applies here.

If you really want a log of what happened, the actual executed SQL could be logged a `.sql` file if you want 100% history in there.  That applies to even the current design.

> @akutruff the ORM could write a migration with all the changes explicitly included, and it would be a better DX, why not, am missing something?

I don't want the code generator to clobber my custom code in the migration file.  If I want to execute JavaScript in the migration file where I read a bunch of values from a CSV file in the source tree and do some manual DB operations, I want that as part of the transaction that renames or adds columns.

**Comment by romeerez** [comment]
My vision regarding how it could be done in the best way for DX, is:
1. you're adding/removing/renaming a column/table/something
2. nodemon or something reloads the project and detects that tables doesn't match the current database
3. it generates a migration, saves it to all migrations, applies it

That's the most automated way: the user doesn't have to do anything besides updating the app code. Migration file is generated in an explicit way: if it's adding a column, it will have a corresponding line, if it's removing a column, it will have a corresponding line.

What to do with ambiguous changes? If the ORM isn't sure whether to remove one column and add a new one or just rename it, it will ask about it in the terminal. The worst thing to happen is to lose some data in development, which is not critical, but generated migrations will be reviewed and updated if something.

No "versions" are saved, I'm not getting how it's going to be useful. Only migrations.

Step 2 of detecting changes is optional, there will be a corresponding command to run independently.
Step 3 of generating a migration and applying it also would be achievable by running two separate commands.

**Comment by akutruff** [comment]
> 1. you're adding/removing/renaming a column/table/something
> 2. nodemon or something reloads the project and detects that tables doesn't match the current database
> 3. it generates a migration, saves it to all migrations, applies it

I like adding this to the idea!

> No "versions" are saved, I'm not getting how it's going to be useful. Only migrations.

Because it's a strongly typed record of before and after that you can use when you need to customize a migration.  It also allows for user extension of the migration process for adding things like I described above for custom data types and special things like TimeScaleDB and other DB extensions.    Using runtime based diffing with the table definition history stored in the source tree unlocks that.

**Comment by romeerez** [comment]
I trying to understand, but not yet.

> Because it's a strongly typed record of before and after that you can use when you need to customize a migration.

I'm suggesting having a migration only. It's in TS so it's typed. It's a code so it's customizable.

> It also allows for user extension of the migration process for adding things like I described above for custom data types and special things like TimeScaleDB and other DB extensions.

Okay, what's the problem if it will be only generated migrations, without historical versions?

> Using runtime based diffing with the table definition history stored in the source tree unlocks that.

What does it unlock that's not achievable without it?

**Comment by akutruff** [comment]
I removed getChanges() applyChanges() to illustrate the benefits of having both versions in the source code and not distract from that.  Below ignore all the obviously left out crap and how I'm using the column names from the shapes.

```
import { change } from '../dbScript';
import * as previous from '../versions/post_20230609162217';
import * as current from '../versions/post_20230609162218';

//We are going to add a new column to Post that will be a hash of the title as the slug, 
// and we're going to rename the title to subject.
// IGNORE THE FACT THAT YOU CAN DO THIS IN A SINGLE QUERY!
change(async db => {
  // The current version of the table has a new 'slug' column
  const before = new previous.PostTable();
  const after = new current.PostTable();

  const titles = await db.usingTable(before).where().select('id', 'title');

  //Ignore this line for feedback. This adds the new column  Just completely ignore the details for now.  
  // I'm not using applyChanges() because it's not relevant to this aspect.
  await db.addColumn(after.columns.shape.subject.name);
  
  // Yes this is dumb but treat it as pseudocode.  The key is that we are able to use 'title' in a strongly typed manner now!
  await db.usingTable(after).where().update({    
    slug: db.usingTable(before).get('title').hash()
  });

  //Ignore the ugly for now, but you get the idea.
  await db.renameColumn(before.columns.shape.title.name, after.columns.shape.subject.name);
});

```

**Comment by romeerez** [comment]
I see that the benefit of having versions is the ability to use the previous tables to make queries.

IMO this ability is not worth storing version files and increasing the complexity.

You've put much time into explaining the idea and discussing it, sorry but have to reject it.

When needed, you can construct a table interface in the migration:

```ts
change(async (db) => {
  const table = db('table', (t) => ({
    id: t.identity(),
    title: t.text(),
    slug: t.text(),
  }));

  const titles = await table.select('id', 'title');
  
  await table.updateSomehow(titles)
});
```

Or, to run raw queries:

```ts
change(async (db) => {
  await db.queryBuilder.where().updateRaw`
    UPDATE table_name
    SET slug = hash(title)
  `;
});
```

I see that having already-defined tables can simplify writing similar migrations. But storing each version of the table sounds like an overcomplication which is not worth its benefits.

**Comment by akutruff** [comment]
Fair enough.  I look forward to what you end up doing.On Jun 10, 2023, at 3:44 PM, Roman Kushyn ***@***.***> wrote:﻿
I see that the benefit of having versions is the ability to use the previous tables to make queries.
IMO this ability is not worth storing version files and increasing the complexity.
You've put much time into explaining the idea and discussing it, sorry but have to reject it.
When needed, you can construct a table interface in the migration:
change(async (db) => {
  const table = db('table', (t) => ({
    id: t.identity(),
    title: t.text(),
    slug: t.text(),
  }));

  const titles = await table.select('id', 'title');
  
  await table.updateSomehow(titles)
});
Or, to run raw queries:
change(async (db) => {
  await db.queryBuilder.where().updateRaw`
    UPDATE table_name
    SET slug = hash(title)
  `;
});
I see that having already-defined tables can simplify writing similar migrations. But storing each version of the table sounds like an overcomplication which is not worth its benefits.
