### ISSUE TITLE
[bug] `get('id')` returns wrong type with `upsert`

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#121]
query:
```
const id = await db.table.findBy(xxx).upsert({
  create: {},
  update: {},
}).get('id')
```

The type of `id` is always string, but when `create`, it returns an object of `{id: xxx}`, when `update`, it works as expected and returns a string

**Comment by romeerez** [comment]
Thanks for catching it, I published a fix for this.
