### ISSUE TITLE
Example: Faceted navigation

### ISSUE THREAD

**Issue by matthewmorek** [romeerez/orchid-orm#122]
I'm currently trying to build faceted navigation, which is a common pattern on ecommerce websites, such as Amazon, where the user is able to filter results by ticking all the required attributes.

Here's what it sometimes looks like:
```md
# Locations
## Filters
### Facilities
- [ ] Toilets
- [x] Food
- [x] Parking
- [ ] Shop

### Type
- [o] Indoor
- [ ] Outdoor

## Results
- Location 1
  - Food
  - Toilets
  - Parking
- Location 2
  - Toilets
  - Parking
  - Food
- Location 3
  - Food
  - Parking
```

While I have a loose representation of how this may look like in PostgreSQL, I wonder if you have any examples of building such queries with Orchid?

Here's the table set up in OrchidORM:
```ts
export type Location = TableType<LocationTable>;
export class LocationTable extends BaseTable {
  readonly table = "location";
  columns = this.setColumns((t) => ({
    id: t.uuid().primaryKey(),
    name: t.varchar().unique(),
  }));

  relations = {
    locationFacilities: this.hasMany(() => LocationFacilityTable, {
      primaryKey: "id",
      foreignKey: "locationId",
    }),
    facilities: this.hasMany(() => FacilityTable, {
      through: "locationFacilities",
      source: "facility",
    }),
  };
}

export type Facility = TableType<FacilityTable>;
export class FacilityTable extends BaseTable {
  readonly table = "facility";
  columns = this.setColumns((t) => ({
    id: t.uuid().primaryKey(),
    name: t.varchar().unique(),
  }));
}

export type LocationFacility = TableType<LocationFacilityTable>;
export class LocationFacilityTable extends BaseTable {
  readonly table = "location_facility";
  columns = this.setColumns((t) => ({
    id: t.uuid().primaryKey(),
    locationId: t.uuid(),
    facilityId: t.uuid(),
  }));

  relations = {
    location: this.belongsTo(() => LocationTable, {
      primaryKey: "id",
      foreignKey: "locationId",
    }),
    facility: this.belongsTo(() => FacilityTable, {
      primaryKey: "id",
      foreignKey: "facilityId",
    }),
  };
}
```

The SQL roughly looks like this:
```sql
SELECT l.id, l.name, (
  SELECT array_agg(DISTINCT f.name) 
  FROM facility f 
  JOIN location_facility lf ON f.id = lf.facility_id 
  WHERE lf.location_id = l.id
) AS facilities
FROM location l
WHERE EXISTS (
  SELECT 1 
  FROM location_facility lf 
  JOIN facility f ON lf.facility_id = f.id 
  WHERE lf.location_id = l.id 
  AND f.name = ANY(ARRAY['toilets','parking']::varchar[])
)
```

The final structure of the result array should roughly look like this:
```ts
const ok: {
  id: string;
  name: string;
  facilities: { id: string; name: string; }[];
}[] = result;
```

Is there anything I could improve in my models or relationships between models? Ideally, I'd like to expand filtering from just one attribute `facilities` to multiple, such as `location_type`, etc.

Thanks for your time, and making a one of a kind ORM that I actually like to use. The only thing I'm missing is a few more ecommerce specific examples, as everything else is pretty straight-forward.

**Comment by romeerez** [comment]
Thank you for trying it, I'm focusing on building new functionality so it lacks examples. An e-commerce-like filter is a great example idea for the future.

For this use-case, how about `whereExists`?

Something like:

```ts
await db.location
  .whereExists('facility', (q) =>
    q.where({ name: { in: ['Toilet', 'Balcony'] } })
  )
```

It's mentioned here: [whereExist](https://orchid-orm.netlify.app/guide/relation-queries.html#relation-queries), I see it's not clear how to use it from [where conditions](https://orchid-orm.netlify.app/guide/where.html#whereexists-orwhereexists-wherenotexists-orwherenotexists), so the doc could be improved for this.

**Comment by matthewmorek** [comment]
Thanks for this! I'll give this a shot and report back.

I also updated my SQL example to give you better context of what I'm trying to achieve with Orchid in this case.

Would definitely love more of this stuff showcased, as it helps better understand how SQL works in general.

**Comment by romeerez** [comment]
To select array of facilities you can use `pluck`:

```ts
await db.location
  .select('id', 'name', {
    facilities: (q) => q.facilities.pluck(),
  })
  .whereExists('facility', (q) =>
    q.where({ name: { in: ['Toilet', 'Balcony'] } })
  )
```

**Comment by matthewmorek** [comment]
This seem to be working, although the query matches `any` array elements for `facilities`, not `all`, so the result don't narrowing the list of locations, and in some case will even expand it.

I think my SQL statement may only be partially correct, as I'm likely missing an aggregation/grouping in there. I'll try to tweak my SQL to ensure there's 100% representation in what I'm trying to achieve.

One step forward!

**Comment by romeerez** [comment]
Got the idea, in SQL I'd try to write the following, to select the count of facilities filtered by an array of values, and compare the count to the array length:

```sql
SELECT * FROM location l
WHERE (
  SELECT count(*)
  FROM facility f
  JOIN location_facility lf ON lf.facility_id = f.id AND lf.location_id = l.id
  WHERE f.name IN ('one', 'two', 'three')
) = 3
```

This means a sub-query in `where` and comparing the result of this sub-query to a value. Currently, ORM can't do this, but it's a good use-case, need to enhance the ORM to make it possible.

It could look like so:
```ts
db.location.whereQuery(
  (q) => q.facilities.whereIn('name', ['one', 'two', 'three']),
  3 // or { eq: 3 }, or { lt: 3 }, or { gt: 3 }, etc. Or to compare it to another sub-query.
)
```

Until implemented, you can put raw SQL into `where`.

**Comment by matthewmorek** [comment]
This is amazing. I was wondering whether possible with Orchid, but even if not yet available thank you for helping me with adjusting the query.

I think this will be a great addition for handling one-to-many and many-to-many relationships, which are often present in e-commerce websites, but also in applications such as Airbnb, i.e:

- `Facility` can belong to many `Location` entries
- `Location` can have many `Facility` entries
- `LocationFacility` joins both tables

It would be great if the ORM part supported loading such nested relationships, but for now it works for me with `.select()` query, which uses simple `.join()` statements like so:

```ts
await db.location
  .select("*", {
    region: (q) => q.region.join().where({ name: selectedRegion }),
    locationType: (q) => q.locationType.join().where({ name: selectedType }),
    primaryEventType: (q) => q.primaryEventType.join(),
    facilities: (q) => q.facilities,
  })
```

One thing I liked about Lucid ORM for AdonisJS, was that it helped with structuring queries in a linear way and preload embedded resources. Not sure if it may be helpful, but I'm always willing to share code that works!
```ts
// LocationFilter.ts
public facilities(facilities: []) {
  const selectedFacilities = [].concat(facilities)
  this.$query.whereIn('locations.id', (builder) => {
    builder
      .select('location_facilities.location_id')
      .from('location_facilities')
      .join('facilities', 'facilities.id', '=', 'location_facilities.facility_id')
      .whereIn('facilities.name', selectedFacilities)
      .groupBy('location_facilities.location_id')
      .havingRaw("count('*') = ?", [selectedFacilities.length])
  })
}

// LocationController.ts
const locations = await Location.query()
  .preload('region')
  .preload('locationType')
  .preload('primaryEventType')
  .preload('facilities')
  .filter({ type, facilities })
  .paginate(currentPage, 16)
```

**Comment by bingtsingw** [comment]
I'm from `Lucid` and I think `select relation` can achieve what `preload` does.

In `Lucid`, it uses `await Location.query().preload('region')`, in `Orchid`, it uses `await db.location.select({ region => (q) => q.region.select('xxx') })`

There is one big difference between `Orchid` and `Lucid`(or other Active Record ORMs), `Lucid` uses active record pattern, which selects everything from the database, but `Orchid` need you call a `select('xxx')` to choose exactly what you want. This design pattern makes `orchid` somehow harder to implement, such as hooks, computed columns, theses features are just 'out of box' in active record pattern, but orchid runtime doesn't know which filed user selects, so it can't be implemented easily, you can browse previous issues and discussions for more information if you are interested.

The same problem exists in Prisma, which is more like a query builder, so extending and DRY is hard to achieve.

**BUT**
`Orchid` integrates a powerful [repository pattern](https://orchid-orm.netlify.app/guide/repo.html) which makes it very easy to cleanup and compose your queries.

So, we can use repo pattern to implement a `select` query in `preload`-way
```
const preloadRegion = db.location.makeHelper((q) => q.select({
  region => (q) => q.region.select('xxx');
}));

const repoLocation = createRepo(db.location, {
  queryMethods: {
    preloadRegion: (q) => preloadRegion(q),
  }
});

// in your app to use repoLocation
await repoLocation.select('xxx').preloadRegion()
```

`.select()` can be chained so you can use repos to do a lot of things and DRY your queries.

I was using `Lucid` and `Prisma`, now I'm migrating a medium-sized project to `orchid`, I can confidently  say that `orchid` is quite pleasant to use  : )

**Comment by matthewmorek** [comment]
@bingtsingw Thanks for this context, I will definitely need to DRY my code, since I do need counts for pagination, etc. This is excellent advice on using repos.

I think I have finally solved my filtering issue using Orchid natively, with subqueries, here's the final code which actually works perfectly. Looks like my old Lucid code helped me get there in the end!

```ts
const locations = await db.location
  .select("*", {
    region: (q) => q.region.join().where({ name: selectedRegion }),
    locationType: (q) => q.locationType.join().where({ name: selectedType }),
    primaryEventType: (q) => q.primaryEventType.join(),
    facilities: (q) => q.facilities,
  })
  .where({
    status: "published",
  })
  .whereIn(
    "id",
    db.locationFacility
      .select("locationId")
      .join("facility")
      .whereIn("facility.name", selectedFacilities)
      .group("locationId")
      .having({
        count: selectedFacilities.length,
      })
  )
  .order({
    title: "ASC",
  })
  .offset(skip)
  .limit(take)
```

Now, I need to make sure that I don't filter out entries where `selectedFacilities.length === 0` and `location.facilities.count === 0` (no `facilities` filter applied when some `location` entries have no `facility` entries declared.

**Comment by romeerez** [comment]
@matthewmorek I added a feature for this, [here are the docs](https://orchid-orm.netlify.app/guide/where.html#where-sub-query).

Now you can do the "facet search" in such a way:

```ts
const locations = await db.location
  .select("*", {
    facilities: (q) => q.facilities,
  })
  .where((q) =>
    q.facilities
      .whereIn('name', selectedFacilities)
      .count().equals(selectedFacilities.length)
  )
```

Assuming that the `location` hasMany `facilities` [though](https://orchid-orm.netlify.app/guide/relations.html#hasmany-through) `locationFacility`.

This approach is more efficient than doing `group + having`.
