### ISSUE TITLE
[bug] typescript hint and auto complete seems not work as expected

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#123]
Environment:
```
vscode: Version: 1.79.1

"orchid-orm": "^1.10.6",
"pqb": "^0.12.5"
```

Not everything is broken.
For `db.table.methods`, these methods have right type `db.table.method(params)`.
For `db.table.method(params)`, these params **do not** have right type hint.

<img width="787" alt="image" src="https://github.com/romeerez/orchid-orm/assets/10382462/dc559046-2719-4217-85c7-84dfe5fa83e5">

I'm not sure if this is my own problem or something wrong with the lib

**Comment by bingtsingw** [comment]
But `pqb@0.12.4 && orchid-orm@1.10.5` do have the right type suggestions, `pqb@0.12.5 && orchid-orm@1.10.6` do not work.

Type hint for `0.12.5`
<img width="497" alt="image" src="https://github.com/romeerez/orchid-orm/assets/10382462/d7258054-c397-4629-a71d-f58b9a55390b">

Type hint for `0.12.4`
<img width="606" alt="image" src="https://github.com/romeerez/orchid-orm/assets/10382462/c1c05d15-dc9a-4829-9ca5-4da2ca42cac5">

`expiredAt` is what I want.

**Comment by romeerez** [comment]
> but in where(params), it even do not verify column corrections

It's really not related to recent versions as there were no type changes for `where` or nearby in the last maybe few weeks.

On my side TS highlights wrong columns passed into `where`. VSCode may be confused when switching from one version to another, maybe try to reopen it?

Also, it could be possible that you explicitly listed a specific version of `pqb`, but `orchid-orm` depends on a slightly different version and there are type collisions.

**Comment by bingtsingw** [comment]
Really strange, I'll dig deeper to see what happens.

**Comment by bingtsingw** [comment]
I may found the reason.

This [commit](https://github.com/romeerez/orchid-orm/commit/443fc3c36e6f822e6a1242ea711757b39af941af) changes `orchid-core`, but it's not [published](https://github.com/romeerez/orchid-orm/commit/f0945f82fb95ad26fab8f6b064d61582d0be0e0d)

**Comment by bingtsingw** [comment]
So, when new version of `pqb` and `orchid-orm` `imoprt { TemplateLiteralArgs } from 'orchid-core'`, it's not exists in `orchid-core@0.4.14`

Rebuild and publish should solve this problem

**Comment by bingtsingw** [comment]
With the release of the new version, this issue has been automatically resolved.
