### ISSUE TITLE
update not allowed with whereIn

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#128]
Type-wise, `whereIn` prevents `update` operation:

### Steps to reproduce

```ts
// Argument of type '{ value: string; }' is not assignable to parameter of type 'never'.
await db.table.whereIn('id', [1, 2]).update({ value: "foo" })

// No errors
await db.table.where({ id: { in: [1, 2] }}).update({ value: "foo" })
```

### Expected

The both operations are allowed.

**Comment by romeerez** [comment]
Will fix it later, meanwhile empty where can be used for a workaround: `db.table.where().whereIn('id', [1, 2]).update({ value: 'foo' })`

**Comment by romeerez** [comment]
Fixed
