### ISSUE TITLE
opt-out from text length validation

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#130]
In Postgres, I can create a text field without having to think about its length:

```
test=# create table foo(text text);
CREATE TABLE
test=# \d foo
               Table "public.foo"
 Column | Type | Collation | Nullable | Default
--------+------+-----------+----------+---------
 text   | text |           |          |
```

This is however not the case in pqb:

```ts
export class Table extends BaseTable {
  columns = this.setColumns(t => ({
    description: t.text(), // Error: Expected 2 arguments, but got 0.
```

can we support this somehow?

I know that there is `t.varchar()` but then it doesn't generate `text` columns.

Then, there is `string()` which is an alias for `text()`, yet strings and texts are logically different things in my thinking (basically, string is a one line text, and text is a collection of strings).

---

I like how it works in knex, clean and straightforward:

```ts
await knex.schema.createTable('foo', t => {
  t.string('title') // varchar(255)
  t.string('short', 15) // varchar(15)
  t.text('text') // text
})
```

**Comment by romeerez** [comment]
You can [override columns](https://orchid-orm.netlify.app/guide/columns-overview.html#override-column-types) for this. `text` method in migrations is by default overridden in this way.

`min` and `max` args of text don't have any effect on the db.

It is for the case if you want to use a zod integration (and other such libs in the future), to have a min and max validation on the text. If you don't use zod integration, specifying the `min` and `max` is completely useless, but if you use it this will help prevent empty strings and enormous texts out of the db.

String in JS and TS is the same as the text in the database: unlimited sequence of chats, so it's aliased to string.

**Comment by IlyaSemenov** [comment]
Thank you for the heads up. Yes, I know I can override columns this way, my concern was the defaults somehow didn't feel elegant to me.

Question, with the current methods, is there a way to add a column which is varchar and has minimum length?

**Comment by romeerez** [comment]
There is a `varchar` text column: [column types](https://orchid-orm.netlify.app/guide/columns-types.html#text).

The difference between `varchar` and `text` is that in `varchar` the limit is on a database level, while in `text` method the `min` and `max` will be only checked if you use a validation. The choice is up to you, but I prefer having both `min` and `max` validations on the app level and issuing a validation error if a user is passing something wrong, so choosing the `text`.

**Comment by IlyaSemenov** [comment]
Right, that's what I was pointing to: there is a whole bunch of text column methods but there is no simple way to use varchar and app-level minimum length validation, which is kind of odd. (I suppose `t.varchar(max).as(t.string(min, max))` will do though?)

**Comment by romeerez** [comment]
I don't understand the problem, why can't you use `t.varchar(123)`? In both the app and the migration?

**Comment by IlyaSemenov** [comment]
This won't validate minimum length, will it?

**Comment by romeerez** [comment]
Yes, it will, both on a db level and if you use a zod plugin for validations.

**Comment by IlyaSemenov** [comment]
Sorry, I'm not following. How I see it:
- `t.varchar(123)` will validate **maximum** length (limit) but not the **minimum** length.
- `t.text(1, 123)` will validate both on the app level, but nothing on the database level.

If I want to have a true database `varchar` (say for external tooling) **and** validate minimum length on the app level, there's no primitive allowing that.

**Comment by romeerez** [comment]
Got it, you can set the min with the `min` method: `t.varchar(100).min(10)` - min 10 and max 100
