### ISSUE TITLE
Docs: missing link to `routeHandler` in the guide section

### ISSUE THREAD

**Issue by TAKANOME-DEV** [romeerez/orchid-orm#14]
When following the `building a sample app`, I noticed that there is a missing link to `routeHandler`

![orm-1](https://user-images.githubusercontent.com/79809121/217072442-605d4909-2196-493f-bdbb-ce48d964616d.png)

I would love to open a pr fixing it 🙂

**Comment by romeerez** [comment]
https://github.com/romeerez/orchid-orm-examples/blob/main/packages/blog-api/src/lib/routeHandler.ts#L13

Here is a link, but... this is that kind of TS code that frighten people and is not directly related to the ORM.

How do you think, okay to put the link and leave it, or better to simplify it somehow?

**Comment by TAKANOME-DEV** [comment]
> Here is a link, but... this is that kind of TS code that frighten people and is not directly related to the ORM.
> 
Yeah, it was very scary the first time I read it. But once you understand that it's a helper function to simplify typing and validating input, it becomes understandable (but not those zod utilities :sweat_smile: )
> How do you think, okay to put the link and leave it, or better to simplify it somehow?
>
I would say let's just put the link in their for now (i don't know how to simplify it) and think of how to make it better (less scary).

**Comment by romeerez** [comment]
I have updated the doc at this place to better describe what's going on.

Thanks for pointing!
