### ISSUE TITLE
chain `decrement` and `update`

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#142]
In previous versions, this usage was valid:
```
  await db.test
    .find(xxx)
    .decrement('xxx')
    .update({xxx});
```

But now it throws an error with message: `Only the selecting queries are allowed inside callback of update, update is given instead.`

**Comment by romeerez** [comment]
Thanks for catching it, will fix

**Comment by romeerez** [comment]
@bingtsingw sorry for not responding recently, I'm testing this right now and it works.

Placing `increment` or `decrement` before `update` is not a problem.

The error "Only the selecting queries are allowed inside callback of update, update is given instead." is saying that inside your `update` you have a callback with a query, and that query is trying to perform update, something like:

```ts
await db.test
  .find(xxx)
  .decrement('xxx')
  .update({
    xxx: (q) => q.relation.update(xxx),
  });
```

Was it a case? If the problem still exists, please share a more detailed code.

**Comment by romeerez** [comment]
Thanks for the code sample, the bug was about using the syntax `usages: (q) => q.jsonInsert(...)` after a decrement (or increment).

Published a fix for this.
