### ISSUE TITLE
Fix problem where using custom updatedAt for snakeCase timestamps causes error

### ISSUE THREAD

**Issue by krichards** [romeerez/orchid-orm#144]
##  Background

We have a snakecase table with snakecase timestamps, when attempting to set the updatedAt we get an error saying there are duplicate updated_at in the sql.

The problem seems to be the key for the timestampsSnake case is the 'updated_at' which is incorrect.  Added a test and updated the code.

### Discussed in https://github.com/romeerez/orchid-orm/discussions/143

<div type='discussions-op-text'>

<sup>Originally posted by **krichards** July 20, 2023</sup>
How can I override the updated at when adding and updating rows.

I need to sync with another data source and set the updated at under some circumstances.

I tried adding including the updated_at but it complains that there are multiple instances of the same column.</div>

**Comment by romeerez** [comment]
Thanks for the fix! Published libs with it.
