### ISSUE TITLE
[ask] how to use hooks to add field to before record created

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#146]
This is my use case:

I have a `branch` table, the `code` filed is auto created with the `default()` function provided by orchid, the `qrcode` field is based on the `code` field, how can I use the default-generated `code` field to generate `qrcode` field before created.

```
export class TableBranch extends BaseTable {
  readonly table = 'branch';

  columns = this.setColumns((t) => ({
    ...t.baseColumns(),
    code: t
      .varchar()
      .unique()
      .default(() => init({ length: 6 })()),
    qrcode: t.varchar(),
  }));
```

This is how I do it right now, is there are any simpler way to do it with query hooks.
```
const branch = await db.branch.create({
  qrcode: '',
});

try {
  const qrcode = await generateQrcode(branch.code)
  
  await update db.branch.find(branch.id).update({
    qrcode: qrcode
  })
} catch (err) {
  await db.branch.delete(branch.id)
}
```

**Comment by IlyaSemenov** [comment]
I think [afterCreate hook](https://orchid-orm.netlify.app/guide/hooks.html#after-hooks) is exactly what you're after?

On a side note, when not using hooks, you should really be using transactions instead of creating and deleting:

```ts
await db.$transaction(async () => {
  const branch = await db.branch.select('id', 'code').create({ qrcode: '' })
  const qrcode = await generateQrcode(branch.code)
  await db.branch.find(branch.id).update({ qrcode })
})
```

**Comment by bingtsingw** [comment]
I tried afterCreate hook, but I don't know how to merge fields, and if I omit `qrcode: ''` in `create` method, typescript would throw an error.

I'm not using transaction because the `generateQrcode` is based on a third party service, which may take a few seconds

**Comment by romeerez** [comment]
You can first generate the codes, and then create a record with it, why not?

```ts
const code = generateCode()
const qrcode = await generateQrcode(code)

await db.branch.create({ code, qrcode })
```

`afterCreate` and other hooks are meant to run before/after queries to perform side effects, but they aren't designed for setting default values before creating.

**Comment by bingtsingw** [comment]
Thank you!
"hooks are meant to run before/after queries to perform side effects", that's what I want to confirm
