### ISSUE TITLE
pqb should have @types/pg as dependency

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#148]
`pqb` should have `@types/pg` as a dependency alongside `pg`. It uses it directly:

https://github.com/romeerez/orchid-orm/blob/65cd221067c561697975f8c6173fcd8b84159c81/packages/qb/pqb/src/adapter.ts#L1
https://github.com/romeerez/orchid-orm/blob/65cd221067c561697975f8c6173fcd8b84159c81/packages/qb/pqb/src/adapter.ts#L42

Without `@types/pg`, the types become underdetermined, and some naive typing errors are allowed:

```ts
import { orchidORM } from 'orchid-orm';

// databaseURL type not checked
export const db = orchidORM({ databaseURL: 123 }, {});
```

I think this is a [general consensus](https://stackoverflow.com/a/46011417/189806) that downstream types that are used in package's own exported declarations should be included as a dependency.

[Reproduction](https://stackblitz.com/edit/stackblitz-starters-8urzsz?file=src%2Fdb%2Fdb.ts) (`pnpm dlx orchid-orm@latest` with all questions answered as "no").

**Comment by romeerez** [comment]
Sure, added
