### ISSUE TITLE
Quickstart not working with Neon

### ISSUE THREAD

**Issue by Stoffberg** [romeerez/orchid-orm#15]
Hi Romeerez,

I tried going through the docs to build a demo application for your ORM which I found interesting, but when trying to create the database and initialize the schema it keeps throwing errors since Neon (the platform where I'm hosting the Postgres instance) requires ssl. When enabling SSL in die config or even on the db string itself I get infinitely prompted with the following image:
![image](https://user-images.githubusercontent.com/48858949/217473850-ddbee37d-50e7-4d44-913d-b858e6518334.png)

Any idea why this might be?
If I remove SSL then I get the following:
![image](https://user-images.githubusercontent.com/48858949/217474027-767e6f3f-776a-4e15-8961-f352bac422cb.png)

**Comment by romeerez** [comment]
`db create` database is trying to create a database and requires admin permissions for that.

When using hosting, simply skip this step, database creation is done by hosting. Only run `db migrate` to create tables.

**Comment by romeerez** [comment]
I've improved the script to handle this, and the quickstart docs, thank you for pointing!

Now when trying to create a db and it requires `ssl`, it will output:

```
SSL is required: append ?ssl=true to the database url string
```

And after setting it to `true` and trying to create the database on a cloud hosting, it will warn and confirm:

```
Permission denied to create database.
Don't use this command for database service providers, only for a local db.
? Would you like to share admin credentials to create a database › (Y/n)
```
