### ISSUE TITLE
rake-db duplicates migration, fails to reset with vite-node and no .ts extension

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#157]
rake-db misbehaves when it's started as `vite-node --script dbScript` (not `dbScript.ts`):
* it inserts duplicate records into the migrations table
* it crashes on `reset` command

Reproduction and logs: https://github.com/IlyaSemenov/rake-db-duplicate-migration-reproduction (you only need to run `pnpm install` and then `pnpm db create/migrate/reset`).

Everything works when started as `vite-node --script dbScript.ts` (with `.ts` extension).

**Comment by romeerez** [comment]
I'm very pleased to see you've even spent time to do a reproduction repo, your issues are the best, and thank you so much for keeping opening new ones!

I'll try to figure this out today-tomorrow.

**Comment by romeerez** [comment]
When running `vite-node --script rake` Vite is caching this module under the "rake" name.

But later when importing from it in the migration:
```ts
import { change } from '../rake'
```

Vite is resolving the path to `rake.ts`, so it is missing the modules cache, and the `rakeDb` function is executing a second time.

In such case, rake-db will now throw an error 'Add a .ts suffix to the "rake" when calling it' to prevent unexpected behavior.
