### ISSUE TITLE
Quickstart `db create` not creating all the tables

### ISSUE THREAD

**Issue by Stoffberg** [romeerez/orchid-orm#16]
When running the `db create` command it responds saying the database is created and the version table is created (the base table), but the rest of the tables were not created. Am I missing something, because it just used the base generator which should set up the project for me correctly.

Any guidance would be appreciated.

**Comment by romeerez** [comment]
`db create` does only that, and a separate command `db migrate` is for running all migration files.

**Comment by romeerez** [comment]
I added hints to quickstart to make it clearer.
