### ISSUE TITLE
Rollback transaction / workflow for testing database errors

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#163]
As a developer, I am writing tests that include failing database queries, such as "duplicate key value violates unique constraint". I want to handle these errors easily and gracefully within the unit test code:
- the error must be handled with `expect().rejects.toThrow()` (which doesn't throw itself)
- the test must be able to carry one after the error happened

This is how I was able to handle the case:

```ts
import { expect, test } from "vitest"

beforeAll(async () => {
  await testTransaction.start(db)
})

beforeEach(async () => {
  await testTransaction.start(db)
})

afterEach(async () => {
  await testTransaction.rollback(db)
})

afterAll(async () => {
  await testTransaction.close(db)
})

test("create users", async () => {
  await expect(create_user("foo")).resolves.toMatchObject({ username: "foo" })
  await expect(create_user("bar")).resolves.toMatchObject({ username: "bar" })
  // Test ORM error
  try {
    // I must start a transaction, otherwise 'duplicate key value' will abort the active testTransaction
    await db.$transaction(async () => {
      await expect(create_user("foo")).rejects.toThrow("duplicate key value")
      throw new Error(`error`) // I must throw error to ensure transaction rollback
    })
  } catch {
    // I must ignore the error thrown above
  }
  // Finally, I can safely proceed with more testing
  await expect(create_user("xyz")).resolves.toMatchObject({ username: "xyz" })
})
```

This is very cumbersome and error prone. I was thinking about something like:

```ts
import { expect, test } from "vitest"

test("create users", async () => {
  await expect(create_user("foo")).resolves.toMatchObject({ username: "foo" })
  await expect(create_user("bar")).resolves.toMatchObject({ username: "bar" })
  // Test ORM error
  await db.$transaction(async () => {
    await expect(create_user("foo")).rejects.toThrow("duplicate key value")
    await db.$rollback() // <------- suggestion
  })
  // Finally, I can safely proceed with more testing
  await expect(create_user("xyz")).resolves.toMatchObject({ username: "xyz" })
})
```

Another option could be:

```ts
await db.$transaction({ rollback: true }, async () => {
  await expect(create_user("foo")).rejects.toThrow("duplicate key value")
})
```

**Comment by IlyaSemenov** [comment]
Of course, I could simply do:

```ts
testTransaction.start(db)
await expect(create_user("foo")).rejects.toThrow("duplicate key value")
testTransaction.rollback(db)
```

But what if the code between start and rollback somehow throws unexpectedly? Will that not disrupt the nesting levels of testTransaction?

**Comment by romeerez** [comment]
Transactions are fully automatic, I especially like the way how the db connection of the transaction is implicitly passed under the hood, so users don't have to know and worry about commits, and rollbacks, and cannot forget to pass the transaction instance to a query.

Adding manual controls will complicate things, it would be more things for users to read in docs and to keep in mind, and a good opportunity to shoot into a foot, so I was planning to add `commit`/`rollback` only after I can find a use-case where automated transactions aren't performing well enough.

If we rewrite this code:
```ts
  // Test ORM error
  try {
    // I must start a transaction, otherwise 'duplicate key value' will abort the active testTransaction
    await db.$transaction(async () => {
      await expect(create_user("foo")).rejects.toThrow("duplicate key value")
      throw new Error(`error`) // I must throw error to ensure transaction rollback
    })
  } catch {
    // I must ignore the error thrown above
  }
```

To:
```ts
  const txPromise = db.$transaction(async () => {
    await create_user('foo');
  });

  await expect(txPromise).rejects.toThrow('duplicate key value');
```

It no longer looks cumbersome, and it's even slightly better because now `expect` is outside of callback. When `expect` is inside callbacks there is a little chance that something goes wrong and it is never reached, while the test is green.

Let me know if this code looks good for you.

**Comment by IlyaSemenov** [comment]
Placing `expect` around the transaction promise works just fine for the above scenario, thanks for the tip!

The rest are totally valid points. Although I still somehow feel that `db.$transaction({ rollback: true }, fn)` could make sense while not disrupting the transparency of the transactions, I agree that this should only be revisited if there is a proper use case.
