### ISSUE TITLE
Shortcut method to narrow column type

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#164]
I have a legacy database where I use varchar to keep string codes which can only be one of select values (sort of enums but not using the actual database enums and not the JS level enums). So technically this column returns a runtime string value, which is fine, but I would like it to be typed as `"foo" | "bar"` both in query results and in query parameters.

What I'm currently using is:

```ts
type OrgType = "foo" | "bar"

class OrgTable extends BaseTable {
  columns = this.setColumns(t => ({
    type: t.varchar().parse(t => t as OrgType).encode((t: OrgType) => t),
  })
}
```

I was thinking that this is perhaps a fairly popular scenario which may deserve a dedicated shortcut, such as:

```ts
columns = this.setColumns(t => ({
  type: t.varchar().cast<OrgType>(), // just thinking. or may be .type()
})
```

**Comment by IlyaSemenov** [comment]
Another way to use this would be:

```ts
columns = this.setColumns(t => ({
  data: t.json().cast<MyFancyJsonType>(),
})
```

as there is currently not much value in carefully describing the json structure with the `t => t.object(...)` callback.

**Comment by IlyaSemenov** [comment]
`asType` sounds good.

I must admit I'm not sure how to code the actual function. All the other column methods use generic parameter to infer and alter the type of `this`, and thus are not supposed to accept user-provided parameters:

https://github.com/romeerez/orchid-orm/blob/577903ee8fba02d58b1da8fbe0d7fcc3faec819e/packages/core/src/columns/columnType.ts#L587-L595

However, the imaginary `.asType<Type>()` can't work like this. Ideas?

I can only think of some duct tape like: `.asType(type<Type>())` using a type-hint no-op helper, which I think should only be used as last resort.

Also, I was wondering where the test was supposed to go. I only found `packages/qb/pqb/src/columns/columnType.test.ts`. Shouldn't tests against "core" methods such as `nullable` be moved outside of `pqb`?

**Comment by IlyaSemenov** [comment]
OK, I can actually do something like:

```ts
asType<Type>() {
  return this as SetColumnType<typeof this, Type>;
}
```

Then it's the matter of updating type/inputType/outputType/queryType thoughtfully.

**Comment by romeerez** [comment]
```ts
// base column type
export abstract class ColumnTypeBase<
  Type = unknown,
  // Ops will be used
  Ops extends BaseOperators = BaseOperators,
  InputType = Type,
  OutputType = Type,
  QueryType = Type,
  // Data will be used
  Data extends ColumnDataBase = ColumnDataBase,
> {
  // ...
  
  asType<Type, Input = Type, Output = Type, Query = Type>(
    this: ColumnTypeBase,
  ): ColumnTypeBase<Type, Ops, Input, Output, Query, Data> {
    return this as any;
  }
}
```

Here the main `Type` is passed from the user, 3 additional types can be passed optionally from the user and are defaulted to the main type. `Ops` and `Data` are applied from the class generics.

The last thing, `Ops` and `Data` are applied from the class generics, which isn't good:

```ts
// without `asType`:
const nullableColumn = someColumn.nullable()
nullableColumn.data.isNullable // has type `true`

// with `asType`:
const nullableColumn = someColumn.nullable().asType<number>()
nullableColumn.data.isNullable // no longer `true`, may lead to non-obvious bugs
```

`Ops` isn't going to be changed, so it's not a problem, only the `Data` is. To solve the problem above, each time when changing the column data we would need to also update the `asType` signature to apply the fresh `Data` type.

For simplicity and who knows how this negatively impacts TS performance, I think it's good enough to point in the docs that `asType` should applied before other methods such as `nullable`.

> I was wondering where the test was supposed to go

I moved methods from `pqb` to `core` but didn't move the corresponding tests. Ideally, tests also should be moved, but it's not a big deal.

**Comment by romeerez** [comment]
Idea: `asType` could be a standalone utility function `setColumnType`:

```ts
import { setColumnType } from 'orchid-orm or pqb';

type OrgType = "foo" | "bar"

class OrgTable extends BaseTable {
  columns = this.setColumns(t => ({
    type: setColumnType<OrgType>(t.varchar())
  })
}
```

It would simply replace existing `type`, `inputType`, etc with new ones, without problems as above. Stylistically I don't like it, but it solves the problem.

**Comment by romeerez** [comment]
Another option is to add a generic to text columns.

`text` would have a single optional generic:

```ts
type: t.text<OrgType>()
```

`varchar` without `limit` is the same as using `text` (according to postgres docs). And in case if `varchar` has a limit it doesn't make much sense to apply a union type to it, as it's expected this union is validated somewhere in the app. Or, to have both the custom type and the limit, varchar could have a `limit` method instead of the parameter as it has now. `t.varchar<OrgType>().limit(100)`.

**Comment by IlyaSemenov** [comment]
I don't think we should return `ColumnTypeBase`, we lose the interface of the derived class. It won't be possible to do `t.text().asType().primaryKey()` and I think the entire table type might be broken.

I'm in favour of `setColumnType<Type,Input,Output,Query>(t.column())` or the no-op typings helper `t.column().asType(columnType<Type,Input,Output,Query>())` which I like slightly better as it chains consistently.

**Comment by romeerez** [comment]
Merged your PR, thanks! Here [are the docs](https://orchid-orm.netlify.app/guide/common-column-methods.html#astype) of `asType` for reference.
