### ISSUE TITLE
Mark table column as having database default

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#168]
As a developer working with Orchid ORM that operates against a third party managed database, I would like to mark certain database columns as having a database-level default **without having to provide that default**.

Example use case:

```ts
import { BaseTable } from "../base"

export class UserTable extends BaseTable {
  readonly table = "user"

  columns = this.setColumns((t) => ({
    id: t.integer().primaryKey(),
    data: t.json().hasDefault(), // <----- the proposed method
  }))
}

// This will work, and it should not generate type errors:
await db.user.create({ id: 1 })
```

Without `.hasDefault()`, the code emits a type error:

```ts
// Error: Property 'data' is missing in type '{ id: number; }' but required in type ...
await db.user.create({ id: 1 })
```

**Comment by romeerez** [comment]
Unless it's called with a function, the `default` method is actually not doing anything other than affecting the type to allow omitting the column from `create`.

But still, it serves a good purpose to let programmers see what default is meant to be in there.

```ts
  columns = this.setColumns((t) => ({
    arr: t.json().default([]), // we can see it's an empty array by default
    obj: t.json().default({}), // it's an empty object by default
    text: t.text().default('specific string'),
    num: t.integer().default(123),
  }))
```

So the `hasDefault` doesn't seem to be a good idea IMO.

**Comment by IlyaSemenov** [comment]
Yes, I realise that `.default(value)` only has runtime effect in migrations.

The use case I have in mind is the database with a text column with a default value which may change over time (outside of the development cycle of the app). Currently, I see these options:
* `t.text().default("small")` — this will become a false hint to the developer when the default is later changed to "large".
* `t.text().default("")` — this is a false hint that the default is an empty string (which it's not)
* `t.text().default("<configured by the backend>")` — this is more or less readable, but how is it better than `.hasDefault()`? Also, what would be the equivalent for `t.integer()`?

That's why I was proposing to add a method that knowingly tells that the default is unknown to the ORM, yet it exists.

**Comment by romeerez** [comment]
It's better to have hints than not. I'm imagining how I'm reviewing PRs where coworkers used `hasDefault` just because they're lazy to write a hint and it annoys me.

If the default value is out of your control, let the `hasDefault` be named `unknownDefault()`. So the name suggests it's for a special "unknown" case, not meant to be used out of laziness.

**Comment by romeerez** [comment]
Added [hasDefault](https://orchid-orm.netlify.app/guide/common-column-methods.html#hasdefault), after some consideration, it seems to sound better than `unknownDefault`.
