### ISSUE TITLE
Reduce boilerplate in upsert call

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#169]
As a developer using `.upsert()`, I want to reduce copy/paste and reuse data between create and update clauses.

Based on the example in the documentation (which is by the way using the outdated `selectAll` API, but that's a different issue):

```ts
const user = await User.selectAll()
  .find({ email: "some@email.com" })
  .upsert({
    update: {
      name: "updated user",
    },
    create: () => ({
      email: "some@email.com",
      name: "created user",
    }),
  })
```

I would like to propose an ehancement:

```ts
const user = await User.selectAll()
  .find({ email: "some@email.com" })
  .upsert({
    update: {
      name: "John Doe",
    },
    // upsert automatically passes the update data as a parameter:
    create: (update_data) => ({
      email: "some@email.com",
      ...update_data,
    }),
  })
```

---

To be honest, I believe that upsert should **always** take `update` data and amend it with create data:

```ts
const user = await User.selectAll()
  .find({ email: "some@email.com" })
  .upsert({
    create: {
      email: "some@email.com",
      // name: "John Doe" should be taken from update, unless overridden here
    },
    update: {
      name: "John Doe",
    },
  })
```

I can't really think of a scenario when some field must be set during update but not during create (and even in this edge case scenario, use could override the unwanted field with `field: undefined`). However, that will be backwards incompatible, so that's your take.

**Comment by IlyaSemenov** [comment]
Another idea is:

```ts
.upsert({
  create: { ... },
  createOrUpdate: { ... } // new option. used in both create and update. fields in `create` take precendence.
})
```

This will be backwards-compatible and the naming is self-explanatory.

**Comment by romeerez** [comment]
> I would like to propose an enhancement:

Cool, it's a good one.

> I can't really think of a scenario

Me too, but maintaining this lib taught me that users will always find use cases you could never imagine :) 

> createOrUpdate

No, because `upsert` is for update or create, first it tries to update. And if you want to first create and then update if already exists, there is a `create(data).onConflict().merge()` for this case.

But let's have `data` for this:

```ts
.upsert({
  data: { ... }, // used for both update and create
  create: { ... }, // additional create properties
})
```

`create` could even be optional when providing data.

**Comment by romeerez** [comment]
Ready: [upsert docs](https://orchid-orm.netlify.app/guide/create-update-delete.html#upsert).

Now it can accept `data` object instead of `update`, and passes the data to `create` function.

**Comment by romeerez** [comment]
By the way, I'm not sure if `upsert` was a good idea. Because `create(...).onConflict().merge()` is doing very the same, but with a single query, while `upsert` begins a transaction, updates a record, if the updated count is 0 creates a record, and closes the transaction. On the other hand, I had problems with `onConflict().merge()` when the table had multiple unique constraints and managed to set it just for one constraint, so I'm not sure if it can be a complete replacement for the `upsert`.

**Comment by IlyaSemenov** [comment]
Django has [get_or_create](https://github.com/django/django/blob/6c6606aa014862f1a5c112d688d5e91c0cd9a8d8/django/db/models/query.py#L933-L956):

```py
    def get_or_create(self, defaults=None, **kwargs):
        """
        Look up an object with the given kwargs, creating one if necessary.
        Return a tuple of (object, created), where created is a boolean
        specifying whether an object was created.
        """
        # The get() needs to be targeted at the write database in order
        # to avoid potential transaction consistency problems.
        self._for_write = True
        try:
            return self.get(**kwargs), False
        except self.model.DoesNotExist:
            params = self._extract_model_params(defaults, **kwargs)
            # Try to create an object using passed params.
            try:
                with transaction.atomic(using=self.db):
                    params = dict(resolve_callables(params))
                    return self.create(**params), True
            except IntegrityError:
                try:
                    return self.get(**kwargs), False
                except self.model.DoesNotExist:
                    pass
                raise
```

Ideally, as a developer, I would like to have a helper method that works as follows:
- fetch
- if not exists, create
- otherwise, update _if needed_ (if the provided data doesn't match what has just been fetched)

...all that reliably yet efficiently wrapped into transactions (i.e. the first fetch shouldn't run in a transaction, assuming that 95% of calls will be fetch-don't update).

**Comment by romeerez** [comment]
If no need to update, Orchid has the [orCreate](https://orchid-orm.netlify.app/guide/create-update-delete.html#orcreate) method.

Without a transaction, it won't feel safe. Like in this warning of [get_or_create](https://docs.djangoproject.com/en/4.2/ref/models/querysets/#get-or-create):

> If the fields used in the keyword arguments do not have a uniqueness constraint, concurrent calls to this method may result in multiple rows with the same parameters being inserted.
