### ISSUE TITLE
Property `X` doesn't exist on type `XType`

### ISSUE THREAD

**Issue by matthewmorek** [romeerez/orchid-orm#171]
I have a Next.js setup and assuming the following structure, I'm getting a TypeScript error when using with extended base interfaces.

```ts
// table definition
export type Location = Selectable<LocationTable>;
export class LocationTable extends BaseTable {
  readonly table = "location";
  columns = this.setColumns((t) => ({
    id: t.uuid().primaryKey(),
    name: t.varchar().unique(),
    title: t.varchar(),
  });
};

// interface extension for fetching data
export interface LocationObject extends Location {
  region: Region;
}

// method for fetching location data
export async function getLocationBySlug(name: string): Promise<LocationObject> {
  const result = await db.location
    .select("*", {
      region: (q) => q.region,
    })
    .where({ name: name, status: "published" })
    .take()
    .log();
  return result;
}

// function that calls and fetches data
const { name } = await getLocationBySlug(params.site);
```
The above results in the following error:
```
Property 'name' does not exist on type 'LocationObject'.
```
<img width="599" alt="CleanShot 2023-08-31 at 12 50 31@2x" src="https://github.com/romeerez/orchid-orm/assets/1137994/61509274-0c1d-4f7f-b3c9-0aaf3a852a16">

This doesn't happen when compiling the project though, so I'm not sure whether this is an issue with TypeScript LSP, my editor configuration, or OrchidORM types. Could anyone shed some light on this, please? Am I defining my tables incorrectly?

**Comment by IlyaSemenov** [comment]
@matthewmorek Your code is not complete and doesn't compile. Can you come up with a reproducible example?

I put your code into a self-sufficient module (fixed syntax errors, added Region table, added the `db` singleton) and there are no typing errors in it:

```ts
import { createBaseTable, orchidORM, Selectable } from "orchid-orm"

const BaseTable = createBaseTable()

export type Location = Selectable<LocationTable>
export class LocationTable extends BaseTable {
  readonly table = "location"
  columns = this.setColumns((t) => ({
    id: t.uuid().primaryKey(),
    name: t.varchar().unique(),
    title: t.varchar(),
    region_id: t.uuid(),
  }))
  relations = {
    region: this.belongsTo(() => RegionTable, {
      required: true,
      columns: ["region_id"],
      references: ["id"],
    }),
  }
}

export type Region = Selectable<RegionTable>
export class RegionTable extends BaseTable {
  readonly table = "region"
  columns = this.setColumns((t) => ({
    id: t.uuid().primaryKey(),
    name: t.varchar().unique(),
  }))
}

// interface extension for fetching data
export interface LocationObject extends Location {
  region: Region
}

export const db = orchidORM(
  {},
  {
    location: LocationTable,
  },
)

// method for fetching location data
export async function getLocationBySlug(name: string): Promise<LocationObject> {
  const result = await db.location
    .select("*", {
      region: (q) => q.region,
    })
    .take()
    .log()
  return result
}

// function that calls and fetches data
const { name } = await getLocationBySlug("foo")
```

<img width="731" alt="image" src="https://github.com/romeerez/orchid-orm/assets/128121/4f7d7674-1c61-47ce-b3e5-1edf00f335e8">

Did you try restarting VS code (or simply TS Server)?

---

Also, just a heads up, you may not need the `LocationObject` type. Orchid infers types based on your query automatically:

```ts
// getLocationBySlug is properly typed automatically
export async function getLocationBySlug(name: string) {
  const result = await db.location
    .select("*", {
      region: (q) => q.region,
    })
    .take()
    .log()
  return result
}
```

if you do need the type for external use, sometimes it's better to actually take it from the function return type:

```ts
export type LocationObject = Awaited<typeof getLocationBySlug>
```

**Comment by matthewmorek** [comment]
Thanks. I'll give the inferred types a shot and report back!

**Comment by matthewmorek** [comment]
I've applied the suggestions you've made and used inferred types instead, and it looks like even after restarting [`typescript-language-server`](https://github.com/typescript-language-server/typescript-language-server), the error is still there, which points me at a problem with either its configuration or with the package itself.

Just a note that I use Zed as my IDE, not VS Code (which uses its own TSServer implementation).

I'll keep on digging, and thank you for the tips on type inference as well as fixes to the code!

**Comment by IlyaSemenov** [comment]
Also, try updating orchid-orm if it's outdated. I was testing the code above against 1.17.2.
