### ISSUE TITLE
t.drop crashes on a column with index

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#172]
Consider two migrations:

```ts
change(async (db, up) => {
  await db.createTable("test", (t) => ({
    id: t.serial().primaryKey(),
    foo: t.integer().index(),
  }))
})
```

```ts
change(async (db, up) => {
  await db.changeTable("test", (t) => ({
    foo: t.drop(t.integer().index()),
  }))
})
```

Running `migrate` on them will fail:

```
index "test_foo_idx" does not exist
```

If I change `foo: t.drop(t.integer().index())` to `foo: t.drop(t.integer())` the migrations will complete, but then rolling back the second migration will not put back the index:

```
(1.1ms) ALTER TABLE "test"
  ADD COLUMN "foo" integer NOT NULL
```

Perhaps we can simply disregard `.index()` inside `t.drop()` during `up` migrations?

**Comment by romeerez** [comment]
Published a fix, thanks for catching!
