### ISSUE TITLE
Crash on fetching children of related field

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#173]
Given a database with two tables: card and image, related as:
- a card has (belongs to) one image
- each image has many children images

the ORM query selecting all cards along with its image's children fails in a weird way:

```ts
await db.card.select({ images: q => q.image.children })
```

```sql
SELECT COALESCE("images".r, '[]') "images"
FROM "card"
LEFT JOIN LATERAL
  (SELECT json_agg(row_to_json("t".*)) r
   FROM
     (SELECT *
      FROM "image" AS "children"
      WHERE EXISTS
          (SELECT 1
           FROM "image"
           WHERE "image"."id" = "children"."parent_id")
        AND "children"."parent_id" = "card"."id") AS "t") "images" ON TRUE
```

```
Error: operator does not exist: integer = uuid
```

---

Complete reproduction:

```ts
import { createBaseTable, orchidORM, testTransaction } from 'orchid-orm'

const BaseTable = createBaseTable()

class CardTable extends BaseTable {
  readonly table = 'card'

  columns = this.setColumns(t => ({
    id: t.uuid().primaryKey(),
    image_id: t.integer().foreignKey('image', 'id'),
  }))

  relations = {
    image: this.belongsTo(() => ImageTable, {
      required: true,
      columns: ['image_id'],
      references: ['id'],
    }),
  }
}

class ImageTable extends BaseTable {
  readonly table = 'image'

  columns = this.setColumns(t => ({
    id: t.serial().primaryKey(),
    parent_id: t.integer().nullable().foreignKey('image', 'id'),
  }))

  relations = {
    children: this.hasMany(() => ImageTable, {
      columns: ['id'],
      references: ['parent_id'],
    }),
  }
}

const db = orchidORM(
  {
    databaseURL: process.env.DATABASE_URL,
    log: true,
  },
  { card: CardTable, image: ImageTable },
)

await testTransaction.start(db)

await db.$query`
  create table "card" (
    id uuid not null primary key default gen_random_uuid(),
    image_id int not null
  );
  create table "image" (
    id serial not null primary key,
    parent_id int
  );
`

await db.card.select({
  images: q => q.image.children,
})

await testTransaction.close(db)
```

**Comment by romeerez** [comment]
> the ORM query selecting all cards along with its image's children fails in a weird way:

```ts
await db.card.select({ images: q => q.image.children })
```

ORM doesn't yet support selecting relation of relation like this, only a direct relation.

You can define a relation using `through` option, so that `card` has many `children` through `image`, and then it should work fine.

**Comment by IlyaSemenov** [comment]
Understood, thanks!

Is traversing this kind of relations something that you have plans for? If not, can it be somehow disabled at typings level?

Currently, it makes an impression that it will work:

```ts
const cards = await db.card
  .select("id", {
    image_url: (q) => q.image.children.where({ size: "small" }).get("url"),
  })
// cards is typed as: Array<{ id: string, image_url: string }>
// which is what a developer would actually expect.
```

**Comment by romeerez** [comment]
I didn't have plans for it until this issue, I think it would be nice to have.
But as it seems to be a big one, I'd like to postpone it to be done after one current big change I'm working on, perhaps for a few weeks.

**Comment by IlyaSemenov** [comment]
For the reference, in this particular case, the `through` relation worked perfectly, thanks for the tip:

```ts
class CardTable extends BaseTable {
  relations = {
    image: this.belongsTo(() => ImageTable, {
      required: true,
      columns: ["image_id"],
      references: ["id"],
    }),
    image_children: this.hasMany(() => ImageTable, {
      through: "image",
      source: "children",
    }),
  }
}

const cards = await db.card
  .select("id", {
    image_url: (q) => q.image_children.where({ size: "pre-middle" }).get("url"),
  })
```

**Comment by romeerez** [comment]
I think there is no point trying to support this syntax:

```ts
image_url: (q) => q.image.children
```
Because that means computing types of all relations of all relations just in case, TS won't survive this.

And if we try to compute relations of relations of relations, that would lead to endless recursion and TS will die even harder.

```ts
image_url: (q) => q.image.children.image.children.image.children,
```

It makes me wish there was an alternative language that could compute types lazily, on demand, without limits, and without heating my laptop.

**Comment by IlyaSemenov** [comment]
I believe there was a (now deleted) comment which elaborated that there were no point trying to support this syntax:

```ts
image_url: (q) => q.image.children.image.children.image.children
```

due to Typescript limitations.

I am not competent enough to argue, but, my original point was that if that is not supported, perhaps it would be possible to somehow **disable** that kind of traversal it at typings level? Currently, this kind of query aligns with developer expectations from this great ORM, it types properly (or at least seemingly so in simple cases), it compiles, it runs, it even builds a syntactically correct SQL query. Only there the problem starts: the SQL query is logically incorrect (and possibly the result parsers won't work either).

**Comment by romeerez** [comment]
I wrote a message and deleted it because after trying it seems to be possible, will have to only slightly override types of nested relations to always return multiple records, because when querying "has one" that's chained after "has many" it should return many.

**Comment by romeerez** [comment]
The feature is ready!

In the latest release, it's possible to chain relations however deep in select, and each chained relation can have (optionally) its own `where` conditions and any other methods such as `limit`, `offset`.

```ts
// should work now:
await db.card.select({ images: q => q.image.children })

await db.card.select({
  images: q =>
    q.image.where({ imageColumn: 'xxx' })
      .children.where({ childColumn: 'yyy' })
      .limit(10)
})
```

Also, it's now supported to have chaining on a top-level, without `select`.

```ts
// Loads children with conditions
// `where exists` image with conditions
// `where exists` card with conditions

await db.card.where({ ...conditions })
  .image.where({ ...conditions })
  .children.where({ ...conditions })
```
