### ISSUE TITLE
A few questions on Orchid features.

### ISSUE THREAD

**Issue by seivan** [romeerez/orchid-orm#176]
I'm looking for an ORM using TS that mimics the rich features Ecto (Elixir) has. 
It seems like Orchid follows most of the same patterns with both taking inspirations from Ruby tooling, but some stuff aren't clear from the documentation.

### Migrations
1. Does the migrator run a lock while running the migrations? [Doesn't seem like it](https://github.com/romeerez/orchid-orm/issues/178)
2. What does it exactly lock? 
3. Does the migrations manage their own lifetime and order? 

The reasons for those questions is, if you're running multiple nodes, and you got your migration in the boot, then you want to make sure only one node runs the migraiton and the others wait with a timeout. 

Like is there a `schema_migrations` table that is locked? 

Another reason is, is that you attach other migrations with your SQL migrations, if some code needs to run to change S3 or Redis, you can have that related with your SQL migrations. Say you're altering a table that refers to data in Redis or S3, you'd want to keep that with the SQL migrations, but you also want lock to ensure those changes only happen once. 

Regarding the lifetime, does the migration keeps track of what has run and what hasn't? 
The docs mention
> Migrations are written by hand instead of generating them like in some other ORMs.

If so, how would it? I am guessing you're adding your own unique identifiers (unix timestamps?) to keep track of what needs to run in what order and storing the meta data of migrations. 

###  Logging
1. Does the logging allow for explanations as a toggled on feature for e.g dev/staging ? 
2. Can logging be an monitored, for say storing on a remote server or using one of the logging services out there? 
3. Does logging support filtering keywords, e.g passwords and tokens? 

I noticed in the config that logging and error are both functions, so I guess the second question can be handled there. But I am also guessing there is no filtering happening before that? 

### Relationships
Can relationships be defined with default key names? 

```ts
  relations = {
    profile: this.hasOne(() => ProfileTable, {
      required: true,
      columns: ['id'],
      references: ['userId'],
    }),
  };
```

Can it automatically understand that that `user_id` and `id` are keys, can you omit defining them if the entire table follows those rules with either `camelCase` or  `snake-case`

### Postgres features.
1. Is [JSON-Path queries](https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-SQLJSON-PATH) supported? 
2. The [documentation](https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-SQLJSON-PATH) mentions selecting schema at runtime, just to be clear, this is using postgres schema features, where you can have the same table on multiple schemas and define the prefix in the query, will that schema trickle down to relationships/joins and etc?

**Comment by romeerez** [comment]
Orchid ORM is relatively young and of course, it can miss important things, I hope you aren't disappointed by it so far so I can implement it in the near future and you can use it. But, after answering most of the questions "not yet" you'll probably go for the alternative. Anyway, thank you for brining up all these points!

### Migrations

> Does the migrator run a lock while running the migrations? https://github.com/romeerez/orchid-orm/issues/178
> What does it exactly lock?

It doesn't lock, going to implement it.

> Does the migrations manage their own lifetime and order?

Command `npm run db new *migration_name*` generates a new migration file where the name starts with timestamps, and migrations are ordered alphabetically.

After migration runs successfully, its timestamp is stored in the "schemaMigrations" table.

Migrations whose timestamp is stored in that table are considered as migrated, and won't be migrated a second time. When rolling back migration, it deletes the timestamp from the table.

### Logging

> Does the logging allow for explanations as a toggled on feature for e.g dev/staging ?

I may not completely understand the question, but logging is configurable. It's on by default and can be turned off with a `log: false` option. In the config, you can provide your own logger object with `log` and `error` functions to customize how it logs. (see [log option](https://orchid-orm.netlify.app/guide/orm-and-query-builder.html#log-option)).

> Does logging support filtering keywords, e.g passwords and tokens?
> the second question can be handled there. But I am also guessing there is no filtering happening before that?

You're right, no filtering. I assume it's up to the user to provide their own log functions and do whatever. But, if you're logging queries and want to censor tokens/passwords, how would your custom log function understand that one string is a password and should be censored, and the other is not? So looks like it there should be a feature in this library to censor specific columns before sending them to the log.

### Relationships

> Can it automatically understand that user_id and id are keys, can you omit defining them if the entire table follows those rules with either camelCase or snake-case

It would be a nice addition, to be done.

### Postgres features.

> Is [JSON-Path queries](https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-SQLJSON-PATH) supported?

Yes, there is a `jsonPathQuery` and other JSON functions. I saved this [cheatsheet](https://storage.pardot.com/890043/1680097111JPZJc433/postgresql_jsonb_cheatsheet_en.pdf) as a source of JSON features to add support for later. Currently, Orchid ORM supports the same set of JSON functions as [Knex](https://knexjs.org/).

[jsonPathQuery](https://orchid-orm.netlify.app/guide/advanced-queries.html#jsonpathquery)

> The [documentation](https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-SQLJSON-PATH) mentions selecting schema at runtime, just to be clear, this is using postgres schema features, where you can have the same table on multiple schemas and define the prefix in the query, will that schema trickle down to relationships/joins and etc?

The link points to the same JSON function as the prev point.

Db schema can be set once for all tables ([link](https://orchid-orm.netlify.app/guide/orm-and-query-builder.html#databaseurl-option)), it can be set separately for a specific table by adding `schema = 'my_schema';` into table class (looks like it's not documented), and also there is a [withSchema](https://orchid-orm.netlify.app/guide/advanced-queries.html#withschema) query builder method.

Non-relational queries where the table is in a custom schema are tested and should work. But relationships aren't tested for such tables. So if you're looking for an ORM for this use case - I wouldn't recommend Orchid for it yet.

**Comment by seivan** [comment]
> Orchid ORM is relatively young and of course, it can miss important things, I hope you aren't disappointed by it so far so I can implement it in the near future and you can use it. But, after me answering most of the questions "not yet" you'll probably go for the alternative. Anyway, thank you for brining up all these points!

Yeah, so far the design seems perfectly apt for what I would like, and closest thing to Ecto design wise. But it's lacking a little bit of the rich feature set. Others have the featureset, but they lack some of the design decisions Orchid has (which I like). 


> ### Migrations
> > Does the migrator run a lock while running the migrations? #178
> > What does it exactly lock?
> 
> It doesn't lock, going to implement it.

Yeah that's a bit of an issue, especially if you run multiple nodes and boot checks pending migrations. 
I suggest looking at how Ecto does it. 



> ### Logging

> I may not completely understand the question, but logging is configurable. It's on by default and can be turned off with a `log: false` option. In the config, you can provide your own logger object with `log` and `error` functions to customize how it logs. (see [log option](https://orchid-orm.netlify.app/guide/orm-and-query-builder.html#log-option)).

Thanks. 
 
> > Does logging support filtering keywords, e.g passwords and tokens?
> > the second question can be handled there. But I am also guessing there is no filtering happening before that?
> 
> You're right, no filtering. I assume it's up to the user to provide their own log functions and do whatever. But, if you're logging queries and want to censor tokens/passwords, how would your custom log function understand that one string is a password and should be censored, and the other is not? So looks like it there should be a feature in this library to censor specific columns before sending them to the log.

Well the best way to catch these, is allowing defining fields as `redacted` that way they can always be filtered out of logs, changelogs, validations, etc. 

> ### Relationships
> > Can it automatically understand that user_id and id are keys, can you omit defining them if the entire table follows those rules with either camelCase or snake-case
> 
> It would be a nice addition, to be done.

Yeah, this would also enforce some standardisation with convenience over configurations.

> ### Postgres features.

> Yes, there is a `jsonPathQuery` and other JSON functions. I saved this [cheatsheet](https://storage.pardot.com/890043/1680097111JPZJc433/postgresql_jsonb_cheatsheet_en.pdf) as a source of JSON features to add support for later. Currently, Orchid ORM supports the same set of JSON functions as [Knex](https://knexjs.org/).
> 
> [jsonPathQuery](https://orchid-orm.netlify.app/guide/advanced-queries.html#jsonpathquery)
Thanks! 



> Db schema can be set once for all tables ([link](https://orchid-orm.netlify.app/guide/orm-and-query-builder.html#databaseurl-option)), it can be set separately for a specific table by adding `schema = 'my_schema';` into table class (looks like it's not documented), and also there is a [withSchema](https://orchid-orm.netlify.app/guide/advanced-queries.html#withschema) query builder method.

Sorry about the link, but you seem to have understood, since that's what I was looking for. 

> Non-relational queries where the table is in a custom schema are tested and should work. But relationships aren't tested for such tables. So if you're looking for an ORM for this use case - I wouldn't recommend Orchid for it yet.
Oh that's a shame. 
That's something that's kinda needed as well, same as migration locks. 
I was just wondering if it works across relationships/references/joins, but I guess not. 

Again, thanks for answering. I'm closing this.
