### ISSUE TITLE
`migrationsTable` should be locked during migration runs. 

### ISSUE THREAD

**Issue by seivan** [romeerez/orchid-orm#178]
Looking through the source, I don't see `migrationsTable` being locked while migration(s) are running. I could be mistaken, but this is a mistake. It should be locked.

**Comment by romeerez** [comment]
No mistakes, it doesn't have a lock table and doesn't lock anything.

I noticed that Knex migrations and Kysely migrations create a second table called "migration_locks", but didn't know what was the point so it's not implemented here.

But as you explained, I see the value and will add it in the same or a similar way to how it's done in Knex and Kysely.

**Comment by seivan** [comment]
Why not just lock the `schema_migrations` table instead? Not sure **why** Knex and Kysely would do it in a separate table. 
Afaik Ecto just locks the migration_table, and that's battle-tested, that being said, I suspect it has something to do with different providers, e.g lacking transactional DDL ops.

**Comment by romeerez** [comment]
So by locks, you mean to lock the "schemaMigrations" row with a transaction for the time of executing migration, I see, that makes sense! Perpahs that's why there was no separate table for locks in RoR.

Then it's even easier to implement (I hope so) and will be more reliable because at the work project where I have Kysely sometimes I have to delete a lock record manually after something went wrong.

**Comment by romeerez** [comment]
I looked at Ecto docs:

https://hexdocs.pm/ecto_sql/Ecto.Migration.html

> Ecto also locks the schema_migrations table when running migrations, guaranteeing two different servers cannot run the same migration at the same time.

https://hexdocs.pm/ecto_sql/Ecto.Migration.html#module-migrator-configuration

> :migration_lock - By default, Ecto will lock the migration source to throttle multiple nodes to run migrations one at a time.

But, how?

> Or use a different locking strategy. For example, Postgres can use advisory locks but be aware that your database configuration might not make this a good fit.

`Postgres can` sounds like this is not a default, and they say in might not make this a good fit, but don't explain.

Asked ChatGPT, and it says:

1. Database Advisory Locks: Ecto uses PostgreSQL's advisory locks. Advisory locks are a type of lock that is not tied to a specific table or row but can be used for application-level locking. Ecto employs these locks to ensure that only one migration process can acquire the lock at a time.

2. Migrations Lock Table: Ecto creates a dedicated table in your database to manage the migrations lock. This table typically has a name like "ecto_migrations_lock."

3. Locking Strategy: When you run a migration, Ecto first tries to acquire a lock on the "ecto_migrations_lock" table. If another migration process already holds the lock, the new migration process will wait until the lock is released.

4. Release Lock: Once the migration is complete, Ecto releases the lock, allowing other migration processes to proceed.

I think I get the general idea.

**Comment by seivan** [comment]
> I looked at Ecto docs:
> 
> https://hexdocs.pm/ecto_sql/Ecto.Migration.html
> 
> > Ecto also locks the schema_migrations table when running migrations, guaranteeing two different servers cannot run the same migration at the same time.
> 
> https://hexdocs.pm/ecto_sql/Ecto.Migration.html#module-migrator-configuration
> 
> > :migration_lock - By default, Ecto will lock the migration source to throttle multiple nodes to run migrations one at a time.
> 
This is correct. 

> But, how?
> 
> > Or use a different locking strategy. For example, Postgres can use advisory locks but be aware that your database configuration might not make this a good fit.
> 
> `Postgres can` sounds like this is not a default, and they say in might not make this a good fit, but don't explain.

It's not a good fit based on a specific configurations, an example of such configuration would be running multiple nodes as the lock is app wide without any distribution. Elixir (OTP) however comes with distributed systems support out of the box, so it's not a problem there, it's usually a problem if your DB is shared with multiple services that doesn't support it, e.g Node, Ruby, etc. 
 
> Asked ChatGPT, and it says:
> 
> 1. Database Advisory Locks: Ecto uses PostgreSQL's advisory locks. Advisory locks are a type of lock that is not tied to a specific table or row but can be used for application-level locking. Ecto employs these locks to ensure that only one migration process can acquire the lock at a time.

It's **one** of the locks, in case the user disables the lock on the migration table, and that's only valid if your system is running in distributed cluster mode, which again is possible with Elixir (OTP), don't get hung up on that, especially since there's really builtin with Node/Deno. 



> 2. Migrations Lock Table: Ecto creates a dedicated table in your database to manage the migrations lock. This table typically has a name like "ecto_migrations_lock."
> 3. Locking Strategy: When you run a migration, Ecto first tries to acquire a lock on the "ecto_migrations_lock" table. If another migration process already holds the lock, the new migration process will wait until the lock is released.
> 4. Release Lock: Once the migration is complete, Ecto releases the lock, allowing other migration processes to proceed.

These sounds more like suggestions than current implementation. I can't see any references to `ecto_migrations_lock`. 

The implementation for the [Postgres adapter looks like this](https://github.com/elixir-ecto/ecto_sql/blob/v3.10.2/lib/ecto/adapters/postgres.ex#L280C8-L280C30)

And it is used [here](https://github.com/elixir-ecto/ecto_sql/blob/v3.10.2/lib/ecto/migrator.ex#L573) the implementation is obviously based on different providers, but still, if possible you should lock the migration table, at the very least for Postgres, I can't speak for others.

**Comment by romeerez** [comment]
@seivan why closing? I was going to work on it later.
