### ISSUE TITLE
Casting columns to different type

### ISSUE THREAD

**Issue by lithdew** [romeerez/orchid-orm#18]
Unsure if this is possible with pqb as-is, though is it possible to cast i.e. `Table.count()` strictly to an integer/numeric type?

**Comment by romeerez** [comment]
I tested to ensure what it does output:

```ts
const count = await db.article.count();
console.log(typeof count);
```

It outputs a `number`, as intended. Could you clarify if there anything wrong and what do you want to cast?

**Comment by lithdew** [comment]
> I tested to ensure what it does output:
> 
> ```ts
> const count = await db.article.count();
> console.log(typeof count);
> ```
> 
> It outputs a `number`, as intended. Could you clarify if there anything wrong and what do you want to cast?

I’m currently running into some issues with directly executing queries such that I am using toSql() and directly passing the query to a raw ‘pg’ instance. I’ll post a separate issue for this in the next day.

**Comment by romeerez** [comment]
Oh, that's some unusual use case.

So you'd like to specify something like:

```ts
const sql = db.table.count({ cast: 'integer' }).toSQL()
// use SQL later
```

To have

```ts
SELECT count(*)::integer FROM table
```

I was going to add something similar to columns, so timestamps could be cast to numbers right inside the query.

But doing this for methods like `count()` I'm not sure if it's valuable. Isn't it simpler to use `parseInt` instead?

**Comment by romeerez** [comment]
By default, the ORM is returning all counts as numbers, both when called on a table or when called in a subquery. In subquery it had a bug that is already fixed, so now it returns numbers from subqueries as well.

For more rare cases, such as casting value inside SQL, there is a `get` method to load only a single value, and a `raw` method to inject some custom SQL, for example:

```ts
const query = db.accounts.select({
  count: (q) => q.account_posts.get(db.accounts.raw(
    (t) => t.integer(),
    'count(*)::integer'
  ))
})

const sql = query.toSql().text
```

And this sql could be passed into a raw `pg` instance for number count type.

**Comment by cressie176** [comment]
I just added a note about returning counts as numbers on [issue 20](https://github.com/romeerez/orchid-orm/issues/20#issuecomment-1426952973). Relevant here too.
