### ISSUE TITLE
Collect rakeDb lazy run logs

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#180]
If I have a lazy rakeDb, how do I collect logs from each run?

```ts
const { change, run } = rakeDb.lazy()

await run(['up']) // I want logs of this call separately
await run(['down']) // from logs of this
```

The only option I see now is a global logger singleton passed to `lazy({}, { logger })`, a wrapper around `run` which resets its, and a semaphore preventing parallel runs, which is very cumbersome.

What I suggest is to allow `run` to accept partial `RakeDbConfig` as a second argument, which will be merged with the defaults that have been provided to the original `rakeDb.lazy` call.

**Comment by romeerez** [comment]
Done, now it can accept a partial config via a second optional arg: [rakeDb.lazy](https://orchid-orm.netlify.app/guide/migration-setup-and-overview.html#rakedb-lazy)
