### ISSUE TITLE
Ensure consistency of order of migrations

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#181]
As a developer working in a team with feature branches, I want to ensure consistency of the order in which migrations are applied.

### User story

1. Alice and Bob both forked master, which had migration 1000.
2. Alice created migration 1001.
3. Bob started later, created migration 1002 involving the same table, but finished quicker.
4. Alice merged Bob's changes, ran his migrations, and also finished her job.
5. Bob merged Alice's changes and ran her migrations.
6. Now Alice and Bob (and the CI/CD targets) all have different database schemas.

This is especially inconvenient when the workflow involves maintaining data-less `schema.sql` as the source of truth (as I sometimes do), as it becomes inconsistent in different working copies.

I believe in certain cases (especially with data migrations) silently mixing the order of migrations could even lead to data loss, although I can't come up with a good example at the moment.

### Traditional approach

Usually, this is either not handled (e.g. Knex or Orchid don't), or handled by defining dependency/-ies of each migration (as [Django does](https://docs.djangoproject.com/en/4.2/topics/migrations/#migration-files)).

### Suggestion

What I suggest is, optionally, have a way to tell rakeDb to refuse to execute older migrations if there are newer migrations applied. In that case, on Step 4 above, rake will report error, suggesting Alice to undo her migrations and rename them as coming after Bob's.

There could be also a helper script that will rename all such blocking migrations to now, now+1, now+2, etc. If Alice is sure that her work is independent of what Bob has done, she could choose to "fake" the undo/rename/redo with just rename/update migrations metadata.

---

UPD: The example above is incorrect, in the sense that there is no way to detect the problem on Step 4. The problem will only appear on Step 5 when it's probably too late.

**Comment by IlyaSemenov** [comment]
The other idea I have is to allow to define migration's dependencies, and use them to infer the order of execution.

Given the list of migrations:
- 1
- 2 (depends on 1)
- 3 (depends on 1)
⇨ The runner should report the error: _"Ambiguous order of migrations: 2, 3 depend on 1. Please define how each of them depend on each other."_

Given the list of migrations:
- 1
- 2 (depends on 1, 3)
- 3 (depends on 1)
⇨ The order should be: 1, 3, 2.

No dependencies will mean "depends on the lexicographically previous", same as now.

This could be implemented as simply as:

```ts
// optional export in a migration module
export dependencies = ["20230804101735"]
```

Then the `db new` command could automatically insert that export (this could be an opt-in option for me:).

**Comment by romeerez** [comment]
I meant "0001_create_user". I think that to enforce order consistency, using "0001" prefixes would be enough. Adding dependencies similar to Django is an option, but less preferable, as I'm not familiar with it and it seems to be more complex.

**User story**
- Alice and Bob both forked master, which had migration 1000.
- Alice created migration 1001.
- Bob also created migration 1001 involving the same table, finished quicker.
- Alice merged Bob's changes, `db migrate` fails because of the second migration with the same id
- Alice ran a new command `db rebase`, which does:
  - detects conflicting migrations, in this case only 1001 but could be several
  - rolls back those of them that were already migrated (Alice version)
  - migrates the rest of the conflicting (Bob version)
  - appends Alice version with new id and migrates it

Voila, the problem was detected and solved before committing!

If Alice wrote a migration 1001 but didn't migrate it, so after merging Bob's code she has both versions not migrated, the `db rebase` could check in git which one is committed, and move the other to the end. If can't detect in git, it can interactively ask which one should be moved.

**Comment by IlyaSemenov** [comment]
Right, that make sense.

I have two smaller concerns:

1) What if Alice forgets to do `db migrate` and simply pushes her changes to the main branch? Perhaps we could have some kind of `db check` command ensuring that all migrations have been applied and there are no conflicts, and a recipe for adding a pre-commit hook? (Will that work in Github/Gitlab PR? I mean, if both Alice and Bob prepare two PRs, both with 1001, and then a team leader merges both of them?)

2) If this approach is to be adopted, what happens to the existing migrations in existing projects? Perhaps we can auto switch, such as when a project already has timestamp-based migrations we continue to generate them in the same manner, but use sequential IDs for new installs? Ideally, I would somehow convert an existing project to the new scheme, but how can we handle non-local (e.g. production) database which already saved the names of the applied migrations? 
 Another approach I was considering is generating `90000000000001`, `90000000000002` etc. for existing setups which will be both backwards compatible (coming lexicographically after `20230811075433`) and benefit from the new approach. But this probably should be opt-in in order not to scare off users. 😃

**Comment by romeerez** [comment]
> What if Alice forgets to do db migrate?

Then it will fail in CI and data corruption is still prevented.

> Perhaps we could have `db check` command ensuring that all migrations have been applied and there are no conflicts

I'd simply use `db migrate` for it, if everything is already migrated it won't do much work, and if there is a problem it will detect it.

> If this approach is to be adopted, what happens to the existing migrations in existing projects?

Mixing both kinds in a single project isn't a good idea, because timestamps will be always at the bottom. If `rake-db` detects a timestamp migration, it throws with a message that if you want them, add an option "timestamp: true" and continue working with timestamp migrations. Or, run some command like `db timestamps-to-numbers`, it will rename timestamps to numbers in the existing files, and also generate a new migration to update migration info in the db, so that it will also be applied in production.

> 90000000000001

Aesthetical damage

**Comment by cressie176** [comment]
I had a similar challenge with [marv](https://github.com/guidesmiths/marv#migration-files), which supports the 0001-blah-blah-blah migration file syntax. I resolved by reporting duplicate and out of sequence migrations, i.e.

a) duplicate numerical prefix

   - Alice commits 0003-foo.sql to feature branch X
   - Bob commits 0003-bar.sql to feature branch Y
   - Alice merges to main/master
   - Bob updates his local workspace with Alices' changes
   - Marv reports the duplicate migration prefix
   
b) out of sequence migrations

   - Alice commits 0003-foo.sql to feature branch X
   - Bob commits 0004-bar.sql to feature branch Y
   - Alice merges to main/master
   - Migrations run successfully
   - Bob updates his local workspace with Alices' changes
   - Marv reports that 0004-bar.sql was run before 0003-foo.sql migration

**Comment by romeerez** [comment]
Thanks for the input, it's cool that you have built a migration tool yourself and can share some tough corners!

I like the naming with a dot from marv: let it be 0001.foo.ts, 0002.bar.ts.

Yes, the idea was like that: having iterative prefixes will allow to catch conflicts, and the tool will exit with an error when there is a duplicate or out-of-sequence number. Plus there will be a "rebase" command to automatically rollback already migrated conflicting migrations, re-numerate them to move them to the bottom, and migrate all.

When I can return to start implementing it - in a couple of months I guess.

**Comment by romeerez** [comment]
This is mostly ready!

Now serial prefixes "0001_", "0002_" are supported and are the default. If you don't wish to switch, set `migrationId: 'timestamp'` in the rake-db config, and if you're ready to switch, here is a new command `change-ids`:

```sh
pnpm db change-ids serial
```

It will rename all existing timestamp-prefixed files to "000x" prefixed, will update track records in the db, and will generate a `.rename-to-serial.json` file with name mapping. When deploying, `db migrate` on the remote server will notice that prefixes have changed and will update existing migration tracking records using that file.

[change-ids](https://orchid-orm.netlify.app/guide/migration-commands.html#change-ids) docs.

A new command `rebase` ([docs](https://orchid-orm.netlify.app/guide/migration-commands.html#rebase)) - it will automatically reorder files in case of conflicts as described in this issue.

What's up to do is to support `rebase` for timestamp versions, as it seems to be also possible. And `db check` command could be added.

**Comment by romeerez** [comment]
The way how `rebase` works for serial-prefixed migrations doesn't make much sense for timestamp migrations, so it's only for serials.

Now, if older migration is not applied, but newer migrations are applied, it will throw an error. So it forces order consistency.

I added a new command for timestamp migrations: `up force` or `migrate force`. It's automatically solving the case above, [here are the docs](https://orchid-orm.netlify.app/guide/migration-commands.html#up-or-migrate-force).

Decided to not add `db check`, as it's not very useful to just fail in case you've forgotten to migrate db. `db up` or `db migrate` will both check and run the migrations if needed.
