### ISSUE TITLE
Malformed SQL when JSON field default is an array

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#183]
Following #175, there is a similar bug when adding a JSON field with `.default([])`. Instead of creating a default of `[]` (empty JSON array), rake sets the field default to `{}` (empty JSON object).

```ts
change(async (db) => {
  await db.createTable("role", (t) => ({
    id: t.uuid().primaryKey(),
    name: t.varchar(),
    acl: t.json().default([]),
  }))
})
```

gives:

```sql
CREATE TABLE "role" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" varchar NOT NULL,
  "acl" jsonb NOT NULL DEFAULT '{}'
)
```

Expected: `"acl" jsonb NOT NULL DEFAULT '[]'`

Similarly, defaults like `.default(["foo"])` will simply generate invalid SQL: `"acl" jsonb NOT NULL DEFAULT '{"foo"}'` which crashes with: "Error: invalid input syntax for type json".

* rake-db@2.10.45

**Comment by IlyaSemenov** [comment]
This is also happening with runtime default:

```ts
modules: t.json((t) => t.array(t.string())).default(() => ["foo"])
```

```sql
INSERT INTO "settings"("modules") VALUES ($1) RETURNING * ['{"foo"}']
-- Error: invalid input syntax for type json
```

**Comment by romeerez** [comment]
Thank you for reporting, I fixed and published it.

Now the default value will be encoded with the encoder from the column, with JSON.stringify in this case, in both migration and when returning a value from a callback.
