### ISSUE TITLE
`create` method should omit computed columns

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#188]
This code throws a create error:
```
computed = this.setComputed({
  test: (q) => {
    return q.sql`test`.type((t) => t.string());
  },
});
```

I have to write:
```
computed = this.setComputed({
  test: (q) => {
    return q.sql`test`.type((t) => t.string().nullable());
  },
});
```

But I think computed columns should never be set in `create` or `update` methods.

**Comment by romeerez** [comment]
I published fixes (orchid-core, orchid-orm, pqb), now `nullable` isn't necessary, `create` and `update` methods forbid computed values on TS level.
