### ISSUE TITLE
`makeHelper().select()` shows type error

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#191]
I had this `queryMethods`
```
const selectForDefault = db.activity.makeHelper((q) => {
  return q.select(
    'id',
  );
});
```

```
export const repoActivity = createRepo(db.activity, {
  queryMethods: {
    selectForShow: (q) => {
      return selectForDefault(q).select({
        category: (q) => q.category.select('id', 'name', 'intro'),
        hasHost: (q) => q.members.where({ host: true }).exists(),
      });
    },
  },
)
```

After upgrade to the latest version, it shows error when use `await repoActivity.find(id).selectForEdit();`
The error message is : `Type instantiation is excessively deep and possibly infinite.`

**Comment by romeerez** [comment]
Sad but, it's a cost of adding new features, types get more and more complicated and TS gives up sooner.

If you could provide a small reproduction repo, that would help, I'd try to optimize types to fix it for this case.

**Comment by bingtsingw** [comment]
I find some of some `makeHelper` will trigger this error, some are not.
I'll delve into it deeper

**Comment by bingtsingw** [comment]
Hi, I have made a reproduction repo, but the result is very strange: https://github.com/bingtsingw/orchid-reproduce

Only `error3()` function throws a type error, others are type safe, including `safe4()`

**Comment by romeerez** [comment]
Fixed!

I optimized types of `select` and now it's a bit more lightweight.
Updating ORM and pqb versions to the latest in your repo fixes the error.

Before any argument of `select` could be an array, and now only the last arg can be an array, which allows for TS optimization.

Sorry that it takes a long time, but in the end it's getting improved anyway.
