### ISSUE TITLE
Bun Support 

### ISSUE THREAD

**Issue by msfunty** [romeerez/orchid-orm#193]
Installing with Bun works as expected.
But rake-db has some issues with it.
In [quickstart](https://orchid-orm.netlify.app/guide/quickstart.html#database-setup) when running "bun run db create" error is thrown as getCallerFilePath() is empty.

69 |     delete result.logger;
70 |   }
71 |   if (!result.basePath || !result.dbScript) {
72 |     const filePath = getCallerFilePath();
73 |     if (!filePath) {
74 |       throw new Error(
                ^
error: Failed to determine path to db script. Please set basePath option of rakeDb
      at processRakeDbConfig (/test/orchid/node_modules/rake-db/dist/index.mjs:74:12)
      at rakeDb (/test/orchid/node_modules/rake-db/dist/index.mjs:3772:17)
      at /test/orchid/src/db/dbScript.ts:6:22

**Comment by IlyaSemenov** [comment]
See #150.

This works:

```ts
export const change = rakeDb(
  { databaseURL: db_url },
  {
    baseTable: BaseTable,
    basePath: __dirname,
    dbScript: __filename,
    migrationsPath: "./migrations",
  },
)

// Needed for bun!
await change.promise
```

**Comment by romeerez** [comment]
Thanks @IlyaSemenov! Are you using it on Bun, is it ok?

I'll look if `await change.promise` can be done automatically for Bun, and will some docs for Bun.

**Comment by bingtsingw** [comment]
I am also interested in supporting bun.

**Comment by IlyaSemenov** [comment]
@romeerez No, I am not using orchid/rake with Bun anymore. I tried Bun as an experiment and I was disappointed with how buggy it was.

I opened a few issues for the problem I had faced (https://github.com/oven-sh/bun/issues/4035, https://github.com/oven-sh/bun/issues/4039) and they were never addressed even though the second one is relatively important in my thinking (bun loses the entire `process.env` under some circumstances).

Besides, it's not playing well with monorepos (compared to pnpm), and it was even corrupting its own binary lockfile in my monorepo every now and then (I didn't have enough patience to come up with a reproduction workflow and report it).

**Comment by msfunty** [comment]
I just updated to the most recent versions of Orchid and Bun (1.0.3).
Without any code changes on my side "bun db create" and "bun db migrate" do run now.
Assuming some bugs got fixed in Bun meanwhile.

**Comment by romeerez** [comment]
I'm confirming that setting paths manually (`basePath: __dirname`) isn't required since bun v1.0.3, and it works for me without the `await change.promise`. There is still one bun-related issue that I'm trying to workaround on the orchid-orm side, but nevertheless, impressive how quickly they fixed those compatibility problems.
