### ISSUE TITLE
[rake-db] TSError when trying to seed db

### ISSUE THREAD

**Issue by matthewmorek** [romeerez/orchid-orm#196]
After writing my migrations and ensuring I can stand up and tear down the database correctly, I decided to write a bunch of seed scripts to populate the database, but even a simple `create()` query is failing.

```
TSError: ⨯ Unable to compile TypeScript:
src/db/seed.ts:213:43 - error TS2345: Argument of type '{ name: string; title: string; }' is not assignable to parameter of type 'CreateRelationsData<Db<"facility", { id: ColumnWithDefault<UUIDColumn & { data: { isPrimaryKey: true; }; } & { data: { default: RawSQLBase<ColumnTypeBase<unknown, BaseOperators, unknown, unknown, unknown, ColumnDataBase>, {}>; }; }, RawSQLBase<...>>; ... 4 more ...; updatedAt: ColumnWithDefault<...>; }, { ...; }, { ...'.
  Type '{ name: string; title: string; }' is missing the following properties from type 'Omit<SetOptional<{ id: CreateColumn<Db<"facility", { id: ColumnWithDefault<UUIDColumn & { data: { isPrimaryKey: true; }; } & { data: { default: RawSQLBase<ColumnTypeBase<unknown, BaseOperators, unknown, unknown, unknown, ColumnDataBase>, {}>; }; }, RawSQLBase<...>>; ... 4 more ...; updatedAt: ColumnWithDefault<...>;...': id, createdAt

213   const { id } = await db.facility.create({
                                              ~
214     name: "test",
    ~~~~~~~~~~~~~~~~~
215     title: "test",
    ~~~~~~~~~~~~~~~~~~
216   });
    ~~~
```

#### Migration
```ts
import { change } from "../dbScript";

change(async (db) => {
  await db.createTable("facility", (t) => ({
    id: t
      .uuid()
      .primaryKey()
      .default(t.sql`uuid_generate_v4()`),
    name: t.varchar().unique(),
    title: t.varchar(),
    description: t.varchar().nullable().default(null),
    createdAt: t.timestamp().default(t.sql`now()`),
    updatedAt: t.timestamp().nullable().default(null),
  }));
});
```

#### Table model
```ts
import { BaseTable } from "./BaseTable";

export class FacilityTable extends BaseTable {
  readonly table = "facility";
  columns = this.setColumns((t) => ({
    id: t
      .uuid()
      .primaryKey()
      .default(t.sql`uuid_generate_v4()`),
    name: t.varchar().unique(),
    title: t.varchar(),
    description: t.varchar().nullable().default(null),
    createdAt: t.timestamp().default(t.sql`now()`),
    updatedAt: t.timestamp().nullable().default(null),
  }));
}
```

#### Seed script
```ts
import { db } from "./db";
export const seed = async () => {
  await db.facility.create({
    name: "test",
    title: "test",
  });

  await db.$close();
};
```

Any ideas why this may be happening? I have set up my `dbScript.ts` exactly as per documentation, but here it is, just in case:
```ts
import { rakeDb } from "rake-db";
import { appCodeUpdater } from "orchid-orm/codegen";
import { config } from "./config";
import { BaseTable } from "./tables/BaseTable";

export const change = rakeDb(config.database, {
  snakeCase: true,
  baseTable: BaseTable,
  migrationsPath: "./migrations",
  appCodeUpdater: appCodeUpdater({
    tablePath: (tableName) => `./tables/${tableName}.ts`,
    ormPath: "./db.ts",
  }),
  useCodeUpdater: false, // set to false to disable code updater
  commands: {
    async seed() {
      const { seed } = await import("./seed");
      await seed();
    },
  },
  import: (path) => import(path),
});
```

As mentioned before, migrations and rollback run perfectly, I am able to to select my data without issues, just can't create anything right now due to these type errors.

**Comment by romeerez** [comment]
I'll debug to see what's wrong, later today. The error says it's missing `id` and `createdAt`, maybe ORM type doesn't take SQL defaults into account, though it should do it.

`uuid` column type has `gen_random_uuid()` default by default.
For timestamps, you can use `..timestamps()` instead of `createdAt` + `updatedAt` ([docs](https://orchid-orm.netlify.app/guide/common-column-methods.html#timestamps)), it will set defaults to `now()`, and `updatedAt` will be updated automatically when updating.

**Comment by matthewmorek** [comment]
Thanks, let me know what you did find in your debug. I'll try to use the factory timestamps.

I wish there was some examples of seeders in your other repo, because I couldn't find anything except for single snippet in the docs.

**Comment by romeerez** [comment]
I copied the code as is but could not reproduce the error.

The error says: "Argument ... is not assignable to parameter of type 'CreateRelationsData<...>", `CreateRelationsData` means that you have defined relations and the error is somehow related to that. Could you publish a reproduction repo, or just copy `BaseTable`, the table class, `createDb`, and the `seed` function to a separate file and share its contents to reproduce the error?

> I noticed that you declare timestamps in the BaseTable by spreading ...t.timestamps, not by invoking a function ...t.timestamps().

In the `BaseTable` you can override column types (optionally) such as to configure timestamps to be parsed into `Date` objects:

```ts
import { createBaseTable } from 'orchid-orm';

export const BaseTable = createBaseTable({
  columnTypes: (t) => ({
    ...t,
    timestamp: () => t.timestamp().asDate(),
  }),
});
```

Column types are defined in the column class, in your code examples all is correct, except that `updatedAt` and `createdAt` better be constructed with `...t.timestamps()`. If you destructure it without calling it won't have effect:

```ts
const fn = () => {}

// we can destructure a function, without type errors, but this won't have any effect:
const obj = { ...fn } // obj is an empty object
```

> I wish there was some examples of seeders in your examples repo, because I couldn't find anything except for single snippet in the docs.

You can do everything described in the [create-update-delete](https://orchid-orm.netlify.app/guide/create-update-delete.html) or anything at all in the seeds

**Comment by matthewmorek** [comment]
I'll get a sample repo ready for you shortly, so you could have a closer look.

**Comment by matthewmorek** [comment]
@romeerez I have a playground repo ready for you to test: https://github.com/matthewmorek/orchidorm-db-playground

**Comment by romeerez** [comment]
Published a fix, it should be fine with the latest versions.

You're using `uuid-ossp` extension to set `uuid_generate_v4()` default for uuids, and it's okay but FYI the ORM is setting `gen_random_uuid()` default to primary key uuids by default, and this function is standard and doesn't require extensions, works for Postgres >= 13.

**Comment by matthewmorek** [comment]
I'm using the UUID extension because it's part of Supabase stack, and I'd like to avoid issues in the future with default values, as my plan is to build multiple clients, some of which won't be able to rely on OrchidORM (Swift, Flutter, etc).

Thanks again for a rapid support and a fix! 🙌
