### ISSUE TITLE
Quickstart guide violates foreign key constraint when running seed

### ISSUE THREAD

**Issue by alexandre-dos-reis** [romeerez/orchid-orm#198]
Hello and thanks for this project !

I followed the QuickStart guide and got this error, I use `bun`.
I ran all the commands described in the guide, the db and the models are all set up.

```sh
$ bun src/db/dbScript.ts seed
2176 | };
2177 | const makeSQL = (table, options) => {
2178 |   const query = table.q;
2179 |   const sql = [];
2180 |   const values = (options == null ? void 0 : options.values) || [];
2181 |   const ctx = {
                  ^
error: insert or update on table "comment" violates foreign key constraint "comment_postId_fkey"
 code: "23503"

      at /Users/alex/orchid-orm/node_modules/pqb/dist/index.mjs:2181:14
error: script "db" exited with code 1 (SIGHUP)
```

Am I doing something wrong ?

Thank you for your help.

**Comment by romeerez** [comment]
Confirming, I reproduced the bug, and there are other few things to update for the quickstart

**Comment by romeerez** [comment]
It's a bug specific to Bun, apparently [AsyncLocalStorage](https://nodejs.org/api/async_context.html) has a bug in a specific edge case, so I filed [an issue](https://github.com/oven-sh/bun/issues/6393).

The bug means that transactions currently don't work with Bun.

**Comment by romeerez** [comment]
I published `pqb` with a workaround, now it works fine.

The installation guide and scripts are yet to be improved, but Bun works.
