### ISSUE TITLE
find().increment() throws error

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#199]
`await db.table.find(id).increment('num');` throws an error, but the query did execute successfully.
`await db.table.where({id : id }).increment('num');` do not throw an error.

And they generate exact the same sql

**Comment by romeerez** [comment]
What is the error?

**Comment by bingtsingw** [comment]
It throws not found error, but the increment did execute

**Comment by romeerez** [comment]
That's how it's intended to be, `find` is throwing when no record is found, there is `findOptional` that doesn't throw on not found. `where` doesn't throw on not found.

SQL may be the same, but we have different methods to handle the result differently.

So I don't see what could be changed or improved here, it's alright, do you have suggestions?

**Comment by bingtsingw** [comment]
Well, I mean, there is a record to update, and the `increment` action executed succeed(for both, even `find` throws an error, the `increment` action succeed).
I dump the sql log, they both generate the same sql, but I don't know why the `find` statement throws an error.

**Comment by romeerez** [comment]
Ah, so that's a bug, I'll try to find time for it in the near days.
That's weird, that functionality is well covered with tests, but apparently still not enough.

**Comment by romeerez** [comment]
I published fixes for this, now it should work fine and be somewhat predictable.

```ts
// throws only when not found, returns count
db.table.find(1).increment('column')
db.table.findBy({ id: 1 }).increment('column')

// don't throw when not found, return count
db.table.findOptional(1).increment('column')
db.table.findByOptional({ id: 1 }).increment('column')
db.table.where({ key: 'value' }).increment('column')

// throw only when not found, return data
const record = db.table.selectAll().find(1).increment('column')

// don'tthrow when not found, return data
const many = db.table.selectAll().where({ key: 'value' }).increment('column')
```
