### ISSUE TITLE
A few suggestions regarding the GitHub repo setup

### ISSUE THREAD

**Issue by icflorescu** [romeerez/orchid-orm#2]
As I already mentioned in my PR, I think this is a fantastic project and I'd really like to see it gaining traction.
I believe there are a few (code-unrelated) things you should do to the GitHub repo that might help:
- Update the README:
  - delete the default TSDX stuff
  - include a link to the docs website (which is really awesome, by the way)
  - consider adding badges (i.e. from shields.io)
- Update your `About` section text in the right, add some topics (such as `Postgres`, `orm`, etc.) and make sure to include the website link here as well
- In your repo `Settings` you'll find a way to *upload an image to customize your repository’s social media preview*, your logo looks cool, so you could add it there.

I know the above sounds like a lot of hassle, but people need to know about your work, and you'll get a lot more attention if you tick a few boxes.

Have a look at my Mantine DataTable for inspiration: https://github.com/icflorescu/mantine-datatable

**Comment by romeerez** [comment]
@icflorescu I'm so happy to read your message, very-very happy! You somehow found this project and you already like it!

I'm actively working on writing final sections of docs and finalizing features and I was going to make announcement later, next week probably, so didn't yet clean such things as the readme.

Thank you for advices!

**Comment by romeerez** [comment]
I followed all your suggestions, except for promoting on platforms like dev.to, because still want to make some polishing and changes before more people come in. And except for logo, not sure if it's okay to use the current one because of possible copyright issues.
