### ISSUE TITLE
computed column's tagged template type error

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#201]
The latest version breaks [computed column's tagged template type](https://github.com/romeerez/orchid-orm/issues/190#issuecomment-1728599901)

<img width="875" alt="image" src="https://github.com/romeerez/orchid-orm/assets/10382462/4baa3f50-911e-407c-98af-3057046dc233">

**Comment by romeerez** [comment]
Published a fix, it should be fine now.
