### ISSUE TITLE
[feat request] soft delete

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#205]
Hi, do you have plan to add soft delete support

**Comment by bingtsingw** [comment]
I'm recently going to changing some tables to soft delete, if you could prioritize it, that would be helpful.

**Comment by romeerez** [comment]
Sure, the next thing to do is to improve and fix quickstart, then to support nested relations for [this issue](https://github.com/romeerez/orchid-orm/issues/173), and then can do the soft delete. In a couple of weeks, I suppose.

**Comment by IlyaSemenov** [comment]
I'd love to see some kind of soft delete helpers as well.

I wanted to share the approach/recipe I've been using in Objection.js which ideally I'd like to be able to port to Orchid:

```ts
await MyModel.query().where(...).softDelete() // converts to patch({ is_deleted: true })
await MyModel.query() // omit deleted by default
await MyModel.query().modify('include_deleted') // pull everything
await OtherModel.query().withGraphFetched('mymodels') // omit deleted for HasManyRelation
await OtherModel.query().withGraphFetched('mymodel') // don't omit for BelongsToOneRelation
```

Implementation:

```ts
class MyModel extends Model {
  static query<M extends MenuCategoryModel>(trx?: TransactionOrKnex) {
    // Omit deleted objects by default
    return super.query(trx).onBuild(qb => {
      const { include_deleted } = qb.context()
      // Don't omit deleted objects when they're fetched as a right side
      // of a BelongsToOneRelation, to ensure type safety
      // (or when explicitly asked to include deleted)
      if (
        !include_deleted &&
        !qb.has(
          op =>
            op.name === 'find' &&
            op.relation instanceof Model.BelongsToOneRelation,
        )
      ) {
        qb.where({ is_deleted: false })
      }
    }) as QueryBuilderType<M>
  }

  static modifiers: Modifiers<QueryBuilder<MyModel>> = {
    /** Include deleted objects */
    include_deleted: (qb, value = true) => {
      qb.context({ include_deleted: value })
    },
  }
}
```

Do you think that's something doable in Orchid?

**Comment by bingtsingw** [comment]
In my experience, I used to set a deleted_at field for my table, if `softDelete()` runs, update this field to the current time.
I think `updated_at` is more useful than a boolean `is_deleted`.

**Comment by romeerez** [comment]
Thanks for sharing. Yes, of course, it must be doable. Just need to research and put more thinking into details.

Let the column be a nullable timestamp `deletedAt`. There should be a way to specify a column name.

By default, tables are not soft-deletable, and users have to explicitly add some config to a specific table to make it soft-deletable.

Such table will include `WHERE "deletedAt" IS NULL` to its all queries by default. And I think that making an exception for 'belongs to' is counter-intuitive, so it also will filter records.

Instead of `softDelete` method, let the regular `delete` do that in case the table is soft-deletable.

And there will be `hardDelete` method to actually delete.

`includeDeleted` method to remove that filter from query.

I'll do more research on it to see how battle-tested ORMs are doing this.

**Comment by IlyaSemenov** [comment]
> I used to set a deleted_at field for my table

Agreed, I used is_deleted for brevity in the example above.

> And I think that making an exception for 'belongs to' is counter-intuitive, so it also will filter records.

It could be counter-intuitive, but I'd very much prefer if that was doable this way or another, with some kind of opt-in/plugin API.

For starters, filtering 'belogs to' will lead to runtime crashes (unless `this.belongsTo` will set `required: false` automatically when a referred table is soft-deletable):

```ts
const posts = await db.post.select('id', {
  user: q => q.user.select('name')
})
for (const post of posts) {
  console.log(post.user.name) // will crash for soft-deleted user.
}
```

**Comment by romeerez** [comment]
By default the relation is not required, so `post.user` is undefined.

And if it's required, by app logic the post must have an author, but it appears that the user was deleted, it will throw `NotFoundError` when performing the query.

And if we omit the filter here, it's possible that the deleted author will show up for the post, which seems to be wrong.

**Comment by bingtsingw** [comment]
Thank you, I like this feature!

**Comment by romeerez** [comment]
Soft delete is ready! [docs](https://orchid-orm.netlify.app/guide/orm-and-query-builder.html#softdelete)

Also renamed `unScope` to `unscope`.
