### ISSUE TITLE
Need to pause Orchid ORM for a while

### ISSUE THREAD

**Issue by romeerez** [romeerez/orchid-orm#208]
I had to pause Orchid ORM while was looking for a job, but that is done - found the one that is better than I could hope for, they mailed me because they noticed this ORM, and 4 people in total connected with me after noticing ORM. So I'm happy.

Not sure how I'll combine a full-time job with ORM, but I promised you and myself.

**Comment by bingtsingw** [comment]
Good luck with your job search!

**Comment by rdunk** [comment]
Good luck and thanks for all your efforts so far. Orchid ORM is an amazing amount of work for one person.
