### ISSUE TITLE
Typescript compilation problem since 1.17.19

### ISSUE THREAD

**Issue by krichards** [romeerez/orchid-orm#209]
Since v 1.17.19  I'm getting errors with our typescript compilation.  I presume it's related to this change

Optimize exported types of columns and column methods by explicitly writing them instead of inferring

I get 

│ db/tables/tables.ts(36,15): error TS18046: 't' is of type 'unknown'.
│ db/tables/tables.ts(64,10): error TS18046: 't' is of type 'unknown'.

Where I'm trying to create a BaseTable with
```

const BaseTable: TableType = createBaseTable({
  snakeCase: true,
  columnTypes: (t) => ({
    ...t,
    timestamp: <P extends number>(precision?: P) => t.timestamp<P>(precision).asDate() as any,
  }),
});
```

**Comment by romeerez** [comment]
Thanks for trying and reporting!

```ts
const BaseTable: TableType = createBaseTable({
```

What is the `TableType` here for? I guess this might be a problem, could you try removing it?

It's hard to tell by this code, similar code works on my end, if you could make a minimal repro that would help. Maybe the version of `orchid-orm` is conflicting with the version of `pqb`, try updating all such packages to the latest version.

**Comment by krichards** [comment]
I use this

export type TableType = ReturnType<typeof createBaseTable>;

If I don't type BaseTable I  get this typescript compiler error.

**TS2742: The inferred type of 'BaseTable' cannot be named without a reference to '.pnpm/pqb@0.18.28/node_modules/pqb'. This is likely not portable. A type annotation is necessary.**

I don't have an explicit dependency for pqb so it is whatever we inherit from orchid - in this case it is the latest 0.18.28.

**Comment by krichards** [comment]
I've found the error - my bad it wasn't where I thought but slightly further down.  I've distilled it down to this file

```
import { createBaseTable, Table } from 'orchid-orm';

export type TableConfig = Table['columns'];
export type TableType = ReturnType<typeof createBaseTable>;

const BaseTable: TableType = createBaseTable({
  snakeCase: true,
  columnTypes: (t) => ({
    ...t,
    timestamp: <P extends number>(precision?: P) => t.timestamp<P>(precision).asDate() as any,
  }),
});

export class DeviceCodeTable extends BaseTable {
  readonly table = 'device_code';
  columns: TableConfig = this.setColumns((t) => ({
    userCode: t.varchar(),
  }));
}

```

Previously it was fine - I'm guessing typescript inferred the argument for this.setColumns but now is unable to.

**Comment by romeerez** [comment]
Column types are `unknown` in the `Table` type, and that's on purpose because it's a generic type, it can't know the exact column types.

I removed these explicit types and have no TS errors:

```ts
import { createBaseTable } from './baseTable';

const BaseTable = createBaseTable({
  snakeCase: true,
  columnTypes: (t) => ({
    ...t,
    timestamp: <P extends number>(precision?: P) =>
      t.timestamp<P>(precision).asDate(),
  }),
});

export class DeviceCodeTable extends BaseTable {
  readonly table = 'device_code';
  columns = this.setColumns((t) => ({
    userCode: t.varchar(),
  }));
}
```

The `Table` type is internal and not meant to be used other than for generic functions.

**Comment by krichards** [comment]
As I mentioned If I dont have a type for BaseTable then I get this

TS2742: The inferred type of 'BaseTable' cannot be named without a reference to '.pnpm/pqb@0.18.28/node_modules/pqb'. This is likely not portable. A type annotation is necessary.

I'll take a look if I can work around it.

**Comment by krichards** [comment]
The module I'm creating is a shared library so I have declaration: true in my ts-config.json.

When this is enabled I get the errors shown above.

**Comment by krichards** [comment]
Hmmm ... I think (somehow) this is related to us using pnpm to do the install.   Using npm does not **seem** to generate the same errors.

**Comment by krichards** [comment]
Seems like I have been hit by this typescript/pnpm issue

https://github.com/microsoft/TypeScript/issues/47663#issuecomment-1519138189

**Comment by krichards** [comment]
This seems to work "import {} from 'pqb'" and adding pqb as a direcet dependency.

**Comment by romeerez** [comment]
Cool, so it's solved, right?

Yes, `pqb` is a required dependency. This should be clarified in the docs.

**Comment by krichards** [comment]
I'm not sure why I have to still include  the 

import {} from 'pqb'

For it to work,  I kinda understand that you need to install pqb, but its definitely a pnpm/typescript issue. Hopefully this might help someoneelse.

**Comment by romeerez** [comment]
> I'm not sure why I have to still include the
> import {} from 'pqb'

This isn't right, importing nothing is weird. Please, make a min reproduction repo, I'll look into it. The problem must be related to the fact that you're doing a shared library, so you have some unique setup for it.
