### ISSUE TITLE
Infer custom keys in group method.

### ISSUE THREAD

**Issue by NelsonMK** [romeerez/orchid-orm#212]
In the following example I am able to get month inferred inside the order method but not in the group method
```ts
 db.orders.select({month: db.orders.sql<number>`extract(month from "createdAt")`}).order('month').group('month')
```

**Comment by romeerez** [comment]
I published a fix for this, and now grouping by selected SQL is supported.

I noticed that the month is returned as a string, you can parse it to a number in such way:

```ts
      const q = db.orders.select({
        month: db.orders.sql<string>`extract(month from "createdAt")`.type((t) =>
          t.string().parse(parseInt),
        ),
      }).group('month');
```
