### ISSUE TITLE
rakedb.lazy runs "up" changes in reverse order after "down" migration

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#214]
I have rakedb.lazy multi-change migration, such as:

```ts
export default [
  change(async (db, up) => {
    console.log("change 1", up)
  }),
  change(async (db, up) => {
    console.log("change 2", up)
  }),
]
```

If I execute `run(["up"])` then `run(["down"])` then `run(["up"])` again, the second up runs changes in reverse order:

```
change 1 true
change 2 true
change 2 false
change 1 false
change 2 true
change 1 true
```

It's probably reversing them in-place on `down` somewhere instead of making a copy with the reverse order.

* rake-db 2.10.65

**Comment by romeerez** [comment]
Thank you for catching it, indeed there was a mutable `reverse` that caused this, fixed in the latest update.
