### ISSUE TITLE
Extract result type from a helper

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#215]
Consider a helper:

```ts
const userHelper = db.user.makeHelper((user) => user.select("id", "name"))
```

Can we have a utility type to pull the resulting type of this helper as if it were applied directly to the database?

For now, I'm using this:

```ts
// Unused, only for typing.
const _select_user_impl = () => select_user(db.user)

// Can we somehow extract this directly from select_user?
export type User = Awaited<ReturnType<typeof _select_user_impl>>[0]
```

**Comment by romeerez** [comment]
Added `QueryHelperResult` type helper:

```ts
import { QueryHelperResult } from 'pqb';

const selectHelper = db.table.makeHelper((q) => q.select('id', 'name'));

// This type is identical to `db.table.select('id', 'name')`
type SelectQuery = QueryHelperResult<typeof selectHelper>;

// Await to get result, the type is `{ id: number, name: string }[]`
type Result = Awaited<QueryHelperResult<typeof selectHelper>>;
```

To combine a result type of helper with a type of other query:

```ts
const otherQuery = db.table.select('something')

const result = await selectHelper(otherQuery)
// result has id, name, and something, - how to get this type?

import { QueryHelperResult, MergeQuery } from 'pqb';

type CombinedResult = MergeQuery<typeof otherQuery, QueryHelperResult<typeof selectHelper>>
```

**Comment by IlyaSemenov** [comment]
@romeerez Thanks! Any reason these are exported by pqb rather than orchid-orm itself? 

See, typically, a developer doesn't need to install and use pqb directly. Even though pqb is pulled by orchid-orm, in a pnpm project it's not accessible to user-land code unless explicitly installed.

I always considered pqb as a lower-level escape hatch to Postgres-specific functions. `makeHelper` is accessible without `pqb`, so I suppose `QueryHelperResult` should be too.

**Comment by romeerez** [comment]
That's a good point, then I'll re-export it from orchid-orm, adding this to todo. `makeHelper` is also re-exported.

**Comment by romeerez** [comment]
@IlyaSemenov done: now everything is re-exported from `orchid-orm`, and no need to have `pqb` among dependencies.
