### ISSUE TITLE
[TSError] When declaring `vector` string inside a `search()` method

### ISSUE THREAD

**Issue by matthewmorek** [romeerez/orchid-orm#217]
I created a repo method to allow searching for strings inside one of my db tables. When declaring a `vector` to use with my query, I'm getting the following TS error:

<img width="553" alt="CleanShot 2023-11-22 at 21 24 53@2x" src="https://github.com/romeerez/orchid-orm/assets/1137994/aae45c9c-7685-47aa-9b57-bad2adb59017">

This is how I define my vector in said table:
```ts
change(async (db) => {
  await db.createTable(
    "location",
    { createIfNotExists: true, dropIfExists: true },
    (t) => ({
      // ... omitted table columns
      generatedTsVector: t
        .tsvector()
        .generated(["title", "description", "locality", "host_name", "address"])
        .searchIndex(),
    }),
  );
});
```

This is how I define my search method:
```ts
filteredBySearchQuery(q, searchQuery: string = undefined) {
  return searchQuery && searchQuery !== ""
    ? q.search({
        vector: "generated_ts_vector",
        query: searchQuery,
      })
    : q;
}
```

Which results in the following TS error:
```
Type 'string' is not assignable to type 'never'.
```
<img width="547" alt="CleanShot 2023-11-22 at 21 23 02@2x" src="https://github.com/romeerez/orchid-orm/assets/1137994/f9a33eb0-30f0-47ee-af89-2f24d8c86785">

This is how I call the repo search method:
```ts
const locations = await locationRepo
  .allWithRelations()
  .onlyPublished()
  .filteredByEventType(selectedEventType)
  .filteredByFacilities(selectedFacilities)
  .filteredBySearchQuery(searchQuery)
  .offset(skip)
  .limit(take);
```

It looks to me like a simple type error, but without ignoring it it crashes my Next.js 13 build on Vercel.

Querying works perfectly when I use it in dev environment (where type errors don't cause a critical error), it only fails the build process where types are strictly checked.

**Comment by romeerez** [comment]
I can see this column `generated_ts_vector` is of type `tsvector` in your migration, but what is the column type in your table file?

Type `never` from the error indicates that it cannot find tsvector columns in the table.

**Comment by matthewmorek** [comment]
The casing is correct, as I explicitly use snake_case for compatibility. Good call on the table structure: the table definition file didn't contain the correct reference to vector. All fixed now, thanks!

The error totally threw me off, as I was expecting to see something like "this property doesn't exist on type X".
