### ISSUE TITLE
whereNot doesn't work as expected on multiple conditions

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#218]
Consider a query:

```ts
await db.book.whereNot({ id: 1 }, { title: "Test" })
```

As a developer, I would expect the ORM to select all books other than the book with ID=1 named "Test" (because both conditions are wrapped into `whereNot`, where they are supposed to be AND'ed).

Instead, it selects all books excluding all books where either ID=1 _or_ the name is "Test":

```
SELECT * FROM "book" WHERE NOT "book"."id" = $1 AND NOT "book"."title" = $2 [1, 'Test']
```

Expected:

```
SELECT * FROM "book" WHERE NOT ("book"."id" = $1 AND "book"."title" = $2) [1, 'Test']
```

**Comment by IlyaSemenov** [comment]
The above could be arguably treated as a gotcha, but the callback form is clearly misbehaving:

```ts
await db.book.whereNot((q) => q.where({ id: 1 }).where({ title: "Test" }))
```

```
SELECT * FROM "book" WHERE NOT "book"."id" = $1 AND NOT "book"."title" = $2 [1, 'Test']
```

I believe `whereNot` should not try to be smart and should simply wrap everything with `NOT( ...it's not whereNot's business what's here... )`.

**Comment by romeerez** [comment]
The fix is ready, now `whereNot` behaves as you're expecting.

I decided to make it not accept multiple arguments, so this no longer compiles:

```ts
await db.book.whereNot({ id: 1 }, { title: "Test" })
```

For `NOT ( id = 1 AND title = 'Text' )`:

```ts
await db.book.whereNot({ id: 1, title: "Text" })
```

For `NOT id = 1 AND NOT title = "Text"`:

```ts
await db.book.whereNot({ id: 1 }).whereNot({ title: "Text" })
```
