### ISSUE TITLE
[ask] how to build relation data with factory

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#220]
I have a activityMember table, the `userId` field is `unique` with `foreign key`
```
await factory.activityMember.createList(10, {
  userId: 'how to build new user'
})
```

**Comment by romeerez** [comment]
I published update for this, now it is possible with:

```ts
await factory.activityMember.createList(10, {
  userId: async () => (await factory.user.create()).id,
})
```

In this example, a new user is created for every activity member.
