### ISSUE TITLE
createTable without primary key

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#225]
Currently, it doesn't seem to be possible to create a table without a primary key:

```
change(async (db) => {
  await db.createTable("test", (t) => ({
    foo: t.string(),
    bar: t.string(),
  }))
})
```

gives:

```
Table test has no primary key.
You can suppress this error by setting { noPrimaryKey: true } after a table name.
```

However, rakedb `createTable` doesn't support that kind of options object, the options are for the actual ORM layer.

I suppose `createTable` could accept a third optional argument with the options?

**Comment by romeerez** [comment]
> However, rakedb createTable doesn't support that kind of options object

Are you sure it's not supported? It's fine in tests.

```ts
await db.createTable('table', { noPrimaryKey: true }, () => ({
  // ...
}));
```
