### ISSUE TITLE
On Conflict [target]

### ISSUE THREAD

**Issue by cressie176** [romeerez/orchid-orm#23]
Hi @romeerez,

I'm curious about Orchid's ON CONFLICT semantics, e.g.

```
Table.create(data).onConfict('email')
```

PostgreSQL allows a conflict target to be specified so you can handle conflicts differently depending on which constraint is violated. Is this supported by orchid?

**Comment by romeerez** [comment]
Thanks for pointing! Currently only one `onConflict`.

**Comment by romeerez** [comment]
Improved `onConflict` usage without argument:

- when doing `onConflict().ignore()` it will output `ON CONFLICT DO NOTHING` without columns, previously it was inserting columns automatically.

- when doing `onConflict().merge()` it will automatically find all table columns that are used in this `INSERT` and that have a unique index or are used in a composite index, and insert them as a conflict target.
