### ISSUE TITLE
[help] API change when update to the latest version

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#230]
The new version changed some exports of types, my old code shows lots of errors.

1. columnTypes
<img width="828" alt="image" src="https://github.com/romeerez/orchid-orm/assets/10382462/003787f7-f61b-4ebc-95df-a3c771379405">

2. DefaultColumnTypes
<img width="903" alt="image" src="https://github.com/romeerez/orchid-orm/assets/10382462/4c8e0d9a-1f13-4de1-a503-cb589e18998a">

**Comment by bingtsingw** [comment]
`jsonInsert` and `jsonSet` shows error
<img width="775" alt="image" src="https://github.com/romeerez/orchid-orm/assets/10382462/e938a356-7c13-4d4a-b0d6-cd077452fe8a">

**Comment by bingtsingw** [comment]
A bug in relation query:

I have a `TableActivity` which has many `TableActivityMember`s
```
export class TableActivity extends BaseTable {
  public readonly table = 'activity';
  public readonly softDelete = true;

  public columns = this.setColumns((t) => ({
  }));

  public relations = {
    members: this.hasMany(() => TableActivityMember, {
      required: true,
      primaryKey: 'id',
      foreignKey: 'activityId',
    }),
  };
}
```

My old query is `db.activity.whereExists('members', (q) => q.where({ 'members.userId': 'xxxxx' }))`, which now shows type error, but the query result is correct.

The correct type for this version changed to `activity_member.userId`, but the query shows 500.

It seems the new version has wrong type hint.

**Comment by romeerez** [comment]
Thank you for testing the new build!

1. columnTypes

You don't have to import it, try this instead:

```ts
q.sql`*sql string*`.type((t) => t.string())
```

2. DefaultColumnTypes

Is it necessary for `cuid` to be a separate function?

If not:

```ts
export const BaseTable = createBaseTable({
  columnTypes: (t) => ({
    ...t,
    cuid() {
      return t
        .varchar(36)
        .primaryKey()
        .default(() => createId());
    },
  }),
});
```

If it has to be a separate function:

```ts
import { ColumnSchemaConfig } from 'orchid-core';

const cuid = (t: DefaultColumnTypes<ColumnSchemaConfig>) => {
```

I didn't expect that you may want to use this type, so it's not exported from orchid-orm or pqb, so it's exported from `orchid-core`. Do you think it's better to export it from orchid-orm?

> A bug in relation query:

I'm glad it's not critical and you can temporarily add ts-ignore, I'll try to handle it in the near days.

**Comment by bingtsingw** [comment]
1. columnTypes
<img width="972" alt="image" src="https://github.com/romeerez/orchid-orm/assets/10382462/201ceb2b-4364-457d-88b5-573d0d41a6a5">

`t => t.string()` seems not work

**Comment by bingtsingw** [comment]
2. DefaultColumnTypes

<img width="571" alt="image" src="https://github.com/romeerez/orchid-orm/assets/10382462/362c169a-848a-4a85-b158-33a0773c6136">

`DefaultSchemaConfig` works well in my code, and it do not need to import from `orchid-core`, can I write `DefaultSchemaConfig` instead of `ColumnSchemaConfig`, if not, I think it's better to re-export `ColumnSchemaConfig` in `orchid-orm `

**Comment by bingtsingw** [comment]
3. Any clue in `jsonInsert` and `jsonSet` query?

**Comment by bingtsingw** [comment]
4. I add `ts-ignore` comment, it works for now, thank you.

**Comment by romeerez** [comment]
Sorry for late reply, I'll have more time from now on;

1. columnTypes

Column types became more dynamic, that's on purpose, so the `Query` type doesn't know the exact types you have.
Exact types are defined in the `BaseTable` (returned by `createBaseTable`).

I just pushed update so that `BaseTable` now will have `columnTypes` prop on it, and you can use your `BaseTable` in that `type` callback:

```ts
import { Query } from 'orchid-orm';
import { BaseTable } from './path-to-your-base-table';

export const SQLFormat = {
  timeCN(q: Query, column: string, format: string) {
    return q.sql`to_char(${q.column(
      column,
    )} + interval '8 hours', ${format})`.type(() =>
      BaseTable.columnTypes.string(),
    );
  },
};
```

2. DefaultColumnTypes

So this is already exported from 'orchid-orm' - good - no changes are needed.

3. Any clue in jsonInsert and jsonSet query?

Worked with zod config, but apparently, there is a bug when you use default column types.

I pushed a fix for this, should be fine now.

**Comment by romeerez** [comment]
> The new version is pleasant to use, typescript hinting is faster and json schema is much easier to write.

I'm so happy to have this feedback from you!

There are more ideas to try to optimize TS further, it will become faster over time.

Just pushed an update to resolve this problem:

```ts
db.activity.whereExists('members', (q) => q.where({ 'members.userId': 'xxxxx' }))
```

Now it should be ok.

Closing this issue, let me know if any problem.
