### ISSUE TITLE
[bug] type error for makeHelper in relation sub query

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#232]
```
const selectForDefault = db.post.makeHelper((q) => {
  return q.select('id');
});

db.user.select({
  post: (q) => selectForDefault(q.post), // type error
})
```

It works in old versions, but throw a type error in `1.21.5`, fortunately, it's a type error, I add `@ts-ignore` to handle this for now

**Comment by romeerez** [comment]
I'm able to reproduce with `posts` relation, the error happens because inside `makeHelper` it's able to reference "post.id":

```ts
const selectForDefault = db.post.makeHelper((q) => {
  return q.select('post.id');
});
```

But for `user`, this is called `posts` and the type doesn't match:

```ts
db.user.select({
  posts: (q) => q.posts.select('posts.id'), // posts is ok
  posts: (q) => q.posts.select('post.id'), // singular 'post' is not okay
})
```

If I name the relation to `post`, as in your example, I don't have a type error.

**Comment by bingtsingw** [comment]
My problem seems to be related to the table name
<img width="412" alt="image" src="https://github.com/romeerez/orchid-orm/assets/10382462/2c8d9ddc-768b-4a9c-949b-a7d705010042">
<img width="387" alt="image" src="https://github.com/romeerez/orchid-orm/assets/10382462/17417de9-3e86-4257-bbb9-ba680342feb5">
<img width="489" alt="image" src="https://github.com/romeerez/orchid-orm/assets/10382462/a4c901b8-db08-447a-b816-02aed63e60eb">

If I comment `public readonly table = 'activity_type';`, there is no error.

Seems the new type infer based on the table name, not the relation name

**Comment by romeerez** [comment]
I recently published an update to solve the problem I understand it.

So after you install the new version, both of these becomes valid:

```ts
const selectForDefault = db.post.makeHelper((q) => {
  return q.select('post.id'); // the table is referenced as `post`
});

db.user.select({
  posts: (q) => selectForDefault(q.posts), // q.posts table alias is `posts` and it's fine by the helper
  posts: (q) => selectForDefault(q.post.as('whatever')), // whatever table alias is fine by the helper
})
```

The error on your screenshot says that the selectable type of "category" isn't assignable to "activity_type", and if you alias "activity_type" as "category" this problem should be solved, but possibly it's something a bit different.

Let me know if the update solves the problem.

**Comment by bingtsingw** [comment]
The latest version works perfect, thank you
