### ISSUE TITLE
[typescript] Issue with inferred types after upgrading from v1.19.0

### ISSUE THREAD

**Issue by matthewmorek** [romeerez/orchid-orm#233]
After a recent upgrade from `v1.19.0` I started experiencing TypeScript errors related to types inferred from simple DB queries, such as:
```ts
// methods.ts
import { db } from "@/db/db";

export async function getRegionByName(name: string) {
  const result = await db.region.findBy({ name: name });
  return result;
}

// layout.tsx
import { getRegionByName } from "./methods";

export async function generateMetadata({ params }) {
  const selectedRegion = params.region || undefined;
  const currentRegion = selectedRegion
    ? await getRegionByName(selectedRegion)
    : undefined;

  const pageTitle = selectedRegion
    ? `Locations in ${currentRegion.title}, UK`
    : "All locations in the UK";
  return { title: pageTitle };
}
```
## Issue
Whilst running the same schema and functions between `v1.19.0` and `v1.20.0` as above, I'm getting the following type error on `v1.20.0` and above:
![CleanShot 2024-02-13 at 12 24 55@2x](https://github.com/romeerez/orchid-orm/assets/1137994/e1b574ad-6b70-4bac-8d71-c71970b3c1ba)

Essentially, Orchid doesn't return any column types correctly anymore, and trying to work around it using explicit typing results in compatibility errors.

## Expected result
![CleanShot 2024-02-13 at 12 28 35@2x](https://github.com/romeerez/orchid-orm/assets/1137994/ec57ddff-a92d-46ff-bc78-a62ee02be0c0)

### Repro repository
I created a simple repro example for you to have a look: https://github.com/matthewmorek/orchidorm-db-playground

Main branch contains stable version under `1.19.0` which works correctly, while the following branch contains the exact same code with Orchid upgraded to `1.20.0`: https://github.com/matthewmorek/orchidorm-db-playground/tree/chore/upgrade-orchid-orm

As mentioned before, my application code didn't change, only version of Orchid was upgraded.

Let me know if you need any more info about this, but the reproducible example should contain everything, as Orchid trips on fairly simple DBs, let alone on queries with subqueries and complex relations. It works perfectly under `1.19.0`.

**Comment by romeerez** [comment]
I caught a flu so need some more time before looking into this

**Comment by matthewmorek** [comment]
It's non-urgent as it works fine on 1.19.0 so far. I hope you'll feel better soon!

**Comment by matthewmorek** [comment]
Thanks for taking a look at it and the pointers!

I guess the breaking change between `1.19.0` and `1.20.0` for my project was the need for `strict` in `tsconfig.json` to be set to `true`.
