### ISSUE TITLE
[ask] Support polymorphic relations

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#249]
There are many scenarios where polymorphic associations are used. For example, I have a 'comment' table, and 'note', 'article', 'activity' each require comment functionality.

I may design the `comment` table field to: 
```typescript
interface Comment {
  id: string;
  content: string;
  commentable_id: string;
  commentable_type: string;
}
```

I hope I can easily use `db.xxx.comments` to build query for comment.

There is an article to introduce the [polymorphic relation pattern](https://medium.com/@hendelRamzy/what-is-polymorphic-relationships-and-how-they-work-61df8d1562c5)

**Comment by romeerez** [comment]
I wish it could be implemented sooner, but it's rather complex, and I have some doings in progress.

For now, you can set `hasMany` relation from note, article, and others to the comment, and manually add `where({ commentableType: 'article' })` when loading comments, and manually add it when creating the comment.

```ts
const articleWithComments = await db.article.select({
  comments: (q) => q.comments.where({ commentableType: 'article' })
})
```

**Comment by IlyaSemenov** [comment]
Besides, if using UUID for the ID, it's not even necessary to filter on commentableType when querying.

**Comment by romeerez** [comment]
You're right, but also ideally it should be possible to query the other way around: take the comment and load its parent resource.

**Comment by bingtsingw** [comment]
@romeerez  Thank you for your response, I agree with you not to implement it because it's not valuable enough, especially when I saw @IlyaSemenov 's solution, which I had not even thought of before, it's really a fantastic perspective.

As of multiple tables vs one table, that depends on the business model. In the scenario of comment, I'd like to think of comment as an Independent service and cover all the logic inside.
