### ISSUE TITLE
Docs: missing link to `getCurrentUserId` in the docs

### ISSUE THREAD

**Issue by TAKANOME-DEV** [romeerez/orchid-orm#25]
The link to [getCurrentUserId](https://github.com/romeerez/orchid-orm-examples/blob/4fbaa097ed90ac32095e1de20893fe9953668b29/packages/blog-api/src/app/user/user.service.ts#L3) is not included in the docs.

![image](https://user-images.githubusercontent.com/79809121/219965572-4c2db8ca-8d38-4d5c-9e88-03afdba73a22.png)

**Comment by romeerez** [comment]
Thanks for pointing, added
