### ISSUE TITLE
non-async afterMigrate/afterRollback methods

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#251]
I'd like to have non-async afterMigrate/afterRollback, but the typings won't allow that:

https://github.com/romeerez/orchid-orm/blob/e936561438be2413e5fcf8077e6054f23ac02020/packages/rake-db/src/config.ts#L47-L50

I suppose it's safe to mark them as `void | PromiseLike<void>`.

**Comment by romeerez** [comment]
Sure, a minor edit, I pushed an update with this.
