### ISSUE TITLE
providing migrationId: 'timestamp' default in setup or asking from user

### ISSUE THREAD

**Issue by KMJ-007** [romeerez/orchid-orm#257]
when setting up the orchid first time, by default for demo table, it generates timestamp base migration file, when we try to run it, we get error, we need to pass migrationId: 'timestamp' in dbScript file, i think either ask user when setting up the orm about migrationId type or by default give timestamp, because that's what are generated in default tables!

i can create PR for this change, if you like, or let me know there are any other thought behind keeping this way!

<img width="617" alt="image" src="https://github.com/romeerez/orchid-orm/assets/86996507/b6b81ebd-df83-4375-9fd8-1b2ef0669b7f">

**Comment by romeerez** [comment]
Thank you for pointing. I fixed this a couple of days ago, but it didn't publish for some reason.

Now it should work fine with

```sh
npm create orchid-orm@latest
# or
pnpm create orchid-orm
```
