### ISSUE TITLE
insertMany to work with 0 records

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#260]
Currently, `insertMany([])` generates invalid SQL and crashes:

```ts
await db.user.insertMany([])
```

```
INSERT INTO "user"("user") VALUES
Error: syntax error at end of input
```

Can we perhaps instead return 0 immediately without actually running any SQL? Same goes for `createMany`.

**Comment by romeerez** [comment]
Thanks for pointing, I published an update with this.
