### ISSUE TITLE
Order by raw SQL expression docs outdated

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#261]
The documentation at https://orchid-orm.netlify.app/guide/query-methods.html#ordersql suggests:

```ts
db.table.order`raw sql`;
// or
db.table.order(db.table.sql`raw sql`);
```

The first syntax doesn't seem to work anymore:

```
Argument of type 'TemplateStringsArray' is not assignable to parameter of type 'OrderArg<TableToDb<UserTable, EmptyObject>>'.ts(2345))
```

I know how to handle this (and I remember about the recent refactorings), just adding an issue to update the docs at some point.

**Comment by romeerez** [comment]
Fixed
