### ISSUE TITLE
Make rake-db import optional again

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#265]
I upgraded from 1.24 to 1.27 and noticed that rake-db now requires `import` option. However, since I'm passing `migrations` collection directly, I don't think rake-db is actually using `import`.

If that is so, I propose to make `import` optional again, and instead crash in runtime with the suggested implementation included in the error message.

Alternatively, make the options type context-aware with something like:

```ts
{
  migrations: ModuleExportsRecord
  migrationsPath?: never
  import?: never
} | {
  migrations?: never
  migrationsPath?: string
  import(path: string): Promise<unknown>
}
```

or perhaps refactor it altogether:

```ts
migrations: ModuleExportsRecord | { path?: string; import(path: string): Promise<unknown> }
```

(UPD: both are records/objects so tech wise this won't work as is, but I'm keeping it just as something to consider).

**Comment by romeerez** [comment]
Done, now `import` is optional when you have `migrations`.

The import is also used for code generation, not only for loading migrations. It will throw a runtime error if it's not set and you're trying to use `db generate (g)`.
