### ISSUE TITLE
afterChangeCommit always receives all migrations

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#267]
I'm trying to use `afterChangeCommit` added in #252 and what I observe is that `migrations` is always the full list, even if I simply doing `up` on the fully migrated table.

```ts
export const change = rakeDb(
  { databaseURL },
  {
    baseTable: BaseTable,
    migrationsPath: './migrations',
    migrationsTable: 'rakedb_migration',
    migrationId: 'serial',
    import: path => import(path),
    async afterChangeCommit({ migrations }) {
      // here migrations is always the full list, not the list of applied migrations
      console.log('dumping', migrations.length)
    },
  },
)
```

This contradicts the example in [docs](https://github.com/romeerez/orchid-orm/blob/main/docs/src/guide/migration-setup-and-overview.md?plain=1#L502-L503), "skip dumping" will never happen:

```ts
    afterChangeCommit({ options, migrations }) {
      // skip dumping if there were no pending migrations
      if (!migrations.length) return;
```

Relevant code:

https://github.com/romeerez/orchid-orm/blob/66859299e149d512449724e6fb6482ce37f034be/packages/rake-db/src/commands/migrateOrRollback.ts#L130-L134

**Comment by romeerez** [comment]
It was somehow missed in the implementation,

now I published a fix to rake-db and all callbacks show 0 migrations when nothing was migrated, or a precise number when only a few were migrated.
