### ISSUE TITLE
.rename-to-serial.json doesn't work with bundled migrations

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#268]
Disclaimer: I realise that I'm perhaps the only person who will need this, but it's a problem and I want to report it.

I'm migrating from timestamps to serial migrations. I seem to be unable to migrate the project which uses pre-bundled `migrations` modules (not `migrationsPath` + `import`).

From the quick look, I see that `getMigrationsFromFiles` returns the migration module loaders, but doesn't create the loader for `.rename-to-serial.json` (it only records its existence):

https://github.com/romeerez/orchid-orm/blob/66859299e149d512449724e6fb6482ce37f034be/packages/rake-db/src/migration/migrationsSet.ts#L108-L109

The actual JSON is loaded later on in `renameMigrations`:

https://github.com/romeerez/orchid-orm/blob/66859299e149d512449724e6fb6482ce37f034be/packages/rake-db/src/migration/manageMigratedVersions.ts#L152-L156

Respectively, there is no way [getMigrationsFromConfig](https://github.com/romeerez/orchid-orm/blob/66859299e149d512449724e6fb6482ce37f034be/packages/rake-db/src/migration/migrationsSet.ts#L47) could somehow follow the same contract.

If `getMigrationsFromFiles` returned the loader that would load the rename map from JSON file (instead of `renameTo` string ID), same way as it does for modules already, `getMigrationsFromConfig` could similarly provide the "loader" that simply returns the pre-imported rename JSON taken from some rake config option like `migrationsRenameMap?`.

---

Similarly, I believe `change-ids serial` shouldn't refuse to work when it sees `migrations` instead of `migrationsPath`. It should simply output JSON to `${cwd}/.rename-to-serial.json` (or simply to `stdout`) and add short instruction that this JSON should be imported manually and passed to the respective rake config option.

**Comment by romeerez** [comment]
I guess I didn't account for using `change-ids` for bundled migrations, so that should be handled separately, and yes probably only for you :)

`change-ids` is doing business of renaming files + some additional steps.

In case when migrations are passed explicitly, it cannot rename files, and the process can only be semi-automated.

> getMigrationsFromConfig could similarly provide the "loader" that simply returns the pre-imported rename JSON taken from some rake config option like migrationsRenameMap?

Makes sense, should be possible.

Sorry, but I'm busy this week and I'll try to look closer by the end of the week.

This issue sounds complex, but there is a chance that it's not as complex to handle as it seems.

**Comment by IlyaSemenov** [comment]
> In case when migrations are passed explicitly, it cannot rename files, and the process can only be semi-automated.

I agree, but perhaps `change-ids` could print the proposed shell script? Such as:

```sh
If your migrations are stored in files, run the following commands to rename them:

mv "old_name.ts" "new_name.ts"
mv "old_name.ts" "new_name.ts"
mv "old_name.ts" "new_name.ts"
```

That said, if timestamp migrations are a legacy thing that is to go in future releases, this all is perhaps an overkill. I can handle my case manually with some manual SQL updates, no big deal. I care more about the feature-fullness of the project here.

**Comment by romeerez** [comment]
Done, I published an update.

Now when you have `migrations` and run the `change-ids` command, it will output 2 things:
- A JSON to rename files from old to new versions, you should save it to the config to `renameMigrations`, and it will be used later when deploying.
- A series of `mv` commands so you can navigate to your migrations directory and rename the files.

The command output includes hints of what to do.

Let me know if you going to try it, perhaps you already handed it manually, and if it works fine.

**Comment by IlyaSemenov** [comment]
Sorry — didn't notice this comment on time. I've tried the new logic yesterday, worked flawlessly!

The only minor nuance I encountered is that the `renameMigrations` was emitted as JS code and as such didn't work in a JSON file as is (due to no quotes around keys and extra commas). But that's really a non-issue.

**Comment by romeerez** [comment]
I was going to check on that `renameMigrations` thing later.

**Comment by romeerez** [comment]
Maybe missing something, `renameMigrations` is a JS code because you copy-paste it into JS code into the db script, that's right.

In one case you have `migrationsPath` and the JSON file is emitted and no need to copy-past anything, and in other case you're using `migrations` and then it will emit JS code to copy-paste.
