### ISSUE TITLE
Docs: Missing Installation Step

### ISSUE THREAD

**Issue by djamez** [romeerez/orchid-orm#27]
In the Quickstart documentation page, the instructions assume that the reader has orchid-orm installed globally - as such the installation step is missing:

`npm i orchid-orm # or yarn|pnpm add orchid-orm`

It may be obvious for seasoned developers, but may present a problem for newbies.

**Comment by romeerez** [comment]
@djamez sorry for the late reply, no, it doesn't have to be installed globally, so the Quickstart shows that it should be added to `package.json` dependencies.

Could you please point out where exactly the place in the docs that is confusing?

**Comment by djamez** [comment]
It's true that the `package.json` code-block includes orchid, but the first example in quickstart could be enhanced a little:

```diff
mkdir project
cd project

+ npm init -y                        # or yarn|pnpm init
+ npm install orchid-orm   # or yarn|pnpm add orchid-orm

npx orchid-orm
# or if you're using pnpm
pnpm dlx orchid-orm```

This little addition just adds a bit of clarity, that's all. A fairly knowledgeable Node developer should be able to figure it out easily, but new users...

**Comment by romeerez** [comment]
The goal was to have as few steps as possible, and there is no need for the steps that you're suggesting.

Let me know if it does not work for you without those steps, for me it works fine.

**Comment by romeerez** [comment]
The script that you run by `npx orchid-orm` asks for a path (didn't ask before). If it's a new path it will create a new package.json in there with all the needed dependencies. And if it's an existing project, it will add missing dependencies.

A user only needs to `cd` to the path, run `npm i`, set database creds in `.env`, and create a new db with `npm run db create`, unless already created or cloud-hosted, and all is ready to go.
