### ISSUE TITLE
JS-computed columns

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#270]
Bringing up what's been discussed in #59, I propose to at least have JS-computed columns in the roadmap.

My use case is that I store some kind of internal ID in a varchar, and I want to somehow automatically pull values from an external storage based on that ID.

Imaginary API (very quick attempt, not even a draft):

```ts
export class UserTable extends BaseTable {
  readonly table = "user"

  columns = this.setColumns(t => ({
    id: t.uuid(),
    name: t.string(),
    roleId: t.string(),
  }))

  computed = this.setComputed({
    role: q => q.sql`role_id`.someAfterQueryCallback(async (roleId) => getRoleById(roleId)),
  })
}

await db.user.select("id", "name", "role")
```

Alternatively, it could be something as naive as:

```ts
  computed = this.setComputed({
    role: async (user) => {
      // user is typed as Partial<Selectable<UserTable>>
      assert(user.roleId)
      return await getRoleById(user.roleId)
    },
  })

// User has to specify the dependencies on his own
await db.user.select("id", "roleId", "role")
```

(This is similar to how I was doing it with Objection.js modifiers; of course, the result was untyped.)

**Comment by romeerez** [comment]
It should be doable, last time I left it out because sql-only computeds were enough, and your use case is a legitimate reason to develop it further.

`afterCreate`, `afterUpdate`, and such [hooks](https://orchid-orm.netlify.app/guide/hooks.html#after-hooks) already have an internal logic to enforce column selection.

```ts
export class Table extends BaseTable {
  // ...snip
  
  computed = this.setComputed({
    role: this.compute(
      ['roleId'], // require `roleId`
      async (data) => {
        data // is of type { roleId: string }[]
        // ... load roles by ids
      }
    )
  });
}

// roleId will be selected automatically
await db.user.select("id", "role")
```

**Comment by bingtsingw** [comment]
Vote for this!

**Comment by romeerez** [comment]
In progress, currently planning such design:

```ts
export class Table extends BaseTable {
  // ...columns
  
  computed = (t) => [
    // changing the existing sql computeds into this:
    t.computeInQuery('fullName', q => q.sql`"firstName" || ' ' || "lastName"`.type((t) => t.string())),
    
    // simple runtime computed:
    t.computeAtRuntime('fullName2', ['firstName', 'lastName'], (record) => record.firstName + ' ' + record.lastName),

    // compute a batch:
    t.computeBatchAtRuntime('role', ['roleId'], async (records) => {
      const uniqueRoleIds = [...new Set(records.map((record) => record.roleId))]
      
      const rolesByIds = await loadRolesByIdsFromSomewhere(uniqueRoleIds)

      return records.map((record) => rolesByIds[record.roleId])
    })
  ]
}
```

`computeBatchAtRuntime` is basically a dataloader pattern from GraphQL, to load data based on all loaded records instead of loading data one by one.

For this reason, the simple `computeAtRuntime` won't be allowed to return a Promise, let it be used only for synchronous JS operations.

**Comment by romeerez** [comment]
Ready and published! See the [docs](https://orchid-orm.netlify.app/guide/computed-columns.html).

I'm happy to release this feature because there is probably nothing like it in other ORM, at least not with dependencies and type-safety.
