### ISSUE TITLE
[ask] how to write `orWhere` for only one column

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#278]
```typescript
const activityId = await db.activity
  .where({
    OR: [{ cityId: null }, { cityId: 'xxxxx' }],
    state: 'publish',
    timeStart: { lt: new Date() },
  })
```
I want to query `cityId` is `null` or `xxxxx`, but the `state` and `timeStart` condition is always set.
This query does not work as expected, use `.orWhere` seems not work, too.

**Comment by romeerez** [comment]
Could you write SQL that you want to achieve?

**Comment by romeerez** [comment]
I see that the produced OR is missing `()` around its conditions, I'll fix this. But I was thinking to remove that `OR` later because it kinda feels unnatural.

To get this SQL:
```sql
WHERE (cityId IS NULL OR cityId = 'xxxxx') AND state = 'publish' AND timeStart < 'date'
```

use a callback:

```ts
const activityId = await db.activity.where(
  (q) => q.orWhere({ cityId: null }, { cityId: 'xxxxx' }),
  {
    state: 'publish',
    timeStart: { lt: new Date() },
  },
);
```

**Comment by bingtsingw** [comment]
```
const activityId = await db.activity
  .where((q) => q.orWhere({ cityId: null }, { cityId: { notIn: ['wetpoa9fee5jp34gtjtsc49o'] } }), {
    state: EnumActivityState.Publish,
    timeStart: { lt: addHours(new Date(), -4) },
    // // cityId: { notIn: ['wetpoa9fee5jp34gtjtsc49o'] },
    // cityId: null,
  })
  .order({ timeStart: 'ASC' })
  .getOptional('id');
```
This throws an sql error:
```
SELECT "activity"."id" FROM "activity" WHERE "activity"."deleted_at" IS NULL AND (SELECT "activity"."id" FROM "activity" WHERE "activity"."city_id" IS NULL OR NOT "activity"."city_id" IN ($1) ORDER BY "activity"."time_start" ASC LIMIT 1) AND "activity"."state" = $2 AND "activity"."time_start" < $3 ORDER BY "activity"."time_start" ASC LIMIT 1 ['wetpoa9fee5jp34gtjtsc49o', 'publish', '2024-06-05T13:31:18.871Z'] Error: argument of AND must be type boolean, not type character varying
```

**Comment by bingtsingw** [comment]
> ```sql
> WHERE (cityId IS NULL OR cityId = 'xxxxx') AND state = 'publish' AND timeStart < 'date'
> ```

This is exactly what I want

**Comment by romeerez** [comment]
I'll try to fix this tomorrow, use `whereSql` temporarily instead

**Comment by bingtsingw** [comment]
@romeerez By the way, I'm not quite sure, but `.orWhere` seems not work well with `softDelete`.
`db.xxx.where({a: '1'}).orWhere({a: '2'})` seems to be simply connected with `.where({deletedAt: { not: null }})`

And if `softDelete` has conflict with `orWhere`, `scope` maybe have the same problem

**Comment by romeerez** [comment]
couldn't make it today, but tomorrow will for sure, thank you for finding more and more things to fix here :)

sure, `OR` shouldn't discard the applied scope, so currently `orWhere` breaks soft delete and it's a bug

**Comment by romeerez** [comment]
Published fixes:

- `OR` keyword is now wrapped, the top example should work as expected:
  ```sql
  WHERE (cityId = NULL OR cityId = 'xxxxx') AND state = 'publish' AND timeStart < 'date'
  ```
- The query with `.getOptional('id')` in the end: `get` and `getOptional` were causing troubles to the callback in `where`, now it should be fine
- Scopes, including `softDelete`, now wrapped with parens
  ```sql
  WHERE (deletedAt IS NULL) AND (a = 1 OR b = 2)
  ```
