### ISSUE TITLE
rake-db not pulling snakeCase flag from BaseTable

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#279]
rake-db fails to pull `snakeCase` flag from `BaseTable`:

```ts
const BaseTable = createBaseTable({
  columnTypes: t => ({
    ...t,
    now: () => t.timestamp().default(t.sql`now()`),
  }),
  snakeCase: true,
})

const { change, run } = rakeDb.lazy(
  { databaseURL: config.database.url },
  {
    baseTable: BaseTable, // <--- types are pulled, but snakeCase is not
    basePath: import.meta.url,
    migrationsPath: "./migrations",
    migrations,
    migrationsTable: "rake_migration",
  },
)
```

Related code:

https://github.com/romeerez/orchid-orm/blob/439323184957b152cc27142805fa195b768fe36c/packages/rake-db/src/config.ts#L292-L295

1) `proto.snakeCase` here is always undefined.
2) Note that `proto` is potentially undefined, thus `proto.types` is an unsafe accessor that could crash with null pointer exception. Perhaps it should be `config.baseTable.prototype` not `config.baseTable?.prototype`?

---

Proof:

```ts
import { createBaseTable } from "orchid-orm"

const BaseTable = createBaseTable({
  snakeCase: true,
})

console.log(
  Object.keys(BaseTable.prototype),
  BaseTable.prototype.snakeCase,
)
```

result:

```
% npx tsx server/1.ts
[ 'types' ] undefined
```

* orchid-orm 1.28.5

**Comment by romeerez** [comment]
Thanks for your investigation! Looks quick to fix

2. Probably `?` was to suppress TS complain

**Comment by romeerez** [comment]
Fixed, should be fine.

`createBaseTable`  was missing snakeCase assignment to the prototype
