### ISSUE TITLE
transform in helpers

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#281]
As a developer, I want to create reusable helpers that also utilize transform.

Currently, I have to use repetitive calls around the query:

```ts
export const viewPost = db.post.makeHelper(q => q.select("id", "foo", "bar"))

function transformPost<T extends Partial<Selectable<PostTable>>>(post: T): T {
  if (post.foo && post.bar) {
    post.bar = null
  }
  return post
}

const posts = (await viewPost(db.post.order({ id: "DESC" }).limit(10))).map(transformPost)

const post = transformPost(await viewPost(db.post.find(123))) // becomes more cumbersome with findOptional
```

My naive attempt to reduce this boilerplate was:

```ts
export const viewPost = db.post.makeHelper(
  q => q.select("id", "text").transform(posts => posts.map(transformPost)), // posts typed as ColumnShapeOutput<...>[]
)

...

// Works
const posts = await viewPost(db.post.order({ id: "DESC" }).limit(10))

// Runs transform in the helper with single post, and thus fails to call posts.map
// Return value (const post) is incorrectly typed as ColumnShapeOutput<...>[]
const post = await viewPost(db.post.find(123))
```

Is there a proper method to make a reusable, properly typed helper with transform?

Another option is `afterQuery` but the code is also far from elegant, and it's quite limited (only in-place modifications, no way to extend return type):

```ts
.afterQuery((data) => {
    if (Array.isArray(data)) {
      data.forEach(transformPost)
    } else if (data && typeof data === "object") {
      transformPost(data)
    }
})
```

I was thinking if we could have something like `.transformRow` or something along the lines that would work for plain selects (both single row and multiple rows), but ignore aggregations?

**Comment by romeerez** [comment]
This:

```ts
// Runs transform in the helper with single post, and thus fails to call posts.map
// Return value (const post) is incorrectly typed as ColumnShapeOutput<...>[]
const post = await viewPost(db.post.find(123))
```

doesn't seem correct, and can/should be fixed.

`transformRow` - if it's possible, better to extend `transform` to wrap a single record to array, transform it with your code, and pick the first record before returning if it's for `find`.

**Comment by romeerez** [comment]
I added a new method `map` ([docs](https://orchid-orm.netlify.app/guide/query-methods.html#map)) for this purpose.

Now this should be fine:

```ts
export const viewPost = db.post.makeHelper(
  q => q.select("id", "text").map(transformPost),
)
```

In both single and multiple records cases, `map` will pass only a single record to your function.

**Comment by IlyaSemenov** [comment]
Thanks! Worked like charm, and very intuitive to use.

Question by the way, could the map also be async? Or maybe add `.asyncMap()` alongside? In a way, this is half-way helping with #270 (JS-computed columns) already.

I don't personally have a direct need for this right now, just thinking ahead.

**Comment by romeerez** [comment]
It's not hard to add `await` into the `map` handling, but it's a way to N+1 problem.

If you load 100 records and have an async map that runs for every record, why is it async? It probably loads something. So it would be 1 query + 100 loads, not good.
