### ISSUE TITLE
Exclude onConflict column in merge

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#282]
```ts
await db.post.create({ id, data }).onConflict("id").merge()
```

generates:

```
INSERT INTO "post"("id", "data") VALUES ($1, $2) ON CONFLICT ("id") DO UPDATE 
  SET "id" = excluded."id", "data" = excluded."data" RETURNING "id", "create_time" AS "createTime", "data"
```

I believe there is no point in doing UPDATE on the conflicting fields? The query could be reduced to:

```
INSERT INTO "post"("id", "data") VALUES ($1, $2) ON CONFLICT ("id") DO UPDATE
  SET "data" = excluded."data" RETURNING "id", "create_time" AS "createTime", "data"
```

The only problem I see is when the update is only performed on the keys (i.e. `await db.post.create({ id }).onConflict("id").merge()`). Thoughts?

**Comment by romeerez** [comment]
Published, now `onConflict`ed columns will be excluded from the merge, and it will `DO NOTHING` when all are excluded.
