### ISSUE TITLE
Getting error in PostgreSQL version 16.

### ISSUE THREAD

**Issue by JAYBORICHA07** [romeerez/orchid-orm#284]
I am using orchidORM and while generating migration files i am getting error of missing column "colliculocale".

**Comment by romeerez** [comment]
I'm also using 16 and didn't encounter this.

Do you have any clues of what non-standard collation-related things may be in your db?

What command do you run?

Would you be able to hang me your database dump (structure only)?

**Comment by JAYBORICHA07** [comment]
> I'm also using 16 and didn't encounter this.
> 
> Do you have any clues of what non-standard collation-related things may be in your db?
> 
> What command do you run?
> 
> Would you be able to hand me your database dump (structure only)?


It fixed automatically I think the problem was with some code 

i am closing the issue thanks
