### ISSUE TITLE
jsonSet update for untyped json field gives type error 

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#286]
If a table JSON field is untyped (or typed as `any`), update with `jsonSet` will give typing error:

```ts
class PostTable extends BaseTable {
  readonly table = "post"

  columns = this.setColumns(t => ({
    id: t.serial().primaryKey(),
    data: t.json(), // <--- Untyped json field
  }))
}

await db.post.find(1).update({
  // Error: Parameter 'q' implicitly has an 'any' type.
  data: q => q.jsonSet("data", ["foo"], "FOO"),
})
```

Providing any concrete type, even `t.json<number>()`, removes the error.

In my thinking, using subqueries for JSON fields should always be allowed.

- orchid-orm 1.28.11
- typescript 5.3.3

**Comment by romeerez** [comment]
Fixed, published update.

JSON data of type `any` conflicted with the callback, so the query builder couldn't guess if `q => q.jsonSet` is a callback or a JSON data, so now `t.json` will have type `MaybeArray<boolean | string | number | Record<string, unknown>>` by default.
