### ISSUE TITLE
createMany fails on more than 64K placeholders

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#288]
`createMany` fails on more than 64K placeholders:

```ts
// works
await db.post.createMany(Array.from({ length: 65535 }, () => ({ text: "foo" })))

// error: bind message supplies 0 parameters, but prepared statement "" requires 65536
await db.post.createMany(Array.from({ length: 65536 }, () => ({ text: "foo" })))
```

- orchid-orm 1.28.11
- pg 8.12.0

Perhaps it's not ORM business to do the chunking but I think there could be a 'heads up' note in the documentation with some kind of recipe, e.g.:

```ts
import * as r from "rambda"

const data = Array.from({ length: 100000 }, () => ({ text: "foo" }))

await db.$transaction(async () => {
  for (const chunk of r.splitEvery(1000, data)) {
    await db.post.createMany(chunk)
  }
})
```

(or may be some smarter way to run the promise map sequentially).

**Comment by romeerez** [comment]
Published an update for this,  and updated docs for [createMany](https://orchid-orm.netlify.app/guide/create-update-delete.html#createmany-insertmany).

Now this query should work, internally it will track the count of parameters, and when it exceeds 65535, the insert will be batched into multiple queries.

Multiple inserts are wrapped into a transaction unless it's already in a transaction.

**Comment by IlyaSemenov** [comment]
Great, thanks! I think you missed a word in the docs:

> Because of a limitation of Postgres protocol, queries having more than 65536 are going to fail in runtime.

more than 65536 _of what?_

(also, it's more than 65535 to be precise, sorry for the nit-picking lol)

**Comment by romeerez** [comment]
It's easy to fix, so nit-picking is welcome!
