### ISSUE TITLE
timestamp dont work when snake cases are true

### ISSUE THREAD

**Issue by KMJ-007** [romeerez/orchid-orm#289]
<img width="1407" alt="image" src="https://github.com/romeerez/orchid-orm/assets/86996507/efe5489a-60bb-431d-a6b4-44a05d0384be">

my schema:

```ts
export class UsersTable extends BaseTable {
  readonly table = "users";
  columns = this.setColumns((t) => ({
    email: t.text().email().primaryKey(),
    name: t.text(),

    ...t.timestamps(),
  }));
  relations = {
    userOcJt: this.hasMany(() => UserOcJtTable, {
      nullable: false,
      columns: ["email"],
      references: ["userEmail"],
    }),
    ownercompany: this.hasMany(() => OwnercompanyTable, {
      through: "userOcJt",
      source: "ownercompany",
    }),
  };
}

```

BaseTable:

```ts
export const BaseTable = createBaseTable({
  schemaConfig: zodSchemaConfig,
  snakeCase: true,
  columnTypes: (t) => ({
    ...t,
    autoId: () => t.identity().primaryKey(),
    text: () => t.text(0, Infinity),
    // enums
    applicationStatusEnum: () =>
      t
        .enum("application_status", ["pending", "approved", "rejected"])
        .default("pending"),
    reapplicationStatusEnum: () =>
      t
        .enum("reapplication_status", ["na", "allowed", "reapplied"])
        .default("na"),
  }),
});

```

migration command i ran:

```bash
nr db g init
```

**Comment by IlyaSemenov** [comment]
Try upgrading rake-db. You're using 2.20.17, and there have been a couple snake-case related fixes after that: https://github.com/romeerez/orchid-orm/blob/06ea6addceb515d9327af8185663520238644121/packages/rake-db/CHANGELOG.md?plain=1#L40-L50

**Comment by romeerez** [comment]
The issue indeed is related to an outdated version, because `timetampsSnakeCase` from the error log does not exist anymore and isn't used anywhere internally.

Make sure that `rakeDb` is imported from `orchid-orm/migrations`, remove `rake-db` from package.json if it exists, update the `orchid-orm` and `orchid-orm-schema-to-zod` packages.
