### ISSUE TITLE
`findBy` do not support `join`

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#292]
In older versions, this work:
```
await db.projectToken.join('project').findByOptional({ xxx: 'xxx', 'project.id': 'projectId' })
```

But in the latest version(1.28.14), it throws an ts error
<img width="411" alt="image" src="https://github.com/romeerez/orchid-orm/assets/10382462/969107ad-8f83-4717-8b43-949f2147c230">

**Comment by romeerez** [comment]
Indeed, `findBy` and `findByOptional` were changed to only support unique columns, to prevent situations when you're only querying the first record without realizing that there are many such records.

And it's a bug that `findByOptional` isn't yet aware of joined unique columns, so if `project.appid` is unique it should work. I'll fix this.

And if `project.appid` isn't unique, you can do:

```ts
const token = await db.projectToken
  .join('project')
  .where({ 'project.appid': appid })
  .findByOptional({ ak })
  .select(...)
```

**Comment by bingtsingw** [comment]
Yes, `appid` is `unique`, seems to be a bug

**Comment by romeerez** [comment]
It's too much work to support joined unique columns in `findBy(Optional)`, because `join` can take various forms of arguments and it would be very cumbersome to obtain unique columns from each of the forms + filter them out based on if the `join` has a sub-query with select, so I'm going to won't fix it.

You can achieve the same by using `where` as in my example above, also with:

```ts
const token = await db.projectToken
  .join((q) => q.project.where({ appid }))
  .findByOptional({ ak })
  .select(...)
```

Or:

```ts
const token = await db.projectToken
  .join('project', (q) => q.where({ appid }))
  .findByOptional({ ak })
  .select(...)
```

**Comment by bingtsingw** [comment]
`findBy` only support unique columns is much cleaner, I'm in favour of this change, but I have lots of old `findBy` statements which do not meet this rule.
How can I easily migrate them equivalently.
`.findBy({ a: 'xx', b: 'xxx' })` -> `.where({ a: 'xx', b: 'xxx' }).take()` or `.where({ b: 'xxx' }).findBy({ a: 'xx' })`

**Comment by romeerez** [comment]
> How can I easily migrate them equivalently.
> .findBy({ a: 'xx', b: 'xxx' }) -> .where({ a: 'xx', b: 'xxx' }).take() or .where({ b: 'xxx' }).findBy({ a: 'xx' })

Yes, right, either `where(...).take()` or `where(...).takeOptional()`, or `where` for non-unique + `findBy` for unique columns.

**Comment by romeerez** [comment]
There will be a breaking change for `jsonSet` and similar methods soon, btw

**Comment by bingtsingw** [comment]
I totally accept breaking changes, I'll wait several versions util stable and then update my applications in one time.
