### ISSUE TITLE
Facing relation doesnt exist error in one machine

### ISSUE THREAD

**Issue by krishna-404** [romeerez/orchid-orm#294]
Have been facing a weird error. The same code is running in other machines but my machine is throwing this error when ever we are trying to do any kind of query.

<img width="479" alt="image" src="https://github.com/romeerez/orchid-orm/assets/62951687/ae059506-593f-4dfa-b9bb-9b1a42b2f3bf">

Node version @ 18.x & PostgreSQL version @ 15. Which is the same as other machines.

**Comment by romeerez** [comment]
The error says that relation (table) "ownercompany" does not exist.

The config shows that it's a `b2b_sales_rep_test` db - perhaps it's a separate db for tests. So maybe you didn't run migrations for this db.

Are you sure you executed migrations?

**Comment by krishna-404** [comment]
Thanks! It was a rookie mistake in config. 😓
