### ISSUE TITLE
Deprecate legacy HasAndBelongsToManyOptions

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#297]
I was just investigating why `tsc --noEmit` was crashing with stack limit exceeded and traced it to my m2m models using the old `associationForeignKey` syntax:

https://github.com/romeerez/orchid-orm/blob/c2325a8d80424faa5065bf19271bda0b6a123f48/packages/orm/src/relations/hasAndBelongsToMany.ts#L81-L87

which worked in runtime and didn't trigger type errors in IDE.

[Updating](https://github.com/IlyaSemenov/graphql-orm/commit/09c1fc3a2fa5011ce002edf17da8f4d86a97ed61) the code to use the new syntax with separate `through` object finally fixed `tsc` crashes.

The old syntax is not even documented anymore: https://orchid-orm.netlify.app/guide/relations.html#hasandbelongstomany. May be it's time to deprecate (or obsolete) it?

**Comment by romeerez** [comment]
I removed from docs quote a long time ago (maybe half a year or so), as well as removed primaryKey + foreignKey for other kinds of relations.

Deprecated warnings using `/** @deprecate **/` comment don't work here for some reason, get lost in a complex typing.

It's surprising that the old version loads TS harder than the new one, bc the old was for a single key, and the newer supports multiple keys. But removing typings for the old way going to help TS to do a bit less work.

So I'm going to remove primaryKey+foreignKey options for all kinds of relations.

**Comment by romeerez** [comment]
Done, dropped the old options
