### ISSUE TITLE
Generate command applies previously unapplied migrations to DB

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#298]
I'm not sure if this is a bug or intentional, but I created 2 migrations one after the other:

```
npm run db g myMigration1

 ... some schema changes

npm run db g myMigration2
```

as soon as I ran the 2nd command I saw the first was applied to the database without me first calling `npm run db migrate`.

**Comment by romeerez** [comment]
It's intentional, because otherwise you could get migrations with the same actions in them, it would fail and confuse.

I added a line about this to the docs (will be deployed later).
