### ISSUE TITLE
db.table.where() not setting returnType

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#299]
TL;DR —

```ts
const t1 = db.post.all().where().returnType // typeof t1 is "all"
const t2 = db.post.where().returnType // typeof t2 is QueryReturnType
```

Expected: both `t1` and `t2` typed as `"all"`.

---

For the GraphQL resolver that I'm working on, I want to provide users a generic function that accepts the return type and the query argument. I want to do very basic type check on the query, so that if say the return type is a list, the query should be also returning the list (i.e. it's not `.find()` or `.get()` or `.count()`).

I came up with this quick approach:

```ts
import process from "node:process"

import { createBaseTable, orchidORM, Query } from "orchid-orm"

const BaseTable = createBaseTable()

class PostTable extends BaseTable {
  readonly table = "post"

  columns = this.setColumns((t) => ({
    id: t.serial().primaryKey(),
    text: t.text(),
  }))
}

const db = orchidORM(
  { databaseURL: process.env.DATABASE_URL, log: true },
  {
    post: PostTable,
  },
)

// Similar to db.post, but not necessary so.
interface Post {
  id: number
  text: number
  excerpt: string
  tags: string[]
}

// Query must restrict the return type shape.
function myResolve<T>(
  query: Query & {
    returnType: T extends Array<unknown>
      ? "all" | "rows"
      : T extends undefined
        ? "one"
        : "oneOrThrow"
  },
): Promise<T> {
  return query as unknown as Promise<T>
}

// These all should return type errors:
myResolve<Post>(db.post.all())
myResolve<Post>(db.post.count())
myResolve<Post>(db.post.get("text"))
myResolve<Post>(db.post.findOptional(1))
myResolve<Post[]>(db.post.find(1))

// These should be accepted:
myResolve<Post[]>(db.post.all())
myResolve<Post[]>(db.post.where({ text: "foo" }))
myResolve<Post>(db.post.find(1))
myResolve<Post | undefined>(db.post.findOptional(1))
```

which mostly works but gives false negative for `db.post.where()`.

**Comment by romeerez** [comment]
I'm relying on this helper from pqb:

```ts
export type QueryReturnsAll<T extends QueryReturnType> =
  QueryReturnType extends T ? true : T extends 'all' ? true : false;
```

`db.post.all()` and `db.post` return types are different to let the ORM know if `all()` was applied.

Because `update` and `delete` needs to know if it was applied or not.

**Comment by IlyaSemenov** [comment]
Right, I though so. But what if `db.post` will have some different type like `list` by default? The current way of things is a bit inconsistent. `db.post.where()` is well defined from user point of view (it always returns a list), but it's not precisely typed as other queries (based on typings, it supposedly could return one or void or anything else).

--

As for the helper, thanks for providing it, but I am struggling to see how I can "reverse" it. In my case, I don't need to check query, I need to build a type for the query. I can't really return `Query & { returnType: QueryReturnType }`, can I? Because it will pass anything.

**Comment by romeerez** [comment]
Having `list` by default sounds good, I'd call it `many` to be more symmetrical with the existing `one`, and it should solve the typing problem.

Well, since the default one is `QueryReturnType`, and by coincidence it is a union of all possible values, seems like you cannot restrict it so `db.post.where()` is going to pass while `db.post.take()` won't pass.

**Comment by romeerez** [comment]
Done, now it's `undefined` by default, both at runtime and at the type level.

Use

```ts
returnType: undefined | 'all'
```

to limit queries to return multiple records.

**Comment by IlyaSemenov** [comment]
Thanks! I confirm that in the example above,

```ts
function myResolve<T>(
  query: Query & {
    returnType: T extends Array<unknown>
      ? undefined | "all"
      : T extends undefined
        ? "one"
        : "oneOrThrow"
  },
)
```

works as expected with orchid-orm 1.31.2.
