### ISSUE TITLE
Composite uniques

### ISSUE THREAD

**Issue by quinnvaughn** [romeerez/orchid-orm#30]
Is there a way to do composite uniques like this from Prisma? Or does that need to get built out?

```
model Post {
  id         Int        @id @default(autoincrement())
  createdAt  DateTime   @default(now())
  title      String
  published  Boolean    @default(false)
  author     User       @relation(fields: [authorId], references: [id])
  authorId   Int
  categories Category[] @relation(references: [id])

  @@unique([authorId, title])
}
```

**Comment by romeerez** [comment]
Here is an example of composite unique in a migration: https://orchid-orm.netlify.app/guide/migration-column-methods.html#composite-unique-index

The same syntax can be used in a table definition, just as a highlight that the table has it, but it has effect only in a migration

**Comment by romeerez** [comment]
Hi @krishna-404, yea I should improve docs and will do so eventually, for now I hope this example may help: https://orchid-orm.netlify.app/guide/orm-and-query-builder.html#define-a-table-class

I has composite primary key, indexes, foreign key and such
