### ISSUE TITLE
Log queries inside transaction

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#303]
Currently, query logging can be enabled either globally, or for an individual query.

I propose to allow enabling logging for a transaction:

```ts
// log all queries from BEGIN to COMMIT
await db.$transaction({ log: true }, async () => {
  await db.post.find(id).forUpdate()
  await db.post.find(id).update({ foo: true })
})
```

**Comment by romeerez** [comment]
No problem, but what's the use case?

**Comment by romeerez** [comment]
Actually, may be problematic.

The global log is propagated to query objects, so there is only a single boolean.
You're proposing to add a second boolean to the transaction context.

And you'd expect that transaction's boolean takes precedence over the global one, but individual's query log value should take precedence over the transaction's one.

So in the end need to keep track of 3 booleans: global, transaction, and per-query.

It's code complication and additional runtime checks, do you think it's worth it?

**Comment by IlyaSemenov** [comment]
> No problem, but what's the use case?

It's basically the same purpose as `.log()` for a single query, to debug a part (execution branch) of code. If I enable the log globally, the log is polluted with irrelevant queries coming from background tasks.

I thought it's a matter of a new thread local variable and one or two additional if's, which seemed to have negligible impact both from runtime and code base points of view. If that's not so, then of course it's not something very important to have.

**Comment by romeerez** [comment]
Done and published.

> log all queries from BEGIN to COMMIT

BEGIN and COMMIT are included.

Transaction `log: true` will take a precedence over query's `log(true)`, otherwise it would be complicated and I believe this won't be a problem.
