### ISSUE TITLE
updateSchema() not available

### ISSUE THREAD

**Issue by minkoonim** [romeerez/orchid-orm#305]
from doc:
![image](https://github.com/romeerez/orchid-orm/assets/38183949/8ee5dcad-c367-4367-a43c-3522a0b078c1)

from type hints:
![image](https://github.com/romeerez/orchid-orm/assets/38183949/aea419e4-cc55-4d48-9367-8d87884b3c0d)

**Comment by romeerez** [comment]
I guess I removed the `updateSchema` if favor of `inputSchema().partial()`, I'll update the docs.

**Comment by minkoonim** [comment]
To my understanding,
InputSchema, UpdateSchema, and QuerySchema should be as follows:

1. The InputSchema object should have required fields like the primary key as required, and other nullable fields should be optional.

2. The UpdateSchema object should have the primary key as required, and all other fields should be optional.

3. The QuerySchema object should have all fields optional.

but I see that QuerySchema currently has all fields required

**Comment by romeerez** [comment]
I published an update:

- `inputSchema`: it serves as a base for other schemas, all fields are required (field can be nullable, but required).

- `createSchema`, a new one: primary keys are omitted, nullable fields are optional - non-required.

- `updateSchema`: primary keys are omitted, the rest are optional. If you'd prefer to have primary keys required here, I think it's not a common case, you can do `Table.updateSchema().merge(Table.primaryKeys())`.

- `querySchema`: made it partial.

- `outputSchema`, `pkeySchema` not changed.

**Comment by minkoonim** [comment]
Thanks man!!!!!!!
