### ISSUE TITLE
types broken when selecting '*' with foreign object

### ISSUE THREAD

**Issue by minkoonim** [romeerez/orchid-orm#306]
1.
```
db.table.select('*') // typed correctly 🟢 
```
![image](https://github.com/romeerez/orchid-orm/assets/38183949/f5f8fdc6-9cbd-4389-b7d3-2f59310781f1)

2.
```
db.table.select('*', someForeignObject: (q) => q.foreignObject) // types go "never" ❌ 
```
![image](https://github.com/romeerez/orchid-orm/assets/38183949/a406dd45-cf3c-489a-9eea-1fdcd870211e)

3. 
```
db.table.select('explicit', 'field', 'names', someForeignObject: (q) => q.foreignObject) // typed correctly 🟢 
```
![image](https://github.com/romeerez/orchid-orm/assets/38183949/c84b2dae-6f3e-4381-a950-7a3f68ab2ab5)

**Comment by IlyaSemenov** [comment]
> `db.table.select('*', someForeignObject: (q) => q.foreignObject) // types go "never" ❌ `

This is invalid Typescript, it won't even compile. Please paste the actual code you're writing.

This should work:

```ts
db.table.select('*', { someForeignObject: (q) => q.foreignObject })
```

If it doesn't, please paste your respective table definitions.

**Comment by minkoonim** [comment]
my bad  @IlyaSemenov 
it seems to be working fine now
