### ISSUE TITLE
Select * get's wrong types

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#310]
I'm trying to query all fields of a table but also relations, so I do the following:

```ts
await db.myTable
    .select('*', {
        relation: q => q.relation
    })
```

Unfortunately, all fields except the relation get the `never` type.

**Comment by romeerez** [comment]
This works fine on my end, so please share the tables code for reproducing.

Make sure `strict` is set to true in the tsconfig.

**Comment by mordechaim** [comment]
[Here you go](https://github.com/mordechaim/orchid-repro)

Check out the types in index.ts

**Comment by romeerez** [comment]
I'm very grateful that you found it, and I see what's wrong with it, I did typing optimizations recently and simply missed some stuff, it should be quick to fix.

**Comment by romeerez** [comment]
I published a fix, must be fine now.
