### ISSUE TITLE
[bug] update json subquery error

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#311]
`"orchid-orm": "1.32.6"`

I update the json field like this in the doc(https://orchid-orm.netlify.app/guide/json.html#jsonset), but it show an ts error:
<img width="896" alt="image" src="https://github.com/romeerez/orchid-orm/assets/10382462/5a6078b0-8ef5-42e3-8bb6-ceaca6c9f806">

**Comment by romeerez** [comment]
Could you make a reproduction?

For me the similar query with updating json with `jsonSet` works normally.

**Comment by bingtsingw** [comment]
https://github.com/bingtsingw/orchid-reproduction

The test passed, but `q` has a type error

**Comment by romeerez** [comment]
Thanks, I found that it's `any` only when the table has no relations.

**Comment by romeerez** [comment]
Published a fix, ready.
