### ISSUE TITLE
Creating new record returns timestamps as string, unless it includes relations

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#317]
A weird typing bug: When I create a new record using:

```ts
await db.test.create({})
```

The resulting timestamps are returned as `string`s. But interestingly, if the table declaration has the `relations` property, it will return the timestamps as `Date`.

The workaround is to use `selectAll()`

```ts
await db.test.create({}).selectAll()
```

which will return the timestamps as dates.

Reproduction: https://github.com/mordechaim/orchid-dates

**Comment by romeerez** [comment]
Weird, but for me your reproduction outputs Date objects:

![image](https://github.com/romeerez/orchid-orm/assets/42248135/315479e7-1de3-443c-8147-90c6bfa55622)

steps:
- cloned, installed
- created db
- `npm run db g` tried to generate migration, but it errored with a reminder to add a primary key
- added a primary key, and `npm run db g`, applied migration with `npm run db up`
-added script `"start": "tsx ./index.ts"` to run the file
- added console.logs to index
- `npm start` - shows dates in purple, that means they are both object dates
