### ISSUE TITLE
Breaking migration changes

### ISSUE THREAD

**Issue by quinnvaughn** [romeerez/orchid-orm#32]
So is it just me or were there breaking changes on migrations that aren't actually built out yet and make no reference in the docs? 

timestamps does this
```
createdAt: t.timestamp().default('now()', undefined),
    updatedAt: t
      .timestamp()
      .default('now()', undefined)
      .modifyQuery((q) => {
        orchidCore.pushOrNewArrayToObject(q.query, 'updateData', updatedAtInjector)
      }),
```

There's no mention of orchid core anywhere in the docs, I see it's a new package, but it's not like it's imported automatically on a migration, and when I did try to, 'updateData' wasn't even an option. They also throw an error on undefined, as it's expecting one arg, as well as 'now()' because it's expecting orchidCore.raw('now()') so there's a lot going on here haha

**Comment by quinnvaughn** [comment]
It's easy enough to change it to just `...t.timestamps()` and call it a day, but this seems a huge amount of new functionality added that doesn't actually work.

**Comment by quinnvaughn** [comment]
Can't seem to repeat this now, so closing.

**Comment by romeerez** [comment]
`orchid-core` is an internal package that other packages depend on, so it isn't mentioned in the docs as it's installed automatically as a dependency.

I don't understand what the problem is. I'm glad it's solved, feel free to reopen it if something is not right.

**Comment by romeerez** [comment]
I found this `t.timestamp().default('now()', undefined)` bug when running `db pull`, fixing
