### ISSUE TITLE
SQL computed field based on relation

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#321]
Say I'm trying to add a computed field that is based on a value from a relational table. Traditionally I'd reference the column with a join, but how would I do it with `q` object used inside `this.setComputed()`?

**Comment by romeerez** [comment]
It's not supported currently, but I guess, theoretically, this can be implemented. And I'm not sure if it's worth it.

Imagine you're joining "things" in the computed field. And later in the code you're joining "things" again, but with some extra conditions.

Should the computed be affected by extra conditions or not? I think it depends, and this feature may lead to unexpected results, and it won't be obvious that something isn't working as intended.

**Comment by mordechaim** [comment]
I get it, ok never mind then.

**Comment by romeerez** [comment]
What is your specific use-case? Maybe we can fine other ways.

If you want to do an aggregation, such as using count of comments for a post in a computed field, I have one feature in mind that I've been delaying for years but wanted to add from the beginning.

**Comment by mordechaim** [comment]
I'm trying some basic string concatenation from a column value plus a column in the relation, but can make it work without.
