### ISSUE TITLE
transient flag for database connection

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#323]
I propose to add a new connection flag:

```ts
const db = orchidORM(
  {
    databaseURL: process.env.DATABASE_URL,
    // start transaction on first query and rollback on close
    transient: true
  },
  {
    post: PostTable,
  },
)

await db.post.insert({ text: "foo" })
```

being essentially a shortcut for:

```ts
const db = orchidORM(
  { databaseURL: process.env.DATABASE_URL },
  {
    post: PostTable,
  },
)

await testTransaction.start(db)

await db.post.insert({ text: "foo" })

await testTransaction.close(db)
```

The use case is using in tests and simplifying smaller reproductions (such as #320).

This is by far not important, but if that's something that you generally approve, it could be in the backlog of the project.

**Comment by romeerez** [comment]
When using in tests, you control the transaction from `beforeAll`, `beforeEach` and similar hooks, like Bingtsingw does in [their reproductions](https://github.com/bingtsingw/orchid-reproduction/blob/main/src/issue-311/test-setup.ts).

So the `transient` option you're proposing won't be useful for tests.

And for such a brief code same, I think that having to explicitly call `testTransaction.start` and `testTransaction.close` isn't enough boilerplate to DRY it with a special connection option.

I'm all for simplifying and reducing boilerplates, but in this case that code looks fine by me.
