### ISSUE TITLE
'jsonPath' does not exist in type 

### ISSUE THREAD

**Issue by KenjiGinjo** [romeerez/orchid-orm#326]
<img width="589" alt="image" src="https://github.com/user-attachments/assets/d1bbc74b-b3f8-4eff-8560-c9697d431229">

https://orchid-orm.netlify.app/guide/where.html#jsonb-column-operators
https://orchid-orm.netlify.app/guide/columns-types.html#json

Is the jsonPath operator available for use?

**Comment by romeerez** [comment]
It was renamed to `jsonPathQueryFirst`  because it relies on pg's [json_path_query_first](https://www.postgresqltutorial.com/postgresql-json-functions/postgresql-jsonb_path_query_first/) - uses a JSON query and takes the first occurrence.

And the usage has changed:

```ts
db.table.where((q) =>
  q.get('jsonbColumn').jsonPathQueryFirst('$.name').equals(value),
);
```

I have updated docs.

**Comment by KenjiGinjo** [comment]
```
q.get('profile').jsonPathQueryFirst('$.name').equals(_keyword);
// I have another question about ILIKE. Does it mean the same as equals? Or does jsonPathQueryFirst have another method for ILIKE queries?
```
```
q.where(
          raw({
            raw: `("user"."profile"->>'name')::text ILIKE $keyword`,
            values: { keyword: `%${_keyword}%` },
          }),
        );
```

**Comment by KenjiGinjo** [comment]
> It was renamed to `jsonPathQueryFirst` because it relies on pg's [json_path_query_first](https://www.postgresqltutorial.com/postgresql-json-functions/postgresql-jsonb_path_query_first/) - uses a JSON query and takes the first occurrence.
> 
> And the usage has changed:
> 
> ```ts
> db.table.where((q) =>
>   q.get('jsonbColumn').jsonPathQueryFirst('$.name').equals(value),
> );
> ```
> 
> I have updated docs.

I have another question about ILIKE. Does it mean the same as equals? Or does jsonPathQueryFirst have another method for ILIKE queries?

```
q.get('profile').jsonPathQueryFirst('$.name').equals(_keyword);
```
```
//  For now, I write for this situation
q.where(
      raw({
        raw: `("user"."profile"->>'name')::text ILIKE $keyword`,
        values: { keyword: `%${_keyword}%` },
      }),
);
```

**Comment by romeerez** [comment]
Related issue: https://github.com/romeerez/orchid-orm/issues/342
