### ISSUE TITLE
Where query on connections

### ISSUE THREAD

**Issue by quinnvaughn** [romeerez/orchid-orm#33]
If I had a schema where I had a post and I wanted to check if the title of the post equals some text string, or the content of a comment had some specific text, how would I go about doing that? This is not my _actual_ use case and it's a bit of a convoluted example, but basically I want to also check a where on a connection, but the connection does not appear as an option in the query.

Here's a basic example of this kind of code in MikroORM for comparison

```
      $or: [
               { title: { $like: likeText } },
               { description: { $like: likeText } },
               { comments: { $or: [{ title: { $like: likeText } }, { content: { $like: likeText } }] } },
            ],
```

And I want to do the equivalent. However, the "comments" part does not show up and I'm trying to figure out how. The closest thing I've seen in the documentation is only in regards to select, which _does_ do this same thing.

**Comment by quinnvaughn** [comment]
This is the closest thing I've seen in the select.

```
await db.post
            .select('id', 'title', 'description', {
              author: (q) => q.author.select('id', 'firstName', 'lastName'),
              tags: (q) => q.postTags.pluck('tagName'),
              lastComments: (q) =>
                q.comments
                  .select('id', 'text', {
                    author: (q) =>
                      q.author.select('id', 'firstName', 'lastName'),
                  })
                  .order({ createdAt: 'DESC' })
                  .limit(commentsPerPost),
            })
            .order({ createdAt: 'DESC' });
```

**Comment by romeerez** [comment]
You can use [whereExists](https://orchid-orm.netlify.app/guide/query-builder-where.html#whereexists-orwhereexists-wherenotexists-orwherenotexists) (also there are `orWhereExists`, `whereNotExists`, `orWhereNotExists`):

```ts
const posts = await db.post
  .where({ title: { contains: 'x' } })
  .or({ description: { contains: 'x' } })
  .orWhereExists('comments', (q) =>
    q.where({ title: { contains: 'x' } }).or({ content: { contains: 'x' } })
  );
```

`contains` is using `ILIKE` and will add '%' to the beginning and the end of a string, [here are the docs](https://orchid-orm.netlify.app/guide/query-builder-where.html#text-column-operators) for it.

`select ` will *not* add where conditions, it is only selecting data. So with `select` you can select post comments filtered by title, but this won't filter posts. To filter posts by comments use `whereExists`, I'll try to make it more convenient in the future, but for now that's it.
