### ISSUE TITLE
The latest version seems broke `computed columns`

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#330]
After I upgrade from `1.32.16` to `1.32.18`, computed columns' behaviors changed.

My old code, `as` column name can be completed automatically
```
public computed = this.setComputed((q) => ({
  verificationVerified: q.sql`${q.column('verification')} -> 'verified' as`.type((t) =>
    t.boolean(),
  ),
}));
```

In `1.32.18`, if I query like this: `db.user.find(xxx).get('verificationVerified')`, it throws sql error, the generated sql is `SELECT "user"."verification" -> 'verified' as FROM "user" WHERE "user"."id" = $1 LIMIT 1 ['xxxxx']`
`db.user.find(xxx).select('verificationVerified')` does not throw error but returns unexpected value.

If I change source code to this:
```
public computed = this.setComputed((q) => ({
  verificationVerified: q.sql`${q.column('verification')} -> 'verified' as verificationVerified`.type((t) =>
    t.boolean(),
  ),
}));
```

`.get()` works but `.select()` throws error

**Comment by romeerez** [comment]
Yes, column is no longer aliased in `get` to fix the previous error with `jsonSet`.

Try removing `as` completely:

```ts
public computed = this.setComputed((q) => ({
  verificationVerified: q.sql`${q.column('verification')} -> 'verified'`.type((t) =>
    t.boolean(),
  ),
}));
```

Does it help?

**Comment by bingtsingw** [comment]
Removing `as` seems do the work
