### ISSUE TITLE
varchar without limit

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#331]
With orchid 1.30, it's no more possible to create create varchar columns without limit. That makes it impossible to support databases created with pre-1.30 orchid-orm. The migrations are broken and even if all `column: t.varchar()` are replaced with `column: t.varchar(255)` or `column: t.text()` this is not an equivalent change, creating different db schema on db reset/redo.

I believe it should be possible to at least have something like `t.varchar(null)` or `t.varchar(Number.POSITIVE_INFINITY)` possible. A varchar without a limit is perfectly valid Postgres construct, there is no reason to completely ban it in orchid-orm. I realise and possibly concur the decisions about having limit a required field for varchar; however, there should be an escape hatch for cases when a database column should really be a varchar without limit, such as — but not limited to — legacy projects.

**Comment by romeerez** [comment]
On one hand, it doesn't feel right to have `varchar` and `text` serving the same purpose under different names.
On other hand, legacy projects, people's preferences.

`Number.POSITIVE_INFINITY === Infinity`, I'm leaning towards `t.varchar(Infinity)` to be a compromise.

**Comment by romeerez** [comment]
As a temp workaround, you can try `t.varchar('' as never)`.

I landed a job not so long ago and can't code ORM during working days, and I have some special plans for the next weekends, so this issue can stuck for awhile, as well as the following ones.

**Comment by IlyaSemenov** [comment]
Sure thing, no pressure intended at all. I'm just adding issues as I see them.

As for the workaround, unfortunately, it doesn't work. It generates:

```sql
CREATE TABLE "user" (
  "id" uuid PRIMARY KEY,
  "name" varchar() NOT NULL
)
```

which gives:

```
Error: syntax error at or near ")"
```

**Comment by romeerez** [comment]
I published an update: now `varchar` is simply allowed without limit, and it's no longer ORM business whether you use text or varchar type for unlimited text.
