### ISSUE TITLE
Automatically create foreign keys?

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#332]
I noticed that defining `relations` does not add any foreign keys to enforce relation stability. I am still required to add `foreignKey()` to the relation column definition.

But since we already define the relation in the `relations`, wouldn't automatically adding a foreign key be helpful? This is a breaking change so I'm not asking you to make this the default, but maybe I'm missing something obvious here?

**Comment by bingtsingw** [comment]
`relations` is an `application layer` function which provider ORM the ability to query with relations, `foreignKey()` is an `database layer` function which alter database field. There are many cases your application layer is not the same with database layer, for example `Polymorphic Association`.
In fact, `foreignKey` is only an implementation of `relations`.

So, I don't think adding foreign keys automatically is a good idea.

**Comment by mordechaim** [comment]
I hear your point, but `relations` isn't purely application layer. For instance, [hasAndBelongsToMany](https://orchid-orm.netlify.app/guide/relations.html#hasandbelongstomany) has the `through` parameter which allows you to create a middle table.

So while I understand this shouldn't be a default, I believe we could probably add a `foreignKey: true` option.

I'm not asserting this is the correct approach, I was just not seeing any reference about foreign keys in the docs so I feared that I missed something obvious.

**Comment by bingtsingw** [comment]
That's a good point, I didn't expect it.

**Comment by romeerez** [comment]
I think it would be a nice additional feature. In general, it's always better to have a foreign key. But they add some overhead on db level, and in some cases when striving for max performance you might want to skip them.

I could add `foreignKey: true` to `belongsTo` and to `hasAndBelongsToMany` to be a bit shorter then defining them on columns, and also there could be a global `autoForeignKey: true` option to enable this for all tables.

But let it have a lower priority then other planned things and new bugs, so won't be added soon.

**Comment by romeerez** [comment]
Ready: now you can add `autoForeignKeys: true` to the base table config, and foreign keys are going to be created automatically. With ability to turn it of or customize for specific tables.

[docs](https://orchid-orm.netlify.app/guide/orm-and-query-builder.html#autoforeignkeys)
