### ISSUE TITLE
SnakeCase  Problem

### ISSUE THREAD

**Issue by KenjiGinjo** [romeerez/orchid-orm#333]
https://github.com/KenjiGinjo/orchid-reproduction/tree/K_333

**Comment by romeerez** [comment]
There are two problems here:

1. Incorrect SQL in `whereExists` indirectly caused by `softDelete`
  ```ts
  await db.activity.whereExists('members', (q) => q.where({ name: 'test' }));
  ```
  
2. Snake case problem caused by `on` bug.

I published a fix for the first one, and going to make a fix for the second one a bit later.

**Comment by KenjiGinjo** [comment]
It's ok now.

**Comment by romeerez** [comment]
nope, the snake case problem isn't solved yet

**Comment by KenjiGinjo** [comment]
```
q = q.whereExists('members', (q) => q.where({ 'members.userId': dto.memberId }));
// this is ok, now
```

**Comment by romeerez** [comment]
Yes, that's was fixed, but the 2nd wasn't.

I just published an update for the 2nd case:

```ts
await db.activity.whereExists(db.activityMember, (q) =>
  // activity_member.activityId isn't turned to snake_case
  q.on('activity.id', 'activity_member.activityId').where({ name: 'test' }),
);
```

Now it also works.
