### ISSUE TITLE
column encode() should not be called for undefined values

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#340]
If a column is either nullable or has a default, and has a custom `encode` handler, the handler is mistakenly called for undefined input values, which it may (rightfully) reject or handle inappropriately. This leads to hard to catch runtime errors not exposed by the typings.

The above happens in at least these scenarios:
1) `insertMany` where some records have column values, and some don't.
2) `insert` with explicit `{ ..., column: undefined }`.

Expected: `encode()` is never called for undefined values. If they are undefined, they should not be inserted (with `insertMany`, `DEFAULT` should be inserted right away).

<details>
  <summary>Full reproduction</summary>

```ts
import process from "node:process"

import { createBaseTable, orchidORM, testTransaction } from "orchid-orm"

const BaseTable = createBaseTable({
  columnTypes: t => ({
    ...t,
    decimal: () => t.decimal().encode((value: number | string) => `${value}`),
  }),
})

class PostTable extends BaseTable {
  readonly table = "post"

  columns = this.setColumns(t => ({
    id: t.serial().primaryKey(),
    text: t.text(),
    rating: t.decimal().default("1"),
  }))
}

const db = orchidORM(
  { databaseURL: process.env.DATABASE_URL, log: true },
  {
    post: PostTable,
  },
)

await testTransaction.start(db)

await db.$query`
  create table "post" (
    id serial primary key,
    text text not null,
    rating decimal
  );
`

// INSERT INTO "post"("text", "rating") VALUES ($1, $2), ($3, $4) ['foo', '1.5', 'bar', 'undefined']
// Error: invalid input syntax for type numeric: "undefined"
await db.post.insertMany([
  { text: "foo", rating: 1.5 },
  { text: "bar" },
])

// INSERT INTO "post"("text", "rating") VALUES ($1, $2) ['foo', 'undefined']
// Error: invalid input syntax for type numeric: "undefined"
await db.post.insert({
  text: "foo",
  rating: undefined, // Accepted by typings!
})

await testTransaction.close(db)
```

**Comment by IlyaSemenov** [comment]
Note: updating `encode` to accept `undefined` is not really a workaround:

```ts
// works but is not really a solution
ratingWithoutDefault: t.decimal().encode((value: number | string | undefined) => value === undefined ? undefined : `${value}`)
```

because it breaks typings for non-nullable fields, as if they actually accept `undefined` for "normal" values (which they don't).

**Comment by romeerez** [comment]
The fix is published, now undefinedes will be ignored for both `create` and `createMany`.
