### ISSUE TITLE
[ASK] source code logic in `upsertOrCreate`

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#341]
Hi, I'm reading source code of the `ORM` these days, I have some questions about the following code.

In `.upsertOrCreate` [source code](https://github.com/romeerez/orchid-orm/blob/487e0e28b0cf28a1b11b80d18a61bbdecbfd2430/packages/qb/pqb/src/queryMethods/upsertOrCreate.ts#L79-L85
): 

```
    } else if (queryResult.rowCount > 1) {
      throw new MoreThanOneRowError(
        q,
        `Only one row was expected to find, found ${queryResult.rowCount} rows.`,
      );
    }
  };
```
`patchResult` hook checks if the `queryResult.rowCount > 1`, but in [Line-49](https://github.com/romeerez/orchid-orm/blob/487e0e28b0cf28a1b11b80d18a61bbdecbfd2430/packages/qb/pqb/src/queryMethods/upsertOrCreate.ts#L49), `returnType` is set to `one`. So is it really necessary to check `rowCount` here? Or it's a defensive programming to prevent `returnType` logic to to changed in the future.

**Comment by bingtsingw** [comment]
As I dig deeper, I found it more confusing in `upsertOrCreate` function.

```
// create 2 users
await db.user.create({});
await db.user.create({});

// @ts-expect-error
await db.user.where({}).orCreate({ name: 'xxx' }); // this line do not throw errors, it add `LIMIT 1` to the query.
await db.user.where({}).take().upsert({
    update: { name: 'xxx' },
    create: { name: 'xxx' },
}); // this line throws errors, `Only one row was expected to find, found 2 rows.`
```

Why and how did this magic happens

**Comment by bingtsingw** [comment]
I found where this magic happens, [this line](https://github.com/romeerez/orchid-orm/blob/487e0e28b0cf28a1b11b80d18a61bbdecbfd2430/packages/qb/pqb/src/queryMethods/upsertOrCreate.ts#L214) changes the query.

But it checks the `updateData` which can lead to weird behavior.

query one:
```
await db.user.where({}).take().upsert({
    create: { name: 'xxx' },
    update: { name: 'xxx' },
});
```

query two:
```
await db.user.where({}).take().upsert({
    create: { name: 'xxx' },
    update: { },
});
```

In query one, if user has more than one row, `.take()` will now work and it throws error, but in query two, it do not throw error and only trigger `create` logic

**Comment by romeerez** [comment]
I'll be back on weekends.

It's so nice to know that someone reads it :)
I know it's probably super confusing, but in defense, to my eyes it's somehow understandable.

The `returnType = 'one'` is for what we want - we want a single record.
When you do select, the `one` or `oneOrThrow` makes it so SQL has `LIMIT 1`.

`if (queryResult.rowCount > 1)` is for what we get - we got more than one and not what we expected, so you get the error, and hopefully it will be captured by Sentry or similar, and you'll be able to find this and fix.

It is for `UPDATE`, because you're free to update multiple records at once, and the `UPDATE` SQL cannot have `LIMIT`, so throwing in this case seems to be the only option.

```ts
await db.user.where({}).orCreate({ name: 'xxx' });
```
This can have a limit because it's select or create, without update. So it doesn't throw.

> but in query two, it do not throw error and only trigger create logic

It may be a bug, probably the empty update is a corner case that wasn't handled well.

**Comment by romeerez** [comment]
By the way, I'm not happy with the current upsert implementation because it's 2 queries that are wrapped in a transaction, so 4 roundtrips, and the code is hacky.

It should be possible to rework it into a single large query with CTE expressions, something like (from GPT):

```sql
WITH upsert AS (
    UPDATE example_table
    SET value = 42
    WHERE data = 'example'
    RETURNING *
), insert_if_not_exists AS (
    INSERT INTO example_table (data, value)
    SELECT 'example', 42
    WHERE NOT EXISTS (SELECT 1 FROM upsert)
    RETURNING *
)
SELECT * FROM upsert
UNION ALL
SELECT * FROM insert_if_not_exists;
```

**Comment by bingtsingw** [comment]
Thank you for your explain, I can understand the design now.
I thought `orCreate` and `upsert` logic are similar, like: 
if `count === 0`, do `create`
if `count === 1`, do `update` or nothing
if `count > 1`, throw error.
But the ORM logic is more complex than I imagined : )

**Comment by romeerez** [comment]
I updated `orCreate` and `upsert` logic, now it performs 1 or max 2 queries, without a transaction:

- first, `orCreate` tries to find, `upsert` tries to update;
- if not found,this performs a combined query that tries to find or update again (in case record was suddenly created a moment ago), and then creates if not found as a part of the same query.

[Here are the docs](https://orchid-orm.netlify.app/guide/create-update-delete.html#orcreate).
