### ISSUE TITLE
[ASK] how to query `iLike` for `jsonb` values

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#342]
In old version, I used `q.where({ profile: { jsonPath: ['$.name', 'ilike', `%${keyword}%`] } });`,
how to implement this in the latest `jsonPathQueryFirst` version

**Comment by bingtsingw** [comment]
Raw sql can do the trick:
```
q.where(
    raw({
      raw: `("user"."profile"->>'name')::text ILIKE $keyword`,
      values: { keyword: `%${keyword}%` },
    }),
  );
```

But I found the `sql` [document](https://orchid-orm.netlify.app/guide/sql-expressions.html#sql) seems broke, I can't find `sql` in `baseTable`, and the `raw` function do the work.

**Comment by bingtsingw** [comment]
`ILIKE $keyword` seems to have `SQL injection` issue

**Comment by romeerez** [comment]
> But I found the sql [document](https://orchid-orm.netlify.app/guide/sql-expressions.html#sql) seems broke

It assumes that you're exporting `sql` from your base table file, as shown [here](https://orchid-orm.netlify.app/guide/orm-and-query-builder.html#define-a-base-table).

Otherwise, you can use `db.table.sql`

```ts
const result = await db.user.where(
  db.user.sql`("user"."profile"->>'name')::text ILIKE ${'%text%'}`,
)
```

> ILIKE $keyword seems to have SQL injection issue

Shouldn't be, how exactly?

**Comment by romeerez** [comment]
Keep this issue open so I'll add support for the jsonb ilike later.

**Comment by bingtsingw** [comment]
I'm not sure if it's sql Injection, but in the following code, `input` can be `%xxx%`, `%xx`, `xx%`, and it can affect the searching result.
```
q.where(
  raw({
    raw: `("user"."profile"->>'name')::text ILIKE $keyword`,
    values: { keyword: input },
  }),
);
```

And if I have a record value is `%t%`, there is no way to search it exactly, see: https://github.com/bingtsingw/orchid-reproduction

**Comment by bingtsingw** [comment]
Update the `input` to `input.replace(/([\%_])/g, '\\$1')` do the work, I searched this escape topic on the Internet, it seems `LIKE` escape should be handled additionally.
https://elixirforum.com/t/how-to-prevent-like-injections/22791/7

**Comment by romeerez** [comment]
It's not a dangerous injection like when user can steal your info or drop tables.

But, very good call! I'm changing the logic to escape user-provided search inputs.

**Comment by romeerez** [comment]
Published update:

1. You can use `contains` after `jsonPathQueryFirst`.

The syntax `("user"."profile"->>'name')` is much better, but just not ready yet, so `jsonPathQueryFirst`.

```ts
await db.table.where((q) =>
  q
    .get('data')
    .jsonPathQueryFirst('$.name', { type: (t) => t.text() }) // need to tell query builder that this is a text field
    .contains('word'),
);
```

2. `contains`, `startsWith`, `endsWith`, and case-sensitive versions are now escaped, so '%' and '_' signs are treated literally in the search.

**Comment by bingtsingw** [comment]
> It's not a dangerous injection like when user can steal your info or drop tables.
> 
> But, very good call! I'm changing the logic to escape user-provided search inputs.

It's not a dangerous injection, but if user has a name  "%aaa", he searches `%a`, strange result will appear, so it's better to escape the user input.
