### ISSUE TITLE
[BUG] `jsonb` `contains` error

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#343]
When I use `contains` in the latest version, it shows an error
```
q.where((q) =>
    q
      .get('profile')
      .jsonPathQueryFirst('$.name', { type: (t) => t.text() })
      .contains(_keyword),
  )
```
<img width="394" alt="image" src="https://github.com/user-attachments/assets/ce9f4552-30d1-4f0f-a4e2-4498ce0fc12c">

**Comment by romeerez** [comment]
oops, fixing

**Comment by romeerez** [comment]
Published fix
