### ISSUE TITLE
[BUG] `updateAt` works unexpectlly 

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#349]
I used to rewrite `updatedAt` in `createBaseTable`:
```
updatedAt: t.timestampNoTZ()
  .encode((value: string | Date) => {
    if (typeof value === 'string') {
      return new Date(value);
    } else {
      return value;
    }
  })
  .parse((v: any): Date => (v ? new Date(v) : v)),
```
It do not trigger update the column in the latest version.

So I changed it to `t.timestamps().updatedAt`, but this do not respect `nowSQL` configuration.
`t.timestamps().createdAt` do not respect `nowSQL` as well.

**Comment by bingtsingw** [comment]
This is a big broken to my application, hope it can be solved quickly.
If you have no time, can I have some trick on it by myself now? For example, using `modifyQuery`

**Comment by romeerez** [comment]
> It do not trigger update the column in the latest version.

This is expected because how `t.timestampNoTZ()` would now that you want it to be auto-updated?

`...t.timestamps()`  and `...t.timestampsNoTZ()` are special and only they are auto-updated.

Why do you need that custom encode?

> So I changed it to t.timestamps().updatedAt, but this do not respect nowSQL configuration.
t.timestamps().createdAt do not respect nowSQL as well.

And this is a bug. It must be working and I have a test to check the custom `nowSQL`, please make a repro so I can see how it get broken.

I can't suggest a workaround because this is quite tricky to see why is it broken and how it can be fixed.

**Comment by bingtsingw** [comment]
Well, I know `t.timestampNoTZ()` do not auto update now, `encode` is just my old code working in old ORM version for a long time.
Recently I do update ORM version and shift `encode` to `timestamps().updatedAt` version, and found the bug.

**Comment by bingtsingw** [comment]
Hi, I have write a [reproduction repo](https://github.com/bingtsingw/orchid-reproduction), but what's interesting is that all test passes.

And I found why, I reproduction repo, I uses orchid for my migration which generate the database schema like this:
<img width="1176" alt="image" src="https://github.com/user-attachments/assets/2a052bc5-c2d1-487c-916b-6205a1e1de8a">

But in online database, ops team use another tools to generate the database, which like this:
<img width="884" alt="image" src="https://github.com/user-attachments/assets/54c0efc6-a1d9-4289-9384-7161158698e0">

**Comment by bingtsingw** [comment]
Sorry to disturb you, finally I find the reason, the old way breaks the `update` process, the new way(use it in the default way) `create` process,
so combining them together do the work:
<img width="573" alt="image" src="https://github.com/user-attachments/assets/88c6d14c-7caa-49be-97ba-9dc3c401ac9e">

**Comment by bingtsingw** [comment]
> No problem with disturbing, I always glad to help when I can, and not responding when I can't.

For `parse` part: it's just for convenient, I want the return value of timestamp column to be `Date`, maybe I should use `.asDate()`?

For `default ` part: it's a must for me because of the incorrect migration of database, I can left the `default` only if I can correct all the db errors, or I just ignore it and make it correct for my next new project : )
