### ISSUE TITLE
two bugs: `deletedAt` do not respect `nowSQL` and `.asDate` shows type error

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#350]
bug 1 is in this repo: https://github.com/bingtsingw/orchid-reproduction

**Comment by bingtsingw** [comment]
How to reproduce bug 2:
1. go to  `src/utils/base-table.ts`
2. replace all `parse((v: any): Date => (v ? new Date(v) : v))` with `asDate()` 
3. go back to `test` file.

You'll see `.create()` need to pass `createdAt`, `updatedAt` and `deletedAt`, which `nullable()` and `default` do not work

**Comment by romeerez** [comment]
Ready, I publised a fix: orchid-orm 1.34.2

Both problems are fixed, `asDate()` should now be working fine
