### ISSUE TITLE
[ask] custom columns type is `any` in a package

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#352]
Hi, I write a package [orchid-helper](https://github.com/bingtsingw/orchid-helper) for syncing several of my projects.
I add a `BaseTable` class to save my work, but when import the package, the return type of the db query is broken, do you have any clue?
<img width="462" alt="image" src="https://github.com/user-attachments/assets/0567d055-dfbe-4c28-855d-d4bb54493a23">

PS:
The package source file is in `packages/helper`.
To find out type problem, go to `apps/db/test/orchid/base-table.spec.ts` file, hover any query result

I used to use `BaseTable` in the same repo without compile a `.d.ts`, it has no problem, I guess it maybe the generated `.d.ts` not right. And I tried to generate `dts` with `tsc`, but it has lots of error.

**Comment by romeerez** [comment]
> And I tried to generate dts with tsc, but it has lots of error.

That's it, lots of errors. I remember someone tried to make a shared package and they also had problems with typings, don't remember exactly.

Don't do this, it's complicated and would take more time than save.

```ts
const createdAt = (t: DefaultColumnTypes<DefaultSchemaConfig>) => () =>
  t
    .timestampsNoTZ()
    .createdAt.default(() => new Date().toISOString())
    .asDate();
```

I still don't understand why do you need that default, if the `nowSQL` should be working fine. Maybe there are reasons, okay.

I suggest to copy-paste the common code where it's needed, to avoid problems such as typing issues and having additional complications with configuring and compiling.

**Comment by bingtsingw** [comment]
## Why I use `default`
Because `nowSQL` acts on `migration` process, but not all my projects can use `orchid-orm` to migrate db, some of them are not controlled by me and have wrong default settings in db side.
In projects using `orchid-orm` to migrate or if I have access to correct database `default`,  there is no need for `default(() => new Date().toISOString())`.
So there is nothing wrong with `orchid`, there is no bug : )

## For shared package
I didn't expect this problem to be so complicated, I'll use copy-paste for now.

**Comment by bingtsingw** [comment]
I update the `exports` in `package.json`, the type seems work. https://github.com/bingtsingw/orchid-helper/commit/9d2488411b9f7ebde38e03a2c02a88ebe1dcb42f

**Comment by bingtsingw** [comment]
I found it works to change to export types to a `.ts` file.

Types not work:
```
  "exports": {
    "default": "./dist/index.js",
    "types": "./dist/index.d.ts"
  },
```

Types work:
```
  "main": "./dist/index.js",
  "types": "./src/index.ts",
```

**Comment by IlyaSemenov** [comment]
@bingtsingw related discussion here #296.

**Comment by bingtsingw** [comment]
@IlyaSemenov I can use it successfully by setting `"types": "./src/index.ts"`, see my package here: https://github.com/bingtsingw/orchid-helper/tree/main/packages/helper
I'm not sure if this hack will be helpful to you.

**Comment by IlyaSemenov** [comment]
@bingtsingw No, that discussion is not about the particulars but about the actual problem (reusing derived column types, which is currently not developer friendly with Orchid).

As for publishing types, I see you're using `tsup`, you can use the built-in dts generator in `tsup.config.ts`:

```ts
import { defineConfig } from "tsup"

export default defineConfig({
  clean: true,
  entry: ["src/index.ts"],
  format: ["cjs", "esm"],
  sourcemap: true,
  dts: true,
})
```

and then in `package.json`:

```json
{
  "type": "module",
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.js",
      "require": "./dist/index.cjs"
    }
  },
  "main": "dist/index.cjs",
  "types": "dist/index.d.ts",
  "files": [
    "dist",
    "src"
  ]
}
```

This creates universal ESM+CJS package with proper types and sourcemaps.

**Comment by romeerez** [comment]
I'm glad to know you @bingtsingw figured it out, so closing this issue.

Maybe in future I'll also figure out a reliable way for shared packages, but that should be after figuring out sharing types with frontend because it impacts bundling settings, and will add an instruction for it. For now, yeah, that's not user-friendly.
