### ISSUE TITLE
Aggregate sum with numeric columns

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#356]
The documentation at https://orchid-orm.netlify.app/guide/aggregate.html#sum says:

> ### sum
> Retrieve the sum of the values of a given numeric column, returns number or null if there are no records.

Funnily enough, `sum` doesn't accept numeric columns at all:

```ts
class UserTable extends BaseTable {
  readonly table = "user"

  columns = this.setColumns(t => ({
    id: t.serial().primaryKey(),
    name: t.varchar(),
    balance: t.numeric(),
  }))
}

// Argument of type '"balance"' is not assignable to parameter of type
// 'SelectableOrExpressionOfType<SetQueryReturnsAll<TableToDb<UserTable, EmptyObject>>, NumberColumn>'.
await db.user.all().sum("balance")
```

It works in runtime, but it casts the result to number and thus loses precision:

```ts
await db.user.insertMany([
  { name: "Alice", balance: "111111111111111.111111111111111" },
  { name: "Bob", balance: "222222222222222.222222222222222" },
])

console.log(await db.user.all().sum("balance"))
// 333333333333333.3

console.log((await db.$query`select sum(balance) from "user"`).rows[0].sum)
// 333333333333333.333333333333333
```

* orchid-orm 1.34.5

### Expected

`sum("column")` works if the column is numeric, and returns a string (same as what the actual column value returns).

---

Originally reported: https://github.com/romeerez/orchid-orm/issues/353#issuecomment-2274988591

**Comment by IlyaSemenov** [comment]
Similarly, `db.user.increment({ balance: "111111111111111.111111111111111" })` should be possible for numeric columns. Currently `increment` only accepts numbers.

**Comment by romeerez** [comment]
Thank you for the detailed reporting, I published a fix for this.

Should work as expected, though perhaps won't be ideal for all use cases:
- when `sum`, `avg`, `min`, `max`, etc are executed on `number`-returning column (int, real), it's casted to a number by ORM
- when they are executed on numeric types (decimal) or too big types (bigint), it's returned as is - as a string

`increment` and `decrement` now accepts a string for decimal or bigint types.

**Comment by mordechaim** [comment]
@romeerez  aggregate functions don't properly work on `MONEY` fields. 

Doing `sum('amount')` results in `NaN`.  I believe it has something to do with string parsing.

**Comment by romeerez** [comment]
@mordechaim I'll try to fix it in the near days
