### ISSUE TITLE
Allow (or prevent) select after create

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#361]
Using `.create(...).select(...)` returns an object typed as if it had only select fields (as expected by looking at the query) but in fact it contains all fields.

For example:

```ts
const user1 = await db.user.select("id", "username").create({ username, email, password })
const user2 = await db.user.create({ username, email, password }).select("id", "username")
```

Both objects are typed as `{ id: string; username: string; }` but only `user1` is actually shaped like that. `user2` includes all the rest table fields, including `password`, `createdAt`, etc.

I believe if `.select()` after `.create()` is ignored it should be disabled at typings level, or perhaps even crash in runtime, or at least be typed appropriately. Or, the query builder should be fixed to actually work identically in both cases.

I know the correct order is documented, but nevertheless it is very easy to mix the two syntaxes and leak sensitive data.

* orchid-orm 1.34.5

**Comment by romeerez** [comment]
The idea was that it shouldn't matter if you place select before or after the create/update/delete, but apparently, something went a bit off when appending `select`, I'll fix.

**Comment by romeerez** [comment]
Published, now `select` should act equally when placed before or after create/update/delete.

Generally, `get`/`pluck` should also behave intuitively well enough disregarding of where they are placed.
