### ISSUE TITLE
select() typed as {} but returns full row

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#364]
```ts
const config = await db.config.select().take()
```

The return object is typed as `{}` but in runtime it's the full row: `{ id: 1, title: 'foo', secret: 'will leak' }`.

I propose to either disallow empty `select()` type-wise, or fix the runtime to return empty objects as advertised.

**Comment by romeerez** [comment]
I published a fix for this, if anyone was relying on `select()` returning a full record - this is a breaking change.

It will now return `{}` at runtime as the type suggests.
