### ISSUE TITLE
Accept native BigInt for bigint columns

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#365]
Given a table with a `bigint()` column, I would expect to be able to insert/update native bigints:

```ts
// Type 'bigint' is not assignable to type 'CreateColumn<TableToDb<ConfigTable, EmptyObject>, "bigIntColumn">'.
await db.config.insert({ bigIntColumn: 1n })
```

This is in line how `timestamp()` columns accept native `Date` objects even though they return a string on select.

---

Similarly, I suppose number-string columns such as `numeric()` could accept native numbers for insert/update/sum/increment (and also for `{ default: 0 }`).

**Comment by romeerez** [comment]
I ensured that in runtime it just works, you can insert bigints and they are properly saved.

Bigints are returned as strings from the database and it's good, as you don't always need to manipulate bigints, but JSON.stringify doesn't support them.

So the only missing bit is typing.

I published a fix to accept `string | number | bigint` when creating, updating, (inc|dec)rementing biging columns.
