### ISSUE TITLE
Raw SQL types broken

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#366]
Somehow all raw sql code that I borrow from the docs is broken. See below:

```ts
import { createBaseTable, orchidORM } from "orchid-orm"

const BaseTable = createBaseTable()

const { sql } = BaseTable

class UserTable extends BaseTable {
  override readonly table = "user"

  override columns = this.setColumns(t => ({
    id: t.serial().primaryKey(),
    name: t.varchar(),
  }))
}

const db = orchidORM(
  {},
  {
    user: UserTable,
  },
)

await db.user.select({
  // Error: The 'this' context of type 'void' is not assignable to method's 'this' of type 'PickQueryColumnTypes'.
  num: sql<number>`random() * 100`,
})

await db.$query<{ one: number }>(
  // Error: The 'this' context of type 'void' is not assignable to method's 'this' of type 'PickQueryColumnTypes'.
  sql({
    raw: "SELECT $value AS one",
    values: {
      value: 123,
    },
  }),
)
```

<img width="1071" alt="image" src="https://github.com/user-attachments/assets/b3017464-54a2-4356-b6f1-7c895cb812b6">

- orchid-orm 1.34.7
- typescript 5.5.4

**Comment by romeerez** [comment]
I'm quite sure it's something on your side, because CI wouldn't let it happen, and I didn't push related changes.

Perhaps, you have `pqb` or `orchid-core` package in package.json and their version is conflicting with `orchid-orm`. May be something else. Maybe something with monorepo.

**Comment by romeerez** [comment]
Reproduced, something is wrong, looking into it.

**Comment by romeerez** [comment]
Published a fix, also I deprecated `db.someTable.sql` way of using `sql` to have less ways of achieving the same.

**Comment by IlyaSemenov** [comment]
For the reference, the fix commit was 8e600c8e838a6c3debb64a136b7bcf74fe46112d (it referenced #336 by mistake).

**Comment by mordechaim** [comment]
I don't know why this I get this deprecation warning now:

```ts
computed = this.setComputed(q => ({
    random: q.sql`random()`.type(t => t.integer())
}))
```

I get a strikethrough on `q.sql` with a warning:

```
The signature '(this: PickQueryColumnTypes, ...args: StaticSQLArgs): RawSQL<QueryColumn<unknown, any>, { timestamp: (precision?: number | undefined) => ParseColumn<...>; ... 51 more ...; timestampsNoTZ<T extends ColumnTypeBase>(this: { ...; }): Timestamps<...>; }>' of 'q.sql' is deprecated.ts(6387)
index.d.ts(5420, 8): The declaration was marked as deprecated here
```

Why? And what's the alternative?

**Comment by mordechaim** [comment]
I see now I'm supposed to export `sql` from BaseTable, when did this change, and why? I wasn't aware of this change.

**Comment by romeerez** [comment]
> I see now I'm supposed to export sql from BaseTable, when did this change, and why?

There is a deprecation message when you hover it, but it's in the very bottom.
I'm moving it closer to top for visibility.

There is nothing bad about `q.sql`, I decided to deprecate it and remove in the future to have one thing less, because it's confusing that you can use `sql` from any query object and also there can be an exported `sql`, and prior to that there were some more similar helpers. In this issue I found that `q.sql` works fine while the exported one had a bug, and having less ways also means having less bugs.
