### ISSUE TITLE
JSON column type validation yields Typescript errors

### ISSUE THREAD

**Issue by ArtisanalPickle** [romeerez/orchid-orm#368]
Hi, we just attempted to update our package versions for `orchid-orm` and `orchid-orm-schema-to-zod` to the latest. 

<img width="431" alt="Screenshot 2024-08-15 at 1 27 05 PM" src="https://github.com/user-attachments/assets/55af717f-6817-45db-9428-b258a90a1395">

In attempting to make the necessary code changes I'm stuck with these typescript errors on the `t.json()` function call within the `setColumns` definition blocks of my tables:

<img width="927" alt="Screenshot 2024-08-15 at 1 25 11 PM" src="https://github.com/user-attachments/assets/7fa69257-0a59-4a2e-8416-a6307b677e6a">

 Here is my `BaseTable` definition:

```
import { createBaseTable, type DefaultColumnTypes } from "orchid-orm";
import {
  type ZodSchemaConfig,
  zodSchemaConfig,
} from "orchid-orm-schema-to-zod";

const columnTypes = (t: DefaultColumnTypes<ZodSchemaConfig>) => ({
  ...t,
  text: (min = 0, max = Infinity) => t.text().min(min).max(max),
  timestamp: <P extends number>(precision?: P) =>
    t.timestamp(precision).asNumber(),
});

export const BaseTable = createBaseTable({
  columnTypes,

  schemaConfig: zodSchemaConfig,
});

export type CustomColumnTypes = ReturnType<typeof columnTypes>;
```

Any guidance on how to get past this error would be much appreciated, thanks!

**Comment by romeerez** [comment]
Looks like it was `json(() => z.object())` and then it was changed to `json(z.object())` because `() => ` part isn't really needed, just I didn't update the docs. I'll update docs.

`t.json(z.object(...))` works fine on my end.

It's nice to see you're using timestamp `asNumber`, because it's more optimal for transferring, but is rarely used.

**Comment by romeerez** [comment]
Updated docs.

**Comment by ArtisanalPickle** [comment]
@romeerez greatly appreciated, thank you!
