### ISSUE TITLE
pqb database tests not reporting actual error / leaking due to improper teardown

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#373]
I added a regression test for #371:

```diff
diff --git a/packages/qb/pqb/src/columns/array.test.ts b/packages/qb/pqb/src/columns/array.test.ts
index 2383245f..689dd1b1 100644
--- a/packages/qb/pqb/src/columns/array.test.ts
+++ b/packages/qb/pqb/src/columns/array.test.ts
@@ -21,13 +21,13 @@ describe('array column', () => {
 
     it('should output nested array of strings', async () => {
       const result = await testDb.get(
-        testDb.sql`'{{"a", "b"}, {"c", "d"}}'::text[][]`.type((t) =>
-          t.array(t.array(t.text())),
+        testDb.sql`'{{"a", "b"}, {"str''ing", "str\"ing"}}'::text[][]`.type(
+          (t) => t.array(t.array(t.text())),
         ),
       );
       expect(result).toEqual([
         ['a', 'b'],
-        ['c', 'd'],
+        ["str'ing", 'str"ing'],
       ]);
 
       assertType<typeof result, string[][]>();
```

but the test runner won't properly report errors.

If started as `pnpm pqb check`, it gives:

```
> jest

 FAIL  src/columns/array.test.ts
  ● Test suite failed to run

    TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'Timeout'
        |     property '_idlePrev' -> object with constructor 'TimersList'
        --- property '_idleNext' closes the circle
        at stringify (<anonymous>)

      at messageParent (../../../../node_modules/.pnpm/jest-worker@29.7.0/node_modules/jest-worker/build/workers/messageParent.js:29:19)

 PASS  src/columns/string.test.ts
....
 PASS  src/queryMethods/expressions.test.ts
 PASS  src/queryMethods/with.test.ts
 PASS  src/queryMethods/aggregate.test.ts
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
```

If started as `pnpm pqb check array`, it gives:

```
> jest "array"

 FAIL  src/columns/array.test.ts
  array column
    array
      ✓ should output nested array of numbers (14 ms)
      ✕ should output nested array of strings (1 ms)
      ✓ should output nested array of booleans (1 ms)
      ✓ should have toCode (1 ms)

  ● array column › array › should output nested array of strings





    Cause:


      81 | } else {
      82 |   getThen = function () {
    > 83 |     queryError = new Error();
         |                  ^
      84 |     return maybeWrappedThen;
      85 |   };
      86 | }

      at Db.getThen (queryMethods/then.ts:83:18)
      at Object.get (columns/array.test.ts:23:35)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 3 passed, 4 total
Snapshots:   0 total
Time:        0.159 s
Ran all test suites matching /array/i.
```

Neither of the output reports the actual error / failed assertion.

May be we should replace `jest` with `vitest`?

**Comment by IlyaSemenov** [comment]
My bad, I didn't quote the double quote properly. It should have been `\\"` instead.

However, I still feel like the DX should be somehow improved here; if that was invalid SQL that should have been somehow surfaced and not print weird messages about leaking due to improper teardown.

**Comment by romeerez** [comment]
I added an intentional mistake to SQL in a test to see what Vitest would give:

```
 FAIL  columns/array.test.ts > array column > array > should output nested array of numbers
error: malformed array literal: "{{1, 2, 3}, {4, 5, 6}kokoko}"
 ❯ then queryMethods/then.ts:279:15
    277|     let error;
    278|     if (err instanceof pg.DatabaseError) {
    279|       error = new (q.error as unknown as new () => QueryE…
       |               ^
    280|       assignError(error, err);
    281|       error.cause = localError;
```

It's objectively better at this. I'll check if the same is achievable with Jest.

**Comment by romeerez** [comment]
Published an improvement:

> Converting circular structure to JSON

I hid the circular structure - query object - under JS `#` private field, so JSON won't see it, and now Jest can serialize it.

So now it will print error message and a stack trace. Unlike Vitest, it still doesn't print error details, so Vitest has more useful info.

**Comment by IlyaSemenov** [comment]
I prefer vitest for my projects because it reuses esbuild for runtime unlike Jest which pulls babel and a zillion babel plugins (with potentially slightly different behaviour). It's probably not much better for its main purpose (the actual testing), just a bit more "modern" IMO.

**Comment by romeerez** [comment]
While developing ORM and other libraries, I spend much time in tests, I'd even say 90-95% in tests, and Jest feels like a a comfortable old car that I get used to. Vitest feels different. Output is different, more colorful, and it doesn't feel better, just unusual. It has some problems that I don't have with Jest, somehow one file save triggers test re-run in Vitest multiple times for me, perhaps this has something to do with my editor.

Jest pulls Babel dependencies, that's right, but  Babel is not used if you configure Jest with swc or esbuild transformer.

Last time I tried Vitest on OrchidORM 3 months ago, and it's fast and good, but Jest still was faster, at least on this codebase.

It's better to avoid module mocks like `jest.mock`, but sometimes they are hard to avoid. And it's easier to do in Jest, because it doesn't have to workaround ESM limitations.
