### ISSUE TITLE
After commit hooks don't work inside testTransaction without inner transaction

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#375]
Following #354 and #355, I noticed that after commit hooks don't work inside `testTransaction` without inner transaction:

```ts
await testTransaction.start(db)

await db.user.insert({ name: "Alice" }).afterCreateCommit(["id", "name"], ([user]) => {
  console.log(`Sending email to user: ${JSON.stringify(user)}`)
})

await testTransaction.close(db)
```

This doesn't print anything. It works without `testTransaction`, or with a `db.$transaction` inside `testTransaction`, but not in the scenario above.

- orchid-orm 1.35.0

**Comment by romeerez** [comment]
Published a fix, this should be working fine.

**Comment by IlyaSemenov** [comment]
I confirm it was. Thanks!
