### ISSUE TITLE
Type parsing doesn't work on computed fields

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#380]
Say I have a numeric column, that returns a string, so I want to parse it.

Given this table declaration:
```ts
export class OneTable extends BaseTable {
    readonly table = 'one'

    computed = this.setComputed(q => ({
        computedRaw: sql`1.5`.type(t => t.numeric().parse(parseFloat))
    })
}
```

I try to parse as follows:

```ts
const result = await db.one.select('computedRaw', {
    raw: sql`1.5`.type(t => t.numeric().parse(parseFloat))
})

console.log(result.raw, typeof result.raw)
console.log(result.computedRaw, typeof result.computedRaw)
```

The above prints:
```
1.5 number
1.5 string
```

**Comment by romeerez** [comment]
Until it's fixed, you can cast the value to `real` type in the sql:

```ts
sql`1.5::real`.type((t) => t.real())
```

`real` is the same as `float`, so you can do `1.5::float`, but there is no `t.float` so having real on both sides is more consistent.

**Comment by romeerez** [comment]
I published a fix, now parsers should be respected on computed columns.

**Comment by mordechaim** [comment]
Thank you @romeerez
