### ISSUE TITLE
Aggregate functions don't properly work on `MONEY` fields.

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#391]
Aggregate functions don't properly work on `MONEY` fields. 

Doing `sum('amount')` results in `NaN`.  I believe it has something to do with string parsing.

_Originally posted by @mordechaim in https://github.com/romeerez/orchid-orm/issues/356#issuecomment-2310677320_

**Comment by romeerez** [comment]
I figured out that it is not a bug:

```sql
SELECT avg(x)
FROM (
  SELECT 1::money x
  UNION
  SELECT 2::money x
) t
```

```
[42883] ERROR: function avg(money) does not exist Hint: No function matches the given name and argument types. You might need to add explicit type casts. Position: 8
```

You should use `decimal` or `numeric` (they are the same) for storing exact numbers with floating point, or store money as cents integer, Stripe does it so.

**Comment by mordechaim** [comment]
But `sum` is a valid aggregate function though

**Comment by romeerez** [comment]
That's not correct, I'll change it so TS will complain when you do `db.table.sum('amount')` for a `money` column.

**Comment by mordechaim** [comment]
It is, I just tried
![image](https://github.com/user-attachments/assets/da5cbef3-7e84-4151-b197-358d3ffbcb44)

![image](https://github.com/user-attachments/assets/97b23ae0-822b-4632-a3b5-74e4a9441cc1)

**Comment by romeerez** [comment]
Oh, I tried

**Comment by romeerez** [comment]
I pushed improvement for aggregate argument types.

Not just for `money`, but I listed actual postgres arg types for every aggregate function in ORM and listed arg types literally, so `min` and `max` support numbers, text (wasn't expecting that), dates, timestamps, intervals; `sum` supports numeric types + money, `avg` the same as `sum` but without money, and some more of this.

**Comment by mordechaim** [comment]
Thank you.

Btw I noticed the money parse regex assumes the currency to be $, how does it handle other currency symbols? (Just reading the code, haven't tested it)

**Comment by mordechaim** [comment]
I tried the new version, the sum function now works, but the return value is not parsed to js numbers, instead it returns the string value as `$1.00`.

By now I think I should just use `numeric`...

**Comment by romeerez** [comment]
> how does it handle other currency symbols? (Just reading the code, haven't tested it)

I don't know, that's coming from and handled by postgres.

> instead it returns the string value as $1.00.
> By now I think I should just use numeric

Numeric/decimal types are returned as strings as well, because postgres handles them in a precise way, but JS numbers are more limited and imprecise.

I should research on the topic and write a doc section that suggests how to deal with money and other precise amounts.

**Comment by mordechaim** [comment]
I'm referring to
https://github.com/romeerez/orchid-orm/blob/3a92c5346c6a97f012e782f6f89958984a2bf391/packages/qb/pqb/src/columns/string.ts#L335

Which will fail if the locale is set to any country that uses a different currency symbol.

**Comment by romeerez** [comment]
Thanks for pointing, I'll update that piece.
