### ISSUE TITLE
sudden breaking changes in @1.35.8?

### ISSUE THREAD

**Issue by KMJ-007** [romeerez/orchid-orm#397]
below column defination were working in ^1.31.7, but when upgraded baisc things like column definition types are breaking?

if there is fundamental changes then do major release, it helps us to use it or not

trim is not working in string type, serial is not showing primary key

<img width="1374" alt="image" src="https://github.com/user-attachments/assets/dc8282b2-7404-48c6-bbe4-3807540e1cf6">
<img width="1428" alt="image" src="https://github.com/user-attachments/assets/40938233-bed4-49f2-8b1d-fdd1f958e2aa">

**Comment by IlyaSemenov** [comment]
This is most probably caused by broken deps or TS using old packages after update. It definitely works with orchid-orm 1.35.8 + orchid-orm-schema-to-zod 0.8.46. Try deleting and reinstalling `node_modules` and reloading VS Code.
