### ISSUE TITLE
Prevent redundant inner transaction

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#398]
I'd like to be able to wrap some code in a transaction, **unless it already runs in a transaction**.

That means, more often than not I don't really need nested transactions (savepoints). I just want to prevent inconsistent data ending up in the database. Consider the two functions:

```ts
async function updateUserBalance(userId: string, amount: number) {
  await db.$transaction(async () => {
    await db.transfer.create({ userId, amount })
    await db.user.find(userId).increment({ balance: amount })
  })
}

async function saveDeposit(userId: string, deposit: { ... }) {
  await db.$transaction(async () => {
    await db.deposit.create(deposit)
    // This will start redundant inner transaction.
    await updateUserBalance(userId, deposit.amount)
  })
}
```

`saveDeposit` runs 7 SQL queries while only 5 are actually needed for the operation (BEGIN + 3 INSERTs + COMMIT). If there were an API like `db.$ensureTransaction`, that won't be the case.

Note that even Orchid ORM itself uses this approach in `insertMany`: _"To solve this seamlessly, OrchidORM will automatically batch such queries, and wrap them into a transaction, unless they are already in a transaction."_

**Comment by romeerez** [comment]
Published [$ensureTransaction](https://orchid-orm.netlify.app/guide/transactions.html#ensuretransaction).
