### ISSUE TITLE
Extensions are dropped on new migration generation

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#400]
I try to use the `citext` type. Per the documentation I need to first enable it in a migration, since the `g` command won't detect it, I manually create a migration using the `new` option.

After running the migration I try to create a new migration (using the citext in a column) but the generator tries to `dropExtension()` and the code gen fails:

```js
error: cannot drop extension citext because other objects depend on it
    at [redacted]\node_modules\pg\lib\client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TransactionAdapter.query ([redacted]\node_modules\pqb\src\adapter.ts:241:12)
    at createExtension ([redacted]\node_modules\rake-db\src\migration\migration.ts:1568:9)
    at async eval (eval at verifyMigration ([redacted]\node_modules\orchid-orm\dist\migrations.js:2100:23), <anonymous>:11:3)
    at adapter.transaction.text [redacted]\node_modules\orchid-orm\src\migrations\generate\verifyMigration.ts:40:15)
    at Adapter.transaction ([redacted]\node_modules\pqb\src\adapter.ts:142:18)
    at generate ([redacted]\node_modules\orchid-orm\src\migrations\generate\generate.ts:122:20)
    at runCommand ([redacted]\node_modules\rake-db\src\rakeDb.ts:155:11) {
  length: 251,
  severity: 'ERROR',
  code: '2BP01',
  detail: 'column email of table account_user depends on type citext',
  hint: 'Use DROP ... CASCADE to drop the dependent objects too.',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'dependency.c',
  line: '1204',
  routine: 'reportDependentObjects'
}
```

**Comment by mordechaim** [comment]
If I try to install the `postgis` extension which adds a table `spatial_ref_sys`, I'm completely out of luck, the `g` command complains about the table missing.

**Comment by romeerez** [comment]
I'll be able to look at it on weekends, perhaps the problem with dropping `citext` isn't a bug, but you need to list it in `extensions`, as described [here](https://orchid-orm.netlify.app/guide/orm-and-query-builder.html#generate-migrations), scroll down a little bit.

I see it's not easy to find in the docs, need to make it more visible.

> If I try to install the postgis extension which adds a table spatial_ref_sys, I'm completely out of luck, the g command complains about the table missing.

It's a different problem, I'll see what can be done.

**Comment by mordechaim** [comment]
Yes! I missed this part of the docs. Thanks for pointing me to the right direction.

**Comment by romeerez** [comment]
I discovered one problem with extensions that requires rethinking the migrator's approach on extensions.

All pending migrations are executed in a single transaction, so if some fails, all is reverted.

Turns out, postgres cannot enable extension and use it in a same transaction, so extensions must be handled separately.

This means the rake-db toolkit must handle extensions somehow separately, and the migration generator must account for that.

This will take quite a notable time to handle, I'm looking into how to workaround that.

**Comment by romeerez** [comment]
I published a couple of related fixes, but overall it's not ready yet.

See this [note in the docs](https://orchid-orm.netlify.app/guide/orm-and-query-builder.html#extensions).

So you can enable and use citext by creating it in db manually and adding to the `extensions` array.

But the problem with the postgis table is currently there.

**Comment by romeerez** [comment]
Weird, last week I was sure that I discovered a postgres limitation regarding extensions, and believed that I have to rework this part.

But now it seems to be fine, no need to rework, I mean what I wrote above about extensions in transactions - seems to be ok as it is.

**Comment by romeerez** [comment]
I published some fixes and a postgis geography type for testing.

```ts
class MyTable extends BaseTable {
  readonly table = "table";
  columns = this.setColumns((t) => ({
    id: t.identity().primaryKey(),
    title: t.citext(), // citext column
    point: t.geography.point(), // postgis geography(Point) column
  }));
}

export const db = orchidORM({
    databaseURL: process.env.DATABASE_URL,
    extensions: ["citext", "postgis"], // to enable extensions
    generatorIgnore: {
      tables: ["spatial_ref_sys"], // ignore postgis table
    },
}, {
  myTable: MyTable,
});
```

Running the generator works, applying the migration works.

Postgis is large and going take many efforts to support most of its functionality, so for now it's just a single geography point type.
