### ISSUE TITLE
Add decimal().asNumber()

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#406]
As suggested at https://github.com/romeerez/orchid-orm/issues/405#issuecomment-2361801658:

> For the decimal number parsers, if it's not yet included, let's add `decimal().asNumber()` helper.

That should also affect aggregation results I suppose.

Perhaps `bigint()` could have a similar counterpart, although this will have less use, because numbers are JSON-serializable and bigints aren't. However, I suppose not everyone directly feeds ORM results to JSON-operating layer, so this could be still useful.

**Comment by romeerez** [comment]
I'll add it later, after handling more critical issues.

**Comment by romeerez** [comment]
After some more thinking, no, this shouldn't be here.

`decimal` and `doublePrecision` are returning strings on purpose of not loosing precision.

Currently, there is no such `asNumber` and it makes you think how you're going to parse it, and so you came up with a Decimal solution.

But if there was `decimal().asNumber()`, users could just slap it on and call it a day, so let it continue to return strings.
