### ISSUE TITLE
Allow to omit list of fields in afterCreate, afterUpdate

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#410]
Following #409, I was thinking, can we add a simplified overload for `afterCreate` and `afterUpdate` that simply selects all involved fields?

So that:

```ts
await db.order
  .find(orderId)
  .update({ status: "paid", paidTime: new Date() })
  .afterUpdate(["status", "paidTime"], ([data]) => {
    Object.assign(order, data satisfies Partial<typeof order>)
  })
```

becomes possible to be simplified as:

```ts
await db.order
  .find(orderId)
  .update({ status: "paid", paidTime: new Date() })
  .afterUpdate(([data]) => {
    // data is { status: string; paidTime: string }
    // or possibly { status: string; paidTime: string; updatedAt: string } if timestamps are used
    Object.assign(order, data satisfies Partial<typeof order>)
  })
```

With `afterCreate`, I suppose it could just return all fields in this shortcut overload.

**Comment by IlyaSemenov** [comment]
Another idea is, without the explicit list of fields, it could just pass the result of the original query to the callback. This is quite logical in my thinking and will allow the following approach:

```ts
const selectObj = db.table.makeHelper(...) // reusable helper in a different module

const updatedObj = await selectObj(db.table).find(id).update({ ... }).afterUpdate((updatedObj) => {
  // We can't access the outer scope updatedObj here due to runtime error:
  // Cannot access 'updatedObj' before initialization.
  // but Orchid could just pass the query result as the callback parameter, couldn't it?
  console.log('actually updated obj', updatedObj)
})
```

To be honest, with that addition, I'm not sure if the original syntax is needed at all. We already have powerful means in the query builder to select and transform results. Why repeating the mini version of it in the first argument of `after*` hooks?

**Comment by romeerez** [comment]
> Why repeating the mini version of it in the first argument of after* hooks?

The main idea was to handle `afterUpdate`, `afterCreate`, and some others in a centralized place - where the table is defined. Not on queries. In the query you may select no fields at all, and that list makes sure to load what's needed in the callback.

Since the logic of selecting extra fields and triggering callbacks was already in place, it was easy to expose the hooks on a query object, so I added them just in case.

If you already have `const updatedObj = await *update operation*`, why do you want to have the same object in a callback in the same place?

**Comment by romeerez** [comment]
Let's close this then.

The list may be also useful if you ever want to set `afterCreate` in a `makeHelper`, where the `makeHelper` doesn't know what fields are selected.
