### ISSUE TITLE
Detect if inside transaction

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#411]
I am writing an app that interacts with an external system. The app implements crash recovery in the following manner:

1. Before doing any work, it checks in the db if the work has already been started.
1a. If db says the work has been previously started and not finished, it goes into recovery mode (reconcile status with the external system). This is not covered here.
2. Before doing any actual work, it updates the db and saves work start time.
3. It actually does some work interacting with an external system.
4. It marks work as done.

Now then, if the server crashes on step 3, and the app restarts, supposedly it will go to the recovery branch.

The problem is, if this code runs in a transaction by mistake, and the app crashes, the database will never save that the work has been started, as the transaction will not commit. On restart, the app will not go into recovery and will proceed as normal, which will (in my case) cause double spending.

So what I need is, somehow assert that there is no started transaction (presumably ignoring `testTransaction`). Can we have a public API for that?

**Comment by romeerez** [comment]
Done, I added [db.$isInTransaction](https://orchid-orm.netlify.app/guide/transactions.html#isintransaction) for this.
