### ISSUE TITLE
Type error for branded strings in t.varchar().parse()

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#412]
I am using an external library which uses branded strings (strings with mixed unique symbol) to distinguish its data types. I would like to store these strings in the database and "parse" them accordingly on select.

However, perhaps due to `Simplify` wrapper on the results, this doesn't really work:

```ts
import { createBaseTable, orchidORM } from "orchid-orm"

type MyString = string & {
  readonly __brand: unique symbol
}

function makeMyString(input: string): MyString {
  return input as MyString
}

const BaseTable = createBaseTable()

class TestTable extends BaseTable {
  override readonly table = "test"

  override columns = this.setColumns(t => ({
    id: t.uuid(),
    string: t.varchar(),
    myString: t.varchar().parse(makeMyString),
  }))
}

const db = orchidORM({}, {
  test: TestTable,
})

function printMyString(s: MyString) {
  console.log(s)
}

const obj = await db.test.take()

// @ts-expect-error Argument of type 'string' is not assignable to parameter of type 'MyString'.
printMyString(obj.string)

// No error.
printMyString(makeMyString(obj.string))

// Argument of type '{ readonly [x: number]: string; toString: () => string;
// charAt: (pos: number) => string; charCodeAt: (index: number) => number;
// concat: (...strings: string[]) => string; indexOf: (searchString: string,
// position?: number | undefined) => number; ... 47 more ...; readonly __brand: unique symbol; }'
// is not assignable to parameter of type 'MyString'.
printMyString(obj.myString)
```

Is there any approach that would allow using branded strings with Orchid ORM results? What if we introduce some kind of opt-in type wrapper that will prevent further recursive "simplification"? So in the example above, I could do something like:

```ts
{
  myString: t.varchar().parse(value => makeMyString(value) as StopSimplify<MyString>)
  // or with no-op runtime type helper:
  myString: t.varchar().parse(value => stopSimplify(makeMyString(value)))
}
```

This could be also useful (not sure in that) for cases as in #377 because even though the `Decimal` type does technically work after simplification but it loses its original types, in particular attributed JSDoc.

Ideally, simplification should automatically stop on field types, but I realize that could be impossible to achieve.

**Comment by romeerez** [comment]
Published, you're right that was due to `Simplify` that was recursively destructuring return types, I updated the code to simplify types in a shallow manner instead. So it works until it means the "leaf" type of a column, and no matter if the column type is branded or complex, it's returned as is.
