### ISSUE TITLE
Multi-column checks aren't generated

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#418]
I add multi-column checks as documented [here](https://orchid-orm.netlify.app/guide/migration-column-methods.html#multi-column-check) (unrelated, but `t.integer().check()` in docs seems like a typo).

When running `npm run db g` it completely skips over multi-column checks. Composite indexes do get generated as expected.

**Comment by romeerez** [comment]
Could you share your code?

It works for me when I'm trying:

```ts
export class PostTable extends BaseTable {
  readonly table = "post";
  columns = this.setColumns(
    (t) => ({
      id: t.identity().primaryKey(),
      a: t.integer(),
      b: t.integer(),
    }),
    (t) => t.check(t.sql`a < b`), // multi-column check
  );
}
```

`pnpm db g` generates:

```ts
import { change } from "../dbScript";

change(async (db) => {
  await db.createTable(
    "post",
    (t) => ({
      id: t.identity().primaryKey(),
      a: t.integer(),
      b: t.integer(),
    }),
    (t) => t.check(t.sql`a < b`),
  );
});
```

`t.integer()` in the docs is a typo indeed.

**Comment by mordechaim** [comment]
I'm not at my computer right now to check (and won't be for a couple of days) but I have a slightly different case:

1. I use the array version since I have multiple checks
2. I already have the table definition, perhaps "updates" aren't detected?

**Comment by romeerez** [comment]
I tried with array, tried to first create table and then to add index in a 2nd migration, and it works on my computed, so please share your code when you will be able to.

**Comment by mordechaim** [comment]
Checks don't work for me, not indexes.

I'll create a reproduction in a couple of days

**Comment by mordechaim** [comment]
Here you go
https://github.com/mordechaim/orchid-repro-checks

The database already has 2 migrations applied, including a single column check. The generator will not detect the multi-column check (which was added after the single column check migration was generated).

You can play with the database, I'll delete it after it's fixed.

**Comment by romeerez** [comment]
Yea, I'll try to figure this out next weekends, feel free to point out if any issue is more important than the others, because for me they are equal.

**Comment by romeerez** [comment]
Ready, I published update.

- a single column can have multiple checks
- migration always generates checks with names
- fixed `{ name: '...' }` bug
- solved naming collisions by appending an incrementing number
- check names are no longer ignored

So I tried to ensure that both 1. and 2. are now correctly working.
