### ISSUE TITLE
[ask] How to ORDER BY the IN value list in Orchid ORM?

### ISSUE THREAD

**Issue by KenjiGinjo** [romeerez/orchid-orm#422]
Hi, I need to order the **note** records based on the order of ids returned from a previous query. Here’s my current setup:

```ts
 const ids = await db.collect
      .where(...)
      .pluck('collectableId');

const data = await dr.note
      .whereIn('id', ids)
```

I would like the note records to be ordered by the ids array order. Could you provide suggestions or best practices on how to achieve this in our ORM?

Thanks!

**Comment by bingtsingw** [comment]
In mysql, it's simple to use `FIELD`:
```
.orderSql`FIELD(id, $ids)`
```
In postgres, seems `array_position` can do the trick:
```
.orderSql`array_position(ARRAY${ids}, id)`
```

**Comment by romeerez** [comment]
Thanks, @bingtsingw, `array_position` works well for this, just without the `ARRAY` part:

```ts
const orderedByIds = await db.someTable.where({ id: { in: ids } }).orderSql`array_position(${ids}, id)`

const reversed = await db.someTable.where({ id: { in: ids } }).orderSql`array_position(${ids.reverse()}, id)`
```

@KenjiGinjo perhaps you could do that in one query, it depends on your case. I mean, you can select notes in the "collect" query.

**Comment by KenjiGinjo** [comment]
It works! 😍😘 Thanks @bingtsingw  @romeerez
