### ISSUE TITLE
`generated` column checking for null values.

### ISSUE THREAD

**Issue by krishna-404** [romeerez/orchid-orm#424]
I am using a column which looks like this `commentHash: t.text().generated`md5(comment)`,`

1. When generating migration, its throwing error that the exisiting column value is null.
2. when inserting data, typescript is throwing an error that `undefined` is not accepted.

**Comment by romeerez** [comment]
I see that 1. is because you're trying to add a required column to an existing table and the migration fails because it's empty.

But in 2. I don't know what you're doing, could you share the code?

**Comment by romeerez** [comment]
Not sure how you're trying to insert data when the migration is failing, but I reproduced the 1st point and will fix.

**Comment by romeerez** [comment]
Until it's fixed, you can generate the migration manually to add that column. (`new` instead of `g` in the terminal)

**Comment by krishna-404** [comment]
So lets say the schema earlier was 

`table({ comment: t.text()})`

Now we are adding the column

`commentHash: t.text().generatedmd5(comment),`

In migration, this doesn't need a default value. by adding the below code directly to migration file, there are no errors thrown. Errors get thrown only when generating the migration

```
	// create comment hash column
	await db.changeTable("linkedin_comments", (t) => ({
		...t.add(t.name("comment_hash").text().generated`md5(comment)`),
	}));
```

**Comment by romeerez** [comment]
>  Errors get thrown only when generating the migration

Yes, right, because currently the generator is missing the handler for `generated`

**Comment by romeerez** [comment]
Ready, now generated columns will be generated without problems.
