### ISSUE TITLE
char varying length error on insert

### ISSUE THREAD

**Issue by krishna-404** [romeerez/orchid-orm#425]
Facing the below error when inserting values. Have checked the schema in code & also in db, couldnt find any discrapencies. This what AI had to say after debugging this... what do you suggest?

<img width="782" alt="image" src="https://github.com/user-attachments/assets/0c3ebd67-c1f3-47c4-a8ef-346c820bdf49">

```
api:dev: [08:50:16 UTC] FATAL: Unexpected error.
api:dev:     err: {
api:dev:       "type": "",
api:dev:       "message": "value too long for type character varying(255): ",
api:dev:       "stack":
api:dev:           error: value too long for type character varying(255)
api:dev:               at then (/Users/krishna404/codeProjects/teziapp/zeon-fork/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/queryMethods/then.ts:411:15)
api:dev:               at processTicksAndRejections (node:internal/process/task_queues:95:5)
api:dev:               at async updateDataToDb (/Users/krishna404/codeProjects/teziapp/zeon-fork/apps/api/src/services/brightdata/postsWebhook.brightdata.service.ts:132:4)
api:dev:               at async postsWebhookBrightdataService (/Users/krishna404/codeProjects/teziapp/zeon-fork/apps/api/src/services/brightdata/postsWebhook.brightdata.service.ts:299:2)
api:dev:           caused by: Error
api:dev:               at Db.getThen (/Users/krishna404/codeProjects/teziapp/zeon-fork/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/queryMethods/then.ts:84:18)
api:dev:               at Db.catch (/Users/krishna404/codeProjects/teziapp/zeon-fork/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/queryMethods/then.ts:49:17)
api:dev:               at updateDataToDb (/Users/krishna404/codeProjects/teziapp/zeon-fork/apps/api/src/services/brightdata/postsWebhook.brightdata.service.ts:141:11)
api:dev:               at processTicksAndRejections (node:internal/process/task_queues:95:5)
api:dev:               at async postsWebhookBrightdataService (/Users/krishna404/codeProjects/teziapp/zeon-fork/apps/api/src/services/brightdata/postsWebhook.brightdata.service.ts:299:2)
api:dev:       "length": 99,
api:dev:       "name": "error",
api:dev:       "severity": "ERROR",
api:dev:       "code": "22001",
api:dev:       "file": "varchar.c",
api:dev:       "line": "641",
api:dev:       "routine": "varchar"
api:dev:     }
```

**Comment by romeerez** [comment]
I agree with the AI.

Could you enable log in the ORM itself?

Add `log: true` to the config where you're defining `databaseURL`, and then it will log the query with values when it fails.

**Comment by krishna-404** [comment]
Where can I DM/email you the actual query @romeerez ?

**Comment by krishna-404** [comment]
I just changed all columns to text type and still I am getting the `varchar` error. copy pasting the log-query (after basic formatting for syntax ofcourse) works wihout any issue

**Comment by krishna-404** [comment]
So here is some highlights after some major logging & debugging with the help of AI. So basically when doing a `onConflict.merge` I am getting this error where the input is being typecasted. Does that ring any bells?

```
AHA! The insert worked! This tells us something very important:
1. The varchar(255) error only happens during the ON CONFLICT DO UPDATE part of your original query
2. All the fields work fine with TEXT type for direct inserts
```

```
2. The UPDATE part might be triggering some type conversion
```

```
The issue is with the `post_text` field! Even though it's defined as TEXT in the schema, something in the update path is trying to put it into a varchar(255).
```

**Comment by romeerez** [comment]
You can DM to my email romadzao@gmail.com, or just put the query log with error here with redacted sensitive info.

Okay, so the error happens on `onConflict.merge`, but it's still unclean what data is merged, and why is it causing the error if you changed the string types to unlimited `text` type.

**Comment by krishna-404** [comment]
Hi! Sorry for troubling you with this. the issue was that one of the fields was of type `varchar[]`. But postgres was not throwing the error properly.

And when inserting the data directly via SQL query it was working... Unless you have reasons to debug this, you may close this issue. Apologies & Thanks!

**Comment by krishna-404** [comment]
Also a enhancement request... what if when creating zod schema we could have the max-length property set within it... would help us get better errors at validation level itself.

**Comment by romeerez** [comment]
So did you resolve the issue?

`varchar[]` shouldn't have 255 limit. Only the `t.string()` sets 255 by default, so I suspect you have `t.string()` column somewhere.

> what if when creating zod schema we could have the max-length property set within it.

As far as I remember, this should be already working, so if you make a column `t.varchar(123)`, or `t.string()` (255 by default), or `t.text().max(123)`, these should have a max validation in zod. Let me know if that doesn't work, though I believe I have tests testing this.

**Comment by krishna-404** [comment]
The column type was `t.array(t.string())` changing it to `t.array(t.text())` solved the issue.

Just that postgres error wasnt verbose enough. & postgres detailed logging was pointing to a wrong column, making me go in circles :|

**Comment by romeerez** [comment]
Indeed, if the error could point to the specific column it would save a lot of time. And I'm sure that at least in some cases, the error does that and suggests a specific column, but apparently not in this case.

Glad for you to resolve it after much investigation, and hopefully this will go smoother the next times.
