### ISSUE TITLE
Module resolution error

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#427]
With `orchid-orm@1.37.10` I run into the following error

```
./node_modules/orchid-orm/dist/index.mjs
The requested module 'orchid-core' contains conflicting star exports for the name 'templateLiteralToSQL' with the previous requested module 'pqb'
```

I already made sure I have the latest `orchid-core` (0.21.2) and `pqb` (0.42.7).

The error is also present in `1.37.9`; I had to downgrade to `1.37.8` to fix this.

**Comment by romeerez** [comment]
The latest is 1.37.10, did you try it?

`templateLiteralToSQL` failed in CI and I fixed and published it immediately a couple days ago.

**Comment by mordechaim** [comment]
Yes, I tried both 1.37.9 and 1.37.10

**Comment by matthewmorek** [comment]
I can confirm, after upgrading to `1.37.10` I have the exact same issue.

**Comment by romeerez** [comment]
Published a fix - simply republishing helped.
Thanks for reproduction.

Apparently, CI process isn't ideal and may leak failed builds (in rare cases, because usually it's acting normal).
