### ISSUE TITLE
Optimize orCreate() for frequent select / rare create

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#431]
Currently, `find().orCreate()` always starts a transaction:

```ts
const userId = await db.user.findByOptional({ tgId }).orCreate({ tgId }).get("id")

// Note by the way that this gives invalid type, see https://github.com/romeerez/orchid-orm/issues/408
const userId = await db.user.get("id").findByOptional({ tgId }).orCreate({ tgId })
```

```
(0.7ms) BEGIN
(2.4ms) SELECT "user"."id" FROM "user" WHERE "user"."tg_id" = $1 LIMIT 1
(5.0ms) COMMIT
```

This seems sub-optimal for cases when the vast majority requests is for SELECT and only very few end up with INSERT. The 3 queries above run more than 3x slower than the actual SELECT. Example of such scenario being a telegram command handler which looks up user from the database and creates it as needed.

Currently, I use this boilerplate:

```ts
const selectUser = db.user.makeHelper(q => q.select("id", "tgId", "...")) // Reuse selector
const user = await selectUser(db.user).findByOptional({ tgId })
    ?? await selectUser(db.user).findBy({ tgId }).orCreate({ tgId })
```

I believe it deserves a place in the core (maybe as an option for `orCreate`?). Something similar has been discussed in #169, but it's a bit different perspective now. Back then, @romeerez elaborated it wasn't safe, but I don't see how. The second query will run a transaction anyway so this seems to be safe just having some optimistic prefetch.

**Comment by romeerez** [comment]
I had plans to change implementation of this to run in a single query, using `WITH` statements. Just need to get there.

Here is what ChatGPT suggested for this:

```sql
WITH existing_row AS (
    SELECT id
    FROM your_table
    WHERE unique_column = 'your_value'
)
, inserted_row AS (
    INSERT INTO your_table (unique_column, other_column)
    SELECT 'your_value', 'other_value'
    WHERE NOT EXISTS (SELECT 1 FROM existing_row)
    RETURNING id
)
SELECT id
FROM existing_row
UNION ALL
SELECT id
FROM inserted_row;
```

> Currently, I use this boilerplate:

It's faster because it doesn't use transaction, but also it has a race condition because of that. Two simultaneous queries might end up both creating a new record.

**Comment by IlyaSemenov** [comment]
> Two simultaneous queries might end up both creating a new record.

How so? It falls back to `find().orCreate()` which uses transaction.

```ts
const user =
  // Optimistic prefetch (without transaction).
  await selectUser(db.user).findByOptional({ tgId })
    // If not found, run transaction and safely fetch-or-create.
    ?? await selectUser(db.user).findBy({ tgId }).orCreate({ tgId })
```

What am I missing? How is it different from simply running `find().orCreate()` from the safety viewpoint?

**Comment by romeerez** [comment]
I see, yes, you're right, I didn't follow the code very carefully.

**Comment by romeerez** [comment]
Thank you for the idea, I optimized `orCreate` and `upsert` to do a simple query first, as in your example, and then to do a fancy query with CTE statements, [docs](https://orchid-orm.netlify.app/guide/create-update-delete.html#orcreate).
