### ISSUE TITLE
How to select conditionally with correct types?

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#433]
I'm trying to select a certain column based on a JavaScript condition:

```ts
async getUser = (id: number, password: boolean) => {
    let query = db.user.find(id).select('name')

    if(password) {
        query = query.select('password')    
    }

    return await query
}
```

It works exactly as expected, but the types are incorrect; it only includes the columns of the select outside the if statement. Perhaps it should become a union; or even better, typescript should follow along with the condition and use the correct return type based on the parameters.

Or maybe there's another way to conditionally select, like Prisma?:

```ts
async getUser = (id: number, password: boolean) => {
    return await prisma.user.findUnique({
        select: {
            name: true,
            password
        },
        where: { id } 
    })
}
```

**Comment by IlyaSemenov** [comment]
This is what [modify](https://orchid-orm.netlify.app/guide/query-methods.html#modify) (#107) is exactly for:

```ts
const getUser = async (id: number, password: boolean) => {
  const user = await db.user.find(id).select("name")
    .modify((q: typeof db.user) => password ? q.select("password") : q)
  return user
}
```

`user` above is typed as:

```ts
const user: {
    name: string;
} | {
    name: string;
    password: string;
}
```

The callback argument needs explicit typing at the moment, I hope this gets resolved in #432.

**Comment by mordechaim** [comment]
I didn't know this exists. As the docs clearly say it's very tricky to use in Typescript, you need the `'key' in obj` check. A better type would be:

```
const user: {
    name: string;
    password: string | undefined;
}
```

In any case, maybe we could anyway fix conditional selects as in my first code snippet in the first comment? The runtime type is as expected, but typescript not.

**Comment by IlyaSemenov** [comment]
> or even better, typescript should follow along with the condition and use the correct return type based on the parameters.

I don't think that is possible to infer on the ORM level, but you can do that on your own:

```ts
const getUser = async <T extends boolean>(id: number, password: T) => {
  const user = await db.user.find(id).select("name")
    .modify((q: typeof db.user) => {
      const qWithPassword = q.select("password")
      const q1 = password ? qWithPassword : q
      return q1 as T extends true ? typeof qWithPassword : T extends false ? typeof q : typeof q1
    })
  return user
}

const user1 = await getUser(1, true) // typed as { name: string, password: string }
const user2 = await getUser(1, false) // typed as { name: string }
```

(But then you could even do without `modify`, you could just cast the result in your code in a similar fashion.)

**Comment by IlyaSemenov** [comment]
> password: string | undefined;

You could then do something like:

```ts
const getUser = async (id: number, password: boolean) => {
  const user = await db.user.find(id).select("name")
    .modify((q: typeof db.user) => password ? q.select("password") : q)
    .map(t => t as typeof t & { password?: string })
  return user
}
```

`user` will be:

```ts
const user: {
    name: string;
    password?: string | undefined;
}
```

**Comment by romeerez** [comment]
> Or maybe there's another way to conditionally select, like Prisma?:

I tried Prisma, the typing is wrong:

```ts
// getUser fn is from your example
const user = await getUser(123, false);
if (user) {
  // password was not selected, it is not defined
  const s: string = user.password; // no error, but it has to be
}
```

> you need the 'key' in obj check. A better type would be:

This conditional selects are in principle a source of bugs, and I think it would be better to sacrifice on DRY to some degree by not creating such conditional `getUser` helper functions, and instead explicitly writing the exact selection that you need in a certain case.

The suggested type isn't better, because if the password column is optional (what if you add oauth in the future, this can happen, and no need for password), then you cannot know if the password isn't present because it is NULL in db, or if you perhaps forget to select it.

```ts
type CurrentType = { name: string } | { name: string; password: string | null }

const user: CurrentType = { name: 'name' }

if ('password' in user) { // means we selected the password column
  if (user.password) { // means user has a password
  }
}
```

I'm not dissing on Prisma, it's great, but just want to point out that they have no choice really but to lack on type-safety in this case.

But in OrchidORM you can chain selects. You can define a function `getUser` which has selections, perhaps some logic, but it's important that the return type is always well-determined, cannot change:

```ts
// not async
const getUser = (id: number) => {
    return db.user.find(id).select('name')
}
```

And if you also need to select a password, you can add `select` to it:

```ts
// has both name and password
const userWithPw = await getUser(123).select('password')

// has just the name
const user = await getUser(123)
```

And all is type-safe.

> typescript should follow along

TypeScript cannot do that, and I'm 100% no other typed language can do that. Because the complexity for it to interpret your code like that is too big, and TS is already quite sluggish on large codebases. Can't wait till somebody rewrites it Rust, there is [stc](https://github.com/dudykr/stc) initiative, but even then interpreting the code like that is too much of a challenge for the type checker.

**Comment by mordechaim** [comment]
> And if you also need to select a password, you can add select to it:
>
> ```// has both name and password
> const userWithPw = await getUser(123).select('password')
> ```

I actually tried this, but the types did not include the password even after a chained selection.

This was actually the first code block in my first comment.

**Comment by mordechaim** [comment]
I see, if i chain without conditions it correctly types it. But if I select conditionally it doesn't even type it as a union.

So you say I shouldn't do it in first place, I get it.

**Comment by romeerez** [comment]
Kysely handles this better with `$if` statement (at the bottom): https://kysely.dev/docs/recipes/conditional-selects

The `$if` statement would be a nice addition.

The resulting type after `$if` will be also better:

```ts
type Selected = {
  name: string
  password?: string | undefined | null // undefined if not selected, null if the password is null in db
}
```

**Comment by mordechaim** [comment]
Understood, fair enough. I'm not requesting a feature, I was more of asking how to do it if an API exists for this.

**Comment by romeerez** [comment]
Good, anyway, the `$if` like in kysely is in the plans for future.

**Comment by romeerez** [comment]
I published a new `if` helper (borrowed from kysely): [docs for conditional select](https://orchid-orm.netlify.app/guide/query-methods.html#conditional-select). This should give a better TS type.
