### ISSUE TITLE
afterCreateCommit always selects all columns

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#434]
`afterCreateCommit()` accepts the list of columns to be selected, however, in fact it's disregarded and all columns are always selected:

```ts
await db.$transaction(async () => {
  await db.user.create(
    { name: "Alice", lastName: "Morgan" },
  ).afterCreateCommit(["name"], ([user]) => {
    console.log("Created user", user)
    // user is typed as { name: string }
    // but it prints: Created user { id: 1, name: 'Alice', lastName: 'Morgan' }
  })
})
```

Log:

```
(0.3ms) SAVEPOINT "1"
(1.7ms) INSERT INTO "user"("name", "last_name") VALUES ($1, $2) RETURNING "id", "name", "last_name" AS "lastName" ['Alice', 'Morgan']
(0.1ms) RELEASE SAVEPOINT "1"
Created user { id: 1, name: 'Alice', lastName: 'Morgan' }
```

<details>
<summary>Full reproduction</summary>

```ts
import process from "node:process"

import { createBaseTable, orchidORM, testTransaction } from "orchid-orm"

const BaseTable = createBaseTable({ snakeCase: true })

class UserTable extends BaseTable {
  override readonly table = "user"

  override columns = this.setColumns(t => ({
    id: t.serial().primaryKey(),
    name: t.varchar(),
    lastName: t.varchar(),
  }))
}

const db = orchidORM(
  { databaseURL: process.env.DATABASE_URL, log: true },
  {
    user: UserTable,
  },
)

await testTransaction.start(db)

await db.$query`
create table "user" (
  id serial primary key,
  name varchar not null,
  last_name varchar not null
)`

await db.$transaction(async () => {
  await db.user.create(
    { name: "Alice", lastName: "Morgan" },
  ).afterCreateCommit(["name"], ([user]) => {
    console.log("Created user", user)
    // user is typed as { name: string }
    // but it prints: Created user { id: 1, name: 'Alice', lastName: 'Morgan' }
  })
})

await testTransaction.close(db)
```
</details>

Repeats on:
- orchid-orm 1.35.0
- orchid-orm 1.38.0

**Comment by IlyaSemenov** [comment]
It just occurred to me that it works correctly with `db.user.insert(...).afterCreateCommit(...)`. Not sure if anything needs to be changed then.

**Comment by IlyaSemenov** [comment]
But, it also happens for `upsert()` so it rather should be fixed. There's no non-selecting counterpart for upsert, is there?

**Comment by romeerez** [comment]
This is normal for the first query example, because `create` selects all columns, and `afterCreateCommit` doesn't mind.

> // user is typed as { name: string }
> // but it prints: Created user { id: 1, name: 'Alice', lastName: 'Morgan' }

I didn't strip the excessive fields because I supposed they won't bother. Though, this can be stripped, to be more precise.

> But, it also happens for upsert() so it rather should be fixed.

This may be a bug.

**Comment by romeerez** [comment]
I drastically updated all the internals around this case, should work as expected.
