### ISSUE TITLE
Bytea columns returned from joins are strings

### ISSUE THREAD

**Issue by kvcpr** [romeerez/orchid-orm#437]
When joining a table with a `bytea` column, this column is returned as a hex string instead of a node bytes.

Example:
```
const items = await this.db.items.select({
tableWithByteaColumn: (q) => q.tableWithByteaColumn,
});
```

`items[0].tableWithByteaColumn.byteaColumn` should be node bytes, but it's `hex` string.

Temp fix:
Add in your `baseTable`:
```ts
		bytea: () =>
			t.bytea().parse((item: Buffer | string) => {
				if (typeof item === 'string') {
					return Buffer.from(item.replace('\\x', ''), 'hex');
				}

				return item;
			}),
```

**Comment by romeerez** [comment]
Thank you for reporting, I published a fix for this.
