### ISSUE TITLE
[1.38.2] `upsert` is broken

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#438]
In the latest OrchidORM 1.38.2 `upsert` is broken for me. Trying to upsert in my code throws this error:

```
node_modules\pqb\dist\index.mjs (4695:1) @ then
 ⨯ Internal error: error: WITH query "c" does not have a RETURNING clause
```

I tried to reproduce it on a clean project but it works in isolation so I'm not sure what exactly triggers it. But I do see a recent commit that touched `upsert` https://github.com/romeerez/orchid-orm/commit/2b3ae9b0c7c4334bbb850b78c94a8e82690e6de7.

My code works perfectly in Orchid 1.38.1

**Comment by romeerez** [comment]
Does your code has `select`, `get`, `pluck`, `rows`, something like that?
Because the error suggests that the bug is related to `RETURNING`, so to what you're selecting from the upsert.

**Comment by mordechaim** [comment]
This is the query verbatim

```ts
await db.facilityRole.findBy({ facilityId, roleId }).upsert({
        data: {
            billRate,
            payRate
        },
        create: {
            roleId,
            facilityId,
            billRate,
            payRate
        }
    })
```

No computed fields on this table, just a simple join table with 4 columns `roleId`, `facilityId`, `billRate` and `payRate` plus `id` and timestamps.

The role and facility columns have foreign keys.

**Comment by romeerez** [comment]
Looks like it's not meant to have a `returning` at all and that's a direction to look for the bug.

I'll fix on the next occasion, and for now downgrade the version temporary.

**Comment by mordechaim** [comment]
One more detail, it only happens if the record is not found and a new is created

**Comment by romeerez** [comment]
I published a fix, but I'm not sure if that works for you.

So if this doesn't help, send here SQL log, and maybe how FacilityRole table looks like in the code, perhaps there are some special "after create" hooks, or default selections, something like that. SQL log would help.

**Comment by mordechaim** [comment]
Works as expected now, thanks @romeerez
