### ISSUE TITLE
Don't apply map for .count() query

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#440]
```ts
const userQuery = db.user.select("name").map(u => ({ ...u, online: true }))
const userCount = await userQuery.count()
```

The type of `userCount` is `number`, but the runtime value is `{ online: true }`. I believe the aggregations like this should ignore `.map()` altogether.

---

For the time being, I came up with this workaround using the undocumented `"transform"` clear:

```ts
const userQuery = db.user.select("name").map(u => ({ ...u, online: true }))
const userCount = await userQuery.clear("transform" as ClearStatement).count() // number, both type and runtime
```

Context: #439.

**Comment by romeerez** [comment]
Done, now `count` and all the similar methods will discard `map` and `transform` effects.
