### ISSUE TITLE
Query array contains a certain value

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#441]
How would I query the equivalent of this SQL?

```sql
select * from blog
where 'tech' = any(tags)
```

Where `tags` is `text[]`

**Comment by IlyaSemenov** [comment]
You probably know this already, but just in case, one can always fall back to raw SQL which is still perfectly readable:
```ts
await db.blog.whereSql`${tag} = any(tags)`
```

**Comment by mordechaim** [comment]
Exactly what I currently do, just wanted to know if the orm supports it.

**Comment by romeerez** [comment]
Added [array type operators](https://orchid-orm.netlify.app/guide/where.html#array-operators):
- `has`, `hasEvery`, `hasSome` is based on what Prisma has;
- `containedIn` to cover `arrayContained` from Drizzle;
- `length`: you can filter for empty arrays with `length: 0`, and you can use numeric comparisons such as `length: { gt: 3, lt: 5 }`.
