### ISSUE TITLE
Support database views

### ISSUE THREAD

**Issue by romeerez** [romeerez/orchid-orm#47]
Use case: user already has db views, no need to create them or manage them, only to be able to query them.

I imagine it to be defined in a similar way as tables are, but to exclude methods for updating/creating/deleting.

**Comment by romeerez** [comment]
Nothing special is needed to query views, they can be defined in the app in the exact same way as normal tables are defined, with the name of the view in the `table` property, and column definitions, and they can also have `relations`.

Added ability to create and drop views in migrations: [here is a doc link](https://orchid-orm.netlify.app/guide/migration-writing.html#createview-dropview).

`db pull` now can load views from db into generated migration.

That's all for the views for now.

**Comment by mordechaim** [comment]
With the new generator, It it possible to reconsider supporting views in the ORM?

I can model a table TypeScript definition and add to generateIgnore, but you can still call `create` which would fail at runtime.
