### ISSUE TITLE
Support for manual transaction control

### ISSUE THREAD

**Issue by jd4n14** [romeerez/orchid-orm#50]
First of all, thank you for creating and maintaining this fantastic library! It has been very helpful for working with PostgreSQL in my TypeScript projects.

Currently, OrchidORM handles transactions automatically using the `$transaction` method, which is a great feature. However, I have a use case where I need more manual control over my transactions, specifically using the `BEGIN`, `COMMIT`, and `ROLLBACK` statements directly.

Here's an example of what I'm trying to achieve:

```ts
const connection = await db.$transaction.getConnection();
try {
  await connection.query('BEGIN');
  await db.someTable.where(...conditions).update(...data).transacting(connection);
  await connection.query('COMMIT');
} catch (error) {
  await connection.query('ROLLBACK');
} finally {
  await connection.release();
}

```

I couldn't find any documentation or examples demonstrating how to perform transactions this way using OrchidORM. Could you please provide some guidance or examples on how to handle transactions manually using the library? If it's not currently supported, would you consider adding this feature in a future release?

**Comment by romeerez** [comment]
I'm very glad this ORM is already helpful for your projects!

Manual control of transactions isn't yet supported, I'll add it to my todo.

Wondering, what is the use case? Because the example you gave is the way it's already working under the hood: commit when no error, rollback on error, and release in both cases.

**Comment by romeerez** [comment]
So if manual control isn't really needed I won't add it, but feel free to reopen if such use case appears!
