### ISSUE TITLE
rake-db addTo

### ISSUE THREAD

**Issue by quinnvaughn** [romeerez/orchid-orm#51]
The new syntax for addTo on rake-db doesn't seem to be working properly. I have not yet tried other commands, but I tried every variation of `addTo[Table]`, `addTo [Table]`, etc., and it fills in`changeTable(tableName)`. I mean literally the string `tableName`, not the name of the table ie `changeTable('user')`, so it seems like it's not getting the arg correctly from the command line. If I'm doing it wrong... then the wording is very confusing and needs to be made more clear. Either way I would use [] as args in the text on the command line and not *, which seems to be much more normal cli convention to me.

**Comment by quinnvaughn** [comment]
Ok I just tested create[Table] and that seems to work fine.

Another question I have related to this is, if I have varchar in the cli (like for my id) how can I set the default amount, or is there no way to do that on the cli and I just have to add it manually? It did not take varchar(36).

**Comment by romeerez** [comment]
For reference, docs are here: [generate migration](https://orchid-orm.netlify.app/guide/migration-commands.html#generate-migration),

One of the names it should parse is `add${any string}To${table name}`, I should add examples to this list, I mean here `addColumnsToMyTable` - it should generate a migration with

```ts
db.changeTable('myTable', (t) => ({
  //  ...add columns
}))
```

>  Either way I would use [] as args in the text on the command line and not *

Could you explain because I'm not following which [] and which * do you mean?

>  if I have varchar in the cli (like for my id)

The doc says to take varchar(36) into quotes, are you providing it in the quotes and it doesn't work?

btw, postgres [docs suggest against varchar(n)](https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_varchar.28n.29_by_default)

**Comment by quinnvaughn** [comment]
If you look at the text the cli gives you, it is using stars and you should use brackets to indicate an arg. 
`add[Column]To[Table]` like that.

**Comment by quinnvaughn** [comment]
```
New migration file arguments:
- (required) first argument is migration name
  * create*               template for create table
  * change*               template for change table
  * add*To*               template for add columns
  * remove*From*          template for remove columns
  * drop*                 template for drop table
  ```

**Comment by romeerez** [comment]
I see, okay sure, let it be `add[any string]To[table name]`, I'll update and re-check that it works as expected.

**Comment by quinnvaughn** [comment]
I'd probably just call it column instead of any string as that's what you're actually doing, right?

**Comment by romeerez** [comment]
It's any string because, for example, `addFewColumnsToMyTable`: this will generate a file with the following:

```ts
change(async () => {
  await db.changeTable('myTable', (t) => ({
    // nothing here
  }))
})
```

Because if you want to add a few columns, it would be a too-long migration name. So I thought that it be better to leave migration names without specific column names.

**Comment by quinnvaughn** [comment]
...Wouldn't you just use change[Table] then?

**Comment by romeerez** [comment]
It is already there:

> change${table name} for changing a table

The name of the migration could be any string at all, it's not required to follow the template. This template is a minor bonus feature so the cli tries to guess by name what's expected and tries to help a little bit with the content. But helping only a little bit, you have to edit and write migration by hand anyway.

In the distant future migrations could be generated from model files, so this cli will be less important.

**Comment by quinnvaughn** [comment]
...What? I was saying if you are using add[]To[] you're probably just adding *one* column, otherwise just use change[Table]. Yet you mentioned add[FewColumns]To[Table]. I was saying when would you ever add multiple columns via that command? Which is why I was suggesting it just be add[Column]To[Table] because there is no reason you'd ever want to use it for more than one column.

**Comment by romeerez** [comment]
For instance, "addDetailsToProduct", "addSupplierInfoToProduct", "addLegalInfoToUser", etc.

"addSupplierInfoToProduct" is a more descriptive name than just "changeProduct", so this "add something to table" form may be preferred.

**Comment by quinnvaughn** [comment]
That's fair I guess.

**Comment by romeerez** [comment]
I improved [docs](https://orchid-orm.netlify.app/guide/migration-commands.html#generate-migration) to have `add[something]To[table]` and to have examples.

Also removed the feature of command line arguments being parsed into columns, because it's not really useful but it added confusion.
