### ISSUE TITLE
[Suggestion] Using Zod Schemas to validate requests

### ISSUE THREAD

**Issue by leifniem** [romeerez/orchid-orm#52]
Hello again :)

i'm currently messing around with a koa server and the generated Zod schemas and ran into a problem that i think might come up for other people too:

I am building a route to query filtered results from a table by the means of the requests body, which then is getting a type by using `z.infer` on the schema. When encountering a column that consists of `timestamp` the body values are `Date` objects, while the parameter for `findBy` requires a string.

Since i'm primarily a frontend dev i can't tell if this goes against best practices, but my instinct tells me not having to serialize / deserialize data for validation and using the db as a single source of truth might be something useful.

Happy to hear thoughts on it :)

**Comment by leifniem** [comment]
I'd have totally taken no for an answer, so thanks a lot for all the effort :)

**Comment by romeerez** [comment]
I'm all in for improving DX, and you're really helping with it by pointing out where to draw attention, so thank you for this!

I published `schema-to-zod` with a little improvement: now it can accept `number` | `string` | `Date` to parse a date or a timestamp.

Frontend can send a date or timestamp in the format `date.toISOString` or `date.getTime()` and zod schema will first convert it to `Date` and then validate that it's a valid date. It is simply `new Date(input)` conversion so any format that it can accept will work.

**Comment by leifniem** [comment]
In that case: very much happy to help.
Thank you again :)
