### ISSUE TITLE
Can't set up quickstart

### ISSUE THREAD

**Issue by Superchig** [romeerez/orchid-orm#55]
Hi, thanks for creating this library!

I can't seem to follow the quickstart from the documentation. When trying to use `npx orchid-orm@latest`, I get this error:

```
root@38bf68c725c0:/# npx orchid-orm@latest
Need to install the following packages:
  orchid-orm@latest
Ok to proceed? (y) y
sh: 1: orchid-orm: not found
```

I get this error both on my Arch Linux machine and in a minimal Ubuntu image (see Dockerfile below):

```dockerfile
FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y npm --no-install-recommends

WORKDIR /root

CMD ["/bin/bash"]
```

**Comment by romeerez** [comment]
Thanks for reporting, looks like something in the build process was broken, I'll fix it asap.

I used Arch too btw, switched to Arch-based Manjaro, not sure if it counts as Arch.

**Comment by romeerez** [comment]
Fixed and tested, `npx orchid-orm@latest` should be alright now.
