### ISSUE TITLE
$transaction might be broken

### ISSUE THREAD

**Issue by quinnvaughn** [romeerez/orchid-orm#56]
I upgraded my rake and orchid to the latest version and now my $transaction isn't working, it is just getting the db as type any.

**Comment by quinnvaughn** [comment]
Update: It seems like you're not passing in the new transaction db to the callback anymore? Example code looks as follows.
```
const result = await db.$transaction(async () => {
      const sender = await db.user.find(fromId)
      const senderRemainder = sender.balance - amount
      if (senderRemainder < 0) {
        throw new Error('Sender does not have enough money')
      }
      
      await db.user.find(fromId).decrement({
        balance: amount,
      })
      await db.user.find(toId).increment({
        balance: amount,
      })
      
      return senderRemainder
    })
  } catch (error) {
    // handle transaction error
  }
```

**Comment by romeerez** [comment]
> Update: It seems like you're not passing in the new transaction db to the callback anymore

Yes, sorry for the breaking changes, it happens and some things will continue to get changed in the future.

Transactions were changed after [this issue](https://github.com/romeerez/orchid-orm/issues/22).

Basically, now just use the `db` instance you already have and that's all, remove the callback argument.
