### ISSUE TITLE
Support computed (virtual) columns

### ISSUE THREAD

**Issue by romeerez** [romeerez/orchid-orm#59]
From here: https://github.com/romeerez/orchid-orm/discussions/58

I have a firstName and lastName column in table, I want to calculate a fullName property on the fly.

Computed column should support the following things:

Selecting raw SQL:

```ts
class Table extends BaseTable {
  columns = this.setColumns((t) => ({
    firstName: t.text(),
    lastName: t.text(),
    // combine first and last name on db side, it should be more efficient than doing so on JS side.
    fullName: t.text().computed(t.raw(`"firstName" || ' ' || "lastName"`)),
  }));
}
```

Selecting dynamic raw SQL, what if we want the field to be selected differently based on some variable? Imagine we have a multi-language web site and we want to fetch a product name, db is storing "name_en", "name_uk", "name_fr" and others, and we could define a column `name` to load a translated column:

```ts
// somewhere in the app:
const asyncLocalStorage = new AsyncLocalStorage();

(req, res) => {
  const result = await asyncLocalStorage.run(req.params.locale, () => {
    return db.product.select('name') // select name
  })
}

name: t.text().computed(() => {
  const locale = asyncLocalStorage.getStore();
  return t.raw(`name_${locale}`) // name reveals to name_*locale*
})
```

Would be nice to be able to have a full query builder to define queries, rather than just a raw SQL. But I think it's not possible for this case, so let it be just raw SQL, anyway computed columns aren't meant to be based on complex queries.

Columns that are calculated on JS side are more complex to design, need to think about it. Because:
- such columns depend on other columns, when you're selecting `fullName` it should ensure that `firstName` and `lastName` were selected from db
- it cannot be defined safely inside `setColumns` callback because at this point the columns aren't defined, and the callback cannot know the type of `firstName` and `lastName`, the callback cannot even know if such columns exist on this table.

[Here is a draft](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBCkFNoG8BQ0PWAexAVwFsA7CALmjyIGsjsB3I1dTAhAFwAtsATAHmczQAyghAAzaAgAebBEW4xOASwgAaAZgAiCAA6SZchdCoIAntgkjxAbQDkOfMQi2AuusEYAggCcA5vtl5GAAKMD9yAAUlYCpeKzE7B0ISV1VobR0APjSAOjyw3zJoMCJTaxcASmgAXkzoADdsJW53Dx9CgMMYErKXGugIsLBWWW8IXna66UCjax7cvKUiMQRvaAAlBAg2PoB+Da22aHIiBHrVjUzgjUFlIvjWj2huXSKM8sePAvJ2z4ryYJ5HIFIrtCBVWoHNh4bxEAAqph0CAmfjqaCe3nYMKIxT8xW6pQ0AF9UCTUKBIDAAMLgKCdIJwRAoDRJJz9dFPaDNcgARgATABmT6Cby4BDkWzbbxLXy2T5kwQjLhGarMznQDiQdZi8h3HJKnjBOyikAIVLQYKYnDeFrQE3i6BSmX-aAAI2wYpKNTRN05VuwNpy9ugAHoQ462NKiL5fRisbC7Qhrdwg2KatVVfbY9AiRV1NmVJ5uAQlrqOCp9exlUbbPbzZakwHuC73Z6cZCOeqMGHE8muTBtgGENxoLICDoA2FTI7sKw6BxVgg0iUR0o2JLoDpKcPR9hoAADTUQbWm-dc8cgaJrkCmbOCHs4cd4WQpo8npAqYrQOjeMA6JFrGE2CUCOb5ppwYBHJ+SwAFZJmwMqjguvZNpuQwjBcXaYJi0IJnqBoKDkYGmsEthgMWSy2BU2a5vKTAkkAA) for how the methods could be defined on the table.

**Comment by bingtsingw** [comment]
Do you have plans to implement computed columns recently, I'm going to release a new app version these days. If three is no  plan, I'm take some other workarounds.

**Comment by romeerez** [comment]
This is a big and complex feature that I didn't start yet because of other things, so it won't be ready soon. Happy release to you!

**Comment by bingtsingw** [comment]
Hi, any plan to work on this feature?
@romeerez

**Comment by romeerez** [comment]
I'll prioritize it and try doing it in the next couple of weeks.

**Comment by romeerez** [comment]
Ready! Now we can define [computed columns](https://orchid-orm.netlify.app/guide/orm-and-query-builder.html#computed-columns) in table classes, each computed column is defined with a raw SQL, and it can be generated dynamically when the query is performed.

In the description, I also was thinking about virtual columns on JS side:
> Columns that are calculated on JS side are more complex to design, need to think about it.

But it doesn't seem to make sense to add them, writing logic outside table classes is still a better option.

**Comment by bingtsingw** [comment]
JS side computed columns can be useful sometimes, looking forward to this feature. 

As of API design, it can borrow some ideas from lifecycle hook, witch should explicitly define the dependency columns
