### ISSUE TITLE
repeated migrations with rake-db?

### ISSUE THREAD

**Issue by bonesoul** [romeerez/orchid-orm#6]
I'm switching to rake-db from db-migrate and I wonder if there is any kind of migrations that always get executed in each run.

**Comment by romeerez** [comment]
Could you clarify the use case?

There is no such thing currently as repeated migrations, I can add but need to better understand what is it for.

**Comment by romeerez** [comment]
I was thinking about how it's going to handle things like stored procedures, views, etc. Is it what you're looking for?

In dev mode, the server is restarted on every change, and I'd like to do something smart to **not** run dozen of queries like `create procedure if not exists` each time.

I'm still thinking about how it would be better to implement it.

Let me know if you want first-class support of stored procedure or view or other database-specific features, and I'll prioritize it.

**Comment by bonesoul** [comment]
well let me explain the use case (and I've seen this implemented in other migration packages before: https://elanderson.net/2020/08/always-run-migrations-with-dbup/  https://github.com/DbUp/DbUp/issues/206).

Let me explain my use case. I'm developing a website for world of warcraft (https://wowtrack.gg/) and game gets update regularly. Basically I'm parsing the game files and seeding them.

The thing is that with each game version update, I need to run my tools to reparse all the game data and update my database with latest info. As you may expect, for most of time there is huge amount of changes that practically I can't just manually find them and create a new migration. So my strategy is that with each game version update, I dump all the game data and want to create an always run migration that will just push the latest changes.

**Comment by romeerez** [comment]
`rake-db` is executed via running the user-defined script, so you have

```json
{
  "scripts": {
    "db": "ts-node src/scripts/db.ts"
  }
}
```

And run it with `npm run db migrate`.

You can put the needed logic to this `db.ts` script to execute custom queries every time when this script is called with `migrate`:

```ts
import 'dotenv/config';
import { rakeDb } from './src/rakeDb';
import { createDb, columnTypes } from 'pqb';
import { appCodeUpdater } from '../orm/src';

const databaseURL = process.env.DATABASE_URL;
if (!databaseURL) {
  throw new Error('DATABASE_URL is missing in .env');
}

const options = {
  databaseURL,
};

rakeDb(options, {
  migrationsPath: 'migrations',
}).then(async () => {
  const command = process.argv[2];
  if (command === 'migrate') {
    const db = createDb({ ...options, columnTypes });

    await db('table').createMany([
      {
        key: 'value 1',
      },
      {
        key: 'value 2',
      },
      {
        key: 'value 3',
      },
    ]);

    await db.close();
  }
});
```

I think that should be enough, let me know if any questions or suggestions for how to improve.

I could add callbacks to the `rakeDb` function to improve this a bit, like this:

```ts
rakeDb(options, {
  afterMigrate: (db) => {
    // use db instance to do the stuff
  }
})
```

**Comment by bonesoul** [comment]
well after some though on it i decided to go a different route.

for every game version ill be creating migration files

- 20230127141259_wow_10.0.0.5.ts
- 20230127141259_wow_10.0.0.2.ts

and basically they will be calling a common seed function I'll be creating. This seems to be an easier way to go.

**Comment by romeerez** [comment]
Yeah, that also works, if storing every wow file in migrations is preferred.

But if you'd like to have only one last wow file, then it's better to extend the script.

**Comment by romeerez** [comment]
I'll be doing some special functionality for seeds in the future, so to be more precise, let it be an `afterMigrate` callback.

So I'll implement this sometime later, and in the meantime, you can use `rakeDb(...).then(async () => code here)` as in the example above

**Comment by bonesoul** [comment]
Okay thanks, looking for the seed functionality too :)

**Comment by romeerez** [comment]
Added callbacks, [here are the docs](https://orchid-orm.netlify.app/guide/migration-setup-and-overview.html#before-and-after-callbacks)
