### ISSUE TITLE
running test error

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#60]
When running `pnpm run check` under `packages/core`, there seems to have an error
<img width="940" alt="image" src="https://user-images.githubusercontent.com/10382462/233822960-9c858285-ca29-420b-b2de-2f9617925c30.png">

**Comment by romeerez** [comment]
Could you pull the latest and check again? I had this error yesterday and fixed it, should be fine now.

**Comment by romeerez** [comment]
Are you going to contribute some feature? :)
If so, feel free to ask anything, I've still didn't write a contribution guide, commenting the code is still in plans, and the code is really complex to follow.

**Comment by bingtsingw** [comment]
> Could you pull the latest and check again? I had this error yesterday and fixed it, should be fine now.

It seems my codebase is already the newest, but I still has this error.

**Comment by romeerez** [comment]
I just cloned it to test from scratch and it works fine on my end:

```sh
git clone git@github.com:romeerez/orchid-orm.git
cd orchid-orm
pnpm i
# enter PG_URL and MYSQL_URL
vim .env
# started pg and mysql databases
# the check is successful
pnpm check
```

**Comment by bingtsingw** [comment]
> Are you going to contribute some feature? :) If so, feel free to ask anything, I've still didn't write a contribution guide, commenting the code is still in plans, and the code is really complex to follow.

I'm just looking around the source code to see how far I can understand it, :)
I'm interested in contributing but don't know where to start, maybe I'll first go to use it in my project to see if  there are any bugs or pain points

**Comment by bingtsingw** [comment]
> I just cloned it to test from scratch and it works fine on my end:
> 
> ```shell
> git clone git@github.com:romeerez/orchid-orm.git
> cd orchid-orm
> pnpm i
> # enter PG_URL and MYSQL_URL
> vim .env
> # started pg and mysql databases
> # the check is successful
> pnpm check
> ```
> 
> So I don't know why it could happen on your end, if the sources are fresh. You can run `pnpm check` inside package folders individually. (`run` isn't necessary by the way)

I do the same but still has errors, I see the is `github ci` green, so it‘s most likely my environment problem,  which `node` and `pnpm` version did you use?

**Comment by romeerez** [comment]
Right, that's might be the reason.

I'm using node v18.12.1 (just any 18 or above should work)

pnpm v7.4.1

**Comment by bingtsingw** [comment]
I don't know why, but after I delete every `await query;` statements in [timestamps.test.ts](https://github.com/romeerez/orchid-orm/blob/main/packages/core/src/columns/timestamps.test.ts), it goes green.

**Comment by romeerez** [comment]
And what node and pnpm do you use? So it's not about the versions?

**Comment by bingtsingw** [comment]
I tested on `node v16.20.0` `node v18.15.0` `pnpm v7.32`,all the same error.
And removes `await query;` can solve it

**Comment by bingtsingw** [comment]
https://github.com/romeerez/orchid-orm/blob/80d3318cef7b5905b8a50292fd8cc90545a295a7/.github/workflows/tests.yml#L69-L78

I go to `packages/rake-db` and run
```
pnpm run db create
pnpm run db migrate
```

Everything goes green, no matter which node version I use

**Comment by romeerez** [comment]
Ah, cool, that's right, need to create a db and run migrations. Jest error is very confusing.
