### ISSUE TITLE
`timestamp()` and `timestamps()` column do not accept `Date` by default

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#61]
```
export class test extends BaseTable {
  columns = this.setColumns((t) => ({
    id: t.cuid(),
    time: t.timestamp(),
    ...t.timestamps(),
  }));
}

db.test.find('xxx').update({
  updatedAt: new Date(),  // type error
  test: new Date(),  // type error
});
```
<img width="756" alt="image" src="https://user-images.githubusercontent.com/10382462/233823278-21b3d6d5-6c2d-4f2f-b4de-16fc450295e1.png">

Unless I set the column `asDate()` explicitly, then I can update it with `Date` object, I don't know if it's a bug or design choice.

I think it maybe a bug because I see the same type error in a test file:

https://github.com/romeerez/orchid-orm/blob/80d3318cef7b5905b8a50292fd8cc90545a295a7/packages/core/src/columns/timestamps.test.ts#L26

**Comment by romeerez** [comment]
Seems to be a bug, thanks for pointing!

**Comment by romeerez** [comment]
It was a bug in the `update` type, fixed and published `pqb` and related packages.
