### ISSUE TITLE
compile errors when use it under pnpm workspaces

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#63]
reproduce repo: https://github.com/bingtsingw/orchid-type-error

**Comment by bingtsingw** [comment]
My projects have used pnpm workspace for a long time, it works well for other libraries, so I guess `orchid` may need extra configurations to setup.

**Comment by romeerez** [comment]
You're using `tsup` to start it, this is a tool for building libraries, and the error happens on generating dts files.

The error says:

> The inferred type of 'BaseTable' cannot be named without a reference to '.pnpm/pqb@0.11.8/node_modules/pqb'. This is likely not portable. A type annotation is necessary.

So it cannot infer a type of BaseTable. The column types here depends on a type that is exported from `orchid-core` but not exported, only used in `orchid-orm`. To resolve this, need to somehow change exports of the types.

Are you building a library? If no, use ts-node, it works fine for me.

**Comment by bingtsingw** [comment]
I do not build public libraries, but only build private internal packages under `pnpm monorepo`, it seems I can just configure `dts: false` in `tsup.config.ts`

**Comment by bingtsingw** [comment]
Some of my apps do not support es modules, it works well in dev but throw errors(`Cannot use import statement outside a module`) after deploy.
So I'm used to compiling subpackages with `tsup`, I'm happy to know if there are simpler ways.

**Comment by romeerez** [comment]
I'm not familiar with `tsup`, all the different bundlers and compilers allows you to set a config to compile to esm or commonjs modules. TS compiler by itself can do that with `"module": "commonjs"`.

If after deploy the node version doesn't support `esm` imports, why use it locally? It seems brittle to have different module systems in dev and in the prod.
