### ISSUE TITLE
[bug] `t.name('xxx')` not work

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#65]
`t.name()` should overwrite column name, but it seems to do nothing

**Comment by romeerez** [comment]
`t.name` specifies the column name in the database.

Here `one` is column name in the app, and `two` is column name in db:

```
one: t.name('two')
```

How are you using it?

**Comment by bingtsingw** [comment]
I'm using it exactly this way, but I log the sql query, it was "one", not "two"

**Comment by romeerez** [comment]
I need some code for reproduction from you, because there are a lot of tests for this so it should work.

**Comment by bingtsingw** [comment]
This confused me too, I see and run tests in `pqb` and `orm`, they are fine, but It does not work in my project, I'll create a repo to see if I can reproduce

**Comment by bingtsingw** [comment]
I think I have found the magic: https://github.com/bingtsingw/orchid-reproduce

Do I use `varchar` wrong? Or is this a bug?

**Comment by romeerez** [comment]
Yes, there is such catch, because the `name` is passed in a `this`:

```ts
columnTypes: (t) => ({
  ...t,
  // name doesn't work
  varchar: (length: number = 255) => t.varchar(length),
  // works:
  varchar(length: number = 255) {
    return t.varchar.call(this, length)
  }
}),
```

I wish that this would not be required, but I don't know yet how to do it in a different way.

**Comment by bingtsingw** [comment]
Oh, I missed `call(this)`

I remember this confused me when I looked through the docs, sometimes I saw there is no `call(this)`

https://github.com/romeerez/orchid-orm/blob/c3da007157f712e62ae3c7e9b3b650f84dad793e/docs/src/guide/columns-overview.md?plain=1#L76-L88
`primaryKey()` do not have a `call(this)`

https://github.com/romeerez/orchid-orm/blob/c3da007157f712e62ae3c7e9b3b650f84dad793e/docs/src/guide/columns-overview.md?plain=1#L96-L103
No `call(this)` in this example

So I'm quite confused on when should I use `call(this)`, is there a RULE or just write it for every column types in `createBaseTable`

**Comment by romeerez** [comment]
I have one idea of how to workaround this.

Pseudo-code (for myself to use it later):

```ts
// store the name value somewhere globally:
let name: string | undefined

// t.name will store the name in global variable
t.name = (n: string) => {
  name = n
}

// column types will consume the name and remove it globally
columnTypes.integer = function () {
  // save global name to this
  this.name = name
  
  // clear global name
  name = undefined
}

columns = this.setColumns((t) => ({
  // name = undefined, `one` has no name
  one: t.integer(),
  
  // t.name is setting name globally, integer uses it and immediately clears it
  two: t.name('name').integer(),
  
  // name = undefined again
  three: t.integer(),
}))
```

**Comment by romeerez** [comment]
> So I'm quite confused on when should I use call(this), is there a RULE or just write it for every column types in createBaseTable

When defining `columnTypes` overrides, use `call(this)` always. It is missed in the docs for `id` because it's easy to forget to use it, so I'm going to make this redundant later as in the idea above.

**Comment by bingtsingw** [comment]
This seems to be a workaround for `t.name()` only, I think we may just keep the consistency on **wrting call(this) for `columnTypes` overrides everywhere** strategy and give the right/wrong examples until we could find a perfect way to remove all `call(this)` bindings.

```
columnTypes: (t) => ({
  ...t,
  // wrong: use arrow functions
  varchar: (length: number = 255) => t.varchar(length),

  // right: use this bindings
  varchar(length: number = 255) {
    return t.varchar.call(this, length)
  }
}),
```

`this` bindings are truly annoying, not only in the docs, I found lots of `=>` in source code too.

<img width="897" alt="image" src="https://user-images.githubusercontent.com/10382462/234220308-7b1c50de-b3c3-4f4e-98c3-20ba27b2518b.png">

**Comment by bingtsingw** [comment]
I found another issue related to `this` bindings
<img width="533" alt="image" src="https://user-images.githubusercontent.com/10382462/234225368-a9c666bf-f691-4d80-b859-4b37721b1f66.png">
The return type should be `VarCharColumn<number>`, `VarCharColumn<number|undefined>` breaks some typings

**Comment by bingtsingw** [comment]
Thank you, really happy to see `call(this)` goes away 👍
