### ISSUE TITLE
Git tags for new releases

### ISSUE THREAD

**Issue by Superchig** [romeerez/orchid-orm#70]
Could each commit for a new release be given a git tag?

For example, node.js version 20.0.0 has a [tag](https://github.com/nodejs/node/tree/v20.0.0).

This would be handy for looking up the documentation for older versions.

**Comment by romeerez** [comment]
That's a good thing, I'll try to add tags to the existing history and automate tagging for further commits.

This repo has multiple packages, I'm thinking to base the tags on the `orchid-orm` version.

**Comment by romeerez** [comment]
Pushed tags for the existing history, each tag represents a published version of `orchid-orm`.

**Comment by Superchig** [comment]
Basing tags on the `orchid-orm` version makes sense to me. Thanks!

**Comment by romeerez** [comment]
Tagging is done by [changesets](https://github.com/changesets/changesets) and it creates a tag for each package, and once I push an update to the core then all the packages are tagged and published.

Now this process is fully automated with GitHub CI.

I only couldn't figure out how to create GitHub releases yet.
