### ISSUE TITLE
Ordering on select sub-query

### ISSUE THREAD

**Issue by rdunk** [romeerez/orchid-orm#72]
I'm not sure if this is a result of recent changes, but I've run into an issue where ordering on a select sub-query seems to output SQL which produces an error:

Example query:
```sql
db.person
  .select('id', {
    trackCount: (q) =>
      q.credits.join('track', (q) => q.whereExists('active')).count(),
  })
  .order({ trackCount: 'DESC' })
```

This outputs the following ORDER BY command:
```sql
SELECT
  "person"."id",
  "trackCount".r "trackCount"
FROM
  "person"
  LEFT JOIN LATERAL (
    SELECT
      count(*) r
    FROM
      "trackCredit" AS "trackCount"
      JOIN "trackRevision" AS "track" ON "track"."id" = "trackCount"."trackId"
        AND EXISTS (SELECT 1 FROM "track" AS "active" WHERE "active"."revisionId" = "track"."id" LIMIT 1)
    WHERE
      "trackCount"."personId" = "person"."id") "trackCount" ON TRUE
ORDER BY row_to_json("trackCount".*) DESC
```
Which results in an error `could not identify an ordering operator for type json`. Switching it to just the alias seems to resolve it.

```sql
ORDER BY "trackCount" DESC
```

**Comment by romeerez** [comment]
Thanks for pointing, the error is here `ORDER BY row_to_json("trackCount".*) DESC`, I'll fix

**Comment by romeerez** [comment]
I published a fix for it, let me know if it works

**Comment by rdunk** [comment]
Yep, that's fixed it, thanks!
