### ISSUE TITLE
Feature request: Vite support

### ISSUE THREAD

**Issue by Superchig** [romeerez/orchid-orm#74]
Could the `rake-db` package support ESM?

I'm working on a little project that uses vite and SvelteKit, and I'm using [vite-node](https://www.npmjs.com/package/vite-node) rather than ts-node to run CLI scripts. I use vite-node in order to access path aliases that are provided by SvelteKit (i.e. [`$app/environment`]( https://kit.svelte.dev/docs/modules#$app-environment)).

When trying to use `rake-db` with `npm run db migrate`, I get an error that seems to be related to the use of CommonJS modules:

```
> financial-tracker@0.0.1 db
> vite-node src/lib/server/orchid/dbScript.ts -- migrate

file:///home/chiggie/projects/financial-tracker/node_modules/rake-db/dist/index.mjs:35
        require(path2);
        ^

ReferenceError: require is not defined
    at file:///home/chiggie/projects/financial-tracker/node_modules/rake-db/src/common.ts:94:9
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at file:///home/chiggie/projects/financial-tracker/node_modules/rake-db/src/commands/migrateOrRollback.ts:136:15
    at Adapter.transaction (file:///home/chiggie/projects/financial-tracker/node_modules/pqb/src/adapter.ts:111:18)
    at processMigration (file:///home/chiggie/projects/financial-tracker/node_modules/rake-db/src/commands/migrateOrRollback.ts:130:16)
    at migrateOrRollback (file:///home/chiggie/projects/financial-tracker/node_modules/rake-db/src/commands/migrateOrRollback.ts:79:15)
    at runCommand (file:///home/chiggie/projects/financial-tracker/node_modules/rake-db/src/rakeDb.ts:45:7)

Node.js v18.14.0
```

By the way, thanks for working on this project! The API is super ergonomic, and I love the type support.

**Comment by romeerez** [comment]
I figured out how to resolve this, I'll update the docs for this tomorrow.

After fighting with Vite for a couple of hours, I realized that the fix is very simple:

```ts
export const change = rakeDb(config.database, {
  // add this line to rake db config:
  import: (path: string) => import(path),
});
```

**Comment by Superchig** [comment]
I tried this fix out, and it works! Thanks.

**Comment by romeerez** [comment]
I updated docs with how to Vite in the [Quickstart](https://orchid-orm.netlify.app/guide/quickstart.html#es-modules) and mentioned this specific error you had in [Migrations setup](https://orchid-orm.netlify.app/guide/migration-setup-and-overview.html#referenceerror-require-is-not-defined).

Published an update for ORM codegen to fix the `appCodeUpdater` for Vite and other ESMs.
