### ISSUE TITLE
Help: Type Annotation for `change`

### ISSUE THREAD

**Issue by guspower** [romeerez/orchid-orm#75]
Hi,

We're enjoying orchid so far but have run into an issue when pulling the latest release. Previously we were using the `change` function imported from `rake-db` but see from the guide that we should now provide our own implementation. Unfortunately `tsc` is unhappy with our efforts :-/ 

Implementation:
```
export const change = rakeDb(getDbConfig().allDatabases, rakeConfig())
```

TSC Error:
```
The inferred type of 'change' cannot be named without a reference to '../../../../../../../../home/dev/pnpm-virtual/orchid-orm@1.9.23_typescript@5.0.4/node_modules/pqb/dist/index.js'. This is likely not portable. A type annotation is necessary.ts(2742)
The inferred type of 'change' cannot be named without a reference to '../../../../../../../../home/dev/pnpm-virtual/pqb@0.11.20/node_modules/orchid-core/dist/index.js'. This is likely not portable. A type annotation is necessary.ts(2742)
const change: ((fn: ChangeCallback<{
    timestamps<T extends ColumnTypeBase<unknown, BaseOperators, unknown, ColumnDataBase>>(this: {
        name(name: string): {
            timestamp(): T;
        };
        timestamp(): T;
        timestampsSnakeCase(): {
            ...;
        };
    }): {
        ...;
    };
    ... 57 more ...;
    check(check: RawExpression): {};
}>) => void) & {
    ...;
}
No quick fixes available
```

Any and all advice appreciated.

**Comment by romeerez** [comment]
Nice to hear that you're enjoying it!

This change was needed to allow customizing columns, so in your `rakeConfig()` you can have overridden columns, maybe some unusual type of id like `cuid`, and it will be available across migrations.

I'm not sure what's wrong here and how to fix it, this is a nasty kind of error. Where is `rakeConfig()` located, could you share it?

Maybe the following will work? To specifying a default type of columns.

```ts
import { DefaultColumnTypes } from 'pqb'

export const change = rakeDb<DefaultColumnTypes>(
  getDbConfig().allDatabases,
  rakeConfig()
)
```

**Comment by guspower** [comment]
Wow thanks for the quick reply.

I tried your suggested fix, and also tried defining a new type but alas the same error both times. 

I'm now going to try putting the `rakeDb` set up directly into each of the migration files, e.g.
```
import { rakeDb } from 'rake-db';
import { getDbConfig } from '../config.js';
import { rakeConfig } from '../db-migrate.js';

rakeDb(getDbConfig().allDatabases, rakeConfig())(async (db) => {
  await db.addColumn('audit', 'audit_id', (t) =>
    t.bigint().identity({ always: true }),
  );
});
```

This does run the migration, but also prints out the `help` for each migration :-/ More study required.

The `getDbConfig` has nothing exciting in it, the `rakeConfig` looks like:
```
export const rakeConfig = () => {
    dotenv.config()

    return {
        snakeCase: true,
        migrationsPath: './migrations/ts',
        useCodeUpdater: false,
        commands: {}
    }
}
```

Also here is the `tsconfig.json` as reference:

```
{  
  "extends": "@tsconfig/node18/tsconfig.json",
  "compilerOptions": {
    "experimentalDecorators": true,
    "importHelpers": true,
    "moduleResolution": "node",
    "module": "ES2022",
    "esModuleInterop": true,
    "outDir": "dist",
    "rootDir": "./src",
    "strict": true,
    "declaration":  true,
    "forceConsistentCasingInFileNames": true,
  },
  "node": {
    "esm": true
  },
  "ts-node": {
    "esm": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "test/**/*.spec.ts"],
}
```

So I have it working in an albeit strange way. If you have any more suggestions for improvement let me know and I'll give them a spin.

**Comment by romeerez** [comment]
```ts
import { getDbConfig } from '../config.js'; // <-- .js
import { rakeConfig } from '../db-migrate.js'; // <-- .js
```

Of course, you have configs in `js` files, so that's why there are problems with typings!

**Comment by guspower** [comment]
Yep good call, gimme a couple of days, will see if I can create a minimal reproduction.

**Comment by romeerez** [comment]
I added [instructions](https://github.com/romeerez/orchid-orm-examples/tree/main/packages/express-esm) for how to configure the project for ESM. The only way for me to make ESM work was `vite-node`, and it's a problem (not related to Orchid ORM) to compile a project with ESM in other ways, so `vite-node` is the only recommended way for now.

Hope that you solved that issue, feel free to re-open or open new issues if something.
