### ISSUE TITLE
seeding data in migrations

### ISSUE THREAD

**Issue by bonesoul** [romeerez/orchid-orm#8]
i want to seed my static data within my migrations and only example is here with raw sql: https://orchid-orm.netlify.app/guide/migration-writing.html#writing-a-migration

is there a way to use orchid-orm to do so within migrations?

i was able to seed my data using

```
    for (const entry of regions) {
      await db.query({
        text: "INSERT INTO region (id, code, name) VALUES ($1, $2, $3)",
        values: [entry.id, entry.code, entry.name],
      });
    }
```

but i'm looking for a way to push all records once.

**Comment by romeerez** [comment]
Thank you for reaching out!

> is there a way to use orchid-orm to do so within migrations?

Not ORM itself, because in migration we are changing columns, and in ORM we have models with specific columns.

But it must be possible to use a query builder for this. I'll test it, add it to a doc and write back to you, in a day or two.

**Comment by romeerez** [comment]
It is possible with fresh versions, I added an example [to the docs](https://orchid-orm.netlify.app/guide/migration-writing.html#writing-a-migration)
