### ISSUE TITLE
[RFC] model level lifecycle hook 

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#83]
I see there are [callbacks](https://orchid-orm.netlify.app/guide/callbacks.html) on query level, but sometimes I want to do extra action on all queries for a table.

I'm not sure the api, maybe like this:
```ts
export class UserTable extends BaseTable {
  readonly table = 'user';

  columns = this.setColumns((t) => ({
    xxx
  }));

  hooks = this.setHooks((hooks) => {
    hook.onUpdate.push(xxx)
    hook.onDelete.push(xxx)
  })
}
```

**Comment by romeerez** [comment]
I'm curious, what is the use case to run an action on all queries?

**Comment by romeerez** [comment]
I renamed `callbacks` into `hooks`, because when typing `setColumns` or `setCallbacks` the autocomplete may be confused, so now the table has `setHooks`. Added `beforeSave` and `afterSave` to run on both create and update queries.

Documentation: [lifecycle hooks](https://orchid-orm.netlify.app/guide/hooks.html)

There is one caveat regarding using `db` (see in the doc about it) so that when you need to make queries in the hooks, they must be defined after the `db` is defined.

It's essential that we want to get affected records ids or other data in the `afterCreate` or `afterUpdate`, and this is a tricky problem.

Let's say we created a few records with `createMany`:

```ts
await db.post.createMany([
  { title: 'one', body: 'one body' },
  { title: 'two', body: 'two body' },
])
```

And we want to update a search index on a third-party service, and we need to get the created data:

```ts
addTableHooks(db.post, {
  async afterCreate(q, data) {
    // here we have `data` of type unknown
  },
});
```

In that case, `data` is an array with created records, but it's also possible that the create has no returning, or returns only some of the columns, or that it's a hook for update and it doesn't return data at all.

I can't yet imagine a clean solution to this, so the hooks are somewhat useful for some limited cases, and when we need to handle the case above, it's probably worth calling an index updating right after creating or updating records.

**Comment by bingtsingw** [comment]
Thank you for your quick response!
What do you mean that the `data` may be some of columns or no data at all?

**Comment by bingtsingw** [comment]
Oh, I'm used to active record which returns everything... Although it's inefficient, it's convenient sometimes.

I came up with some ideas maybe helpful to make `data` more useful, but I'm not sure if they can be implemented.

1. Unify `data`'s type instead of `unknown`
We can transform `data` to `Partial<Table['columns']['type']>` or `Array<Partial<Table['columns']['type']>>`, this saves us much time to guard `data`'s type in hooks.

2. return a 'dirty data' in hook
```
const input = {} // user input for create or update table
const result = await query.select('xxx')

const dirtyData = merge(input, result)
callHook(dirtyData)

return result
```

**Comment by romeerez** [comment]
Users can select nested data, join some tables and select from them, and select with raw SQL, so the `data` can literally be anything.

For creating and updating records it's allowed to also use raw SQL, for example, [increment](https://orchid-orm.netlify.app/guide/create-update-delete.html#increment) is updating column with SQL `column = column + 1`.

`update` can return updated data if you specify `select` before it, but by default, it doesn't even return data at all, only the amount of updated records.

I have one idea, that seems hard to implement but should be possible. The hook on itself could define what columns it needs.
When you write a hook function, you also add somewhere nearby an array of columns needed like ['id', 'title'].
When performing a query, ORM will look at what's already selected, if these columns aren't selected it will add them. If the return type is incompatible it will change the return type and will pass the result to the hook and now the `data` contains concrete known data.
And after running the callbacks, ORM will transform the response back to what the query intended to load, and strip extra columns from it.

**Comment by bingtsingw** [comment]
Wow, that sounds wonderful, this implementation is similar to what you talked about in [Support computed (virtual) columns](https://github.com/romeerez/orchid-orm/issues/59), we need a way to collect deps, so that they can be merged with user's `select()`.

There is one problem that `select` fields can be every flexible such as object with sub queries, maybe it's better not to implement them first and restrict the deps to table columns only.

With this implementation, we have `columns`, `computed columns` and `hooks` which depend on `columns`, in any query, returned data types should merge them all, seems to be lots of complicated type operation.

**Comment by romeerez** [comment]
> There is one problem that select fields can be every flexible such as object with sub queries, maybe it's better not to implement them first and restrict the deps to table columns only.

Yes, columns only. Supporting complex selects for this case will be complicated and error-prone, and won't bring much value.

> `hooks` do not need to affect the returned types, as they are side effects of the query, we do not expect it to return anything.

It's such a trick, let me show:

```ts
const ids = await db.someTable.pluck('id') // return type is 'pluck', i.e ids = [1, 2, 3, 4]

await db.someTable.create(someData) // return type is a single object

await db.someTable.createMany([one, two]) // return type is an array
```

The hook function doesn't know if it's an array of ids, an object, or an array of objects. But it wants to use the data.

When executing queries from the above, ORM can see that there are hooks that want the data, and they require `id` column. If `id` is already selected by a query, okay, and if not selected it will add `id` to a select.

Then ORM checks what is the return type, and if it's anything that "return many objects", it will change it to "return many objects".

The hook now will get array of objects like `[ { id: 1 } ]`. No matter if it was `pluck` or `get` or `createMany` or `update`, it will be array of objects with required data.

ORM will return the required columns from the objects unless they were present in the original query:

```ts
// only title is selected
const result = await db.someTable.select('title')

// but the hook wants `id`. ORM adds `id` to the select, passes data to hook, then removed `id` from result.
result.id // is not set
```

Then, after the hooks passed, ORM will coerce the data back to what was requested:
- if it was `pluck`, it will collect the column values into a flat array
- if it was a single record returning, it will return a first object of array
- if it was returning many, it will return the array

That's the plan. It's scary but opens up further possibilities.

**Comment by bingtsingw** [comment]
Thank you for the detailed explanation!

**Comment by romeerez** [comment]
And thank you for staying interested! It motivates me to keep pushing.

**Comment by bingtsingw** [comment]
I'm really learning the source code and advanced type operations slowly, hope I can contribute to core features someday : )

**Comment by romeerez** [comment]
Ready! [Here are the docs](https://orchid-orm.netlify.app/guide/hooks.html). It's a breaking change so need to rewrite the old `after` hooks to the new form with a selection of columns.

Let me know what you think after reading the docs.
