### ISSUE TITLE
[Bug] `JSONDate` claims that the return type is a `Date` object, but it is `string`

### ISSUE THREAD

**Issue by rintaun** [romeerez/orchid-orm#84]
When creating a key with a `JSONDate` value in a JSON column, it correctly accepts a `Date` object as input, and (also correctly) stores it as a string -- since it's JSON. However, the type when querying the value also claims that it is a `Date`, when it is actually never coerced back into a `Date` object; it remains a string.

### Reproduction steps
1. Create a column with the type `t.json((j) => j.date())`
2. Insert a value into the column
3. Select the column; observe that the return type claims `Date`
4. Also observe that `typeof columnValue === 'string'`

**Comment by romeerez** [comment]
Thanks for catching and for repro steps, will fix in near days.

**Comment by romeerez** [comment]
I thought this is a quick fix, but it's a whole quite a big feature.

To do this, the ORM should analyze the schema returned from callback, it can be a tuple, object, intersection, and other variants, it should determine all possible JSON paths to date fields. And then, when loading data from the db, it should walk through all those paths in each loaded record's JSON column to find a string and update it to be a Date.

**Comment by romeerez** [comment]
I removed all the JSON types that aren't serializable to JSON: `date`, `map`, `set`, also `any`, `never`, and some others.
