### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#86]
After #81, I continue to see other broken links here and there. Is there a definitive guide on how they should be fixed?

For example, the now-missing "query builder setup" page is linked from 3 files:

```
packages/qb/myqb/package.json
6:  "homepage": "https://orchid-orm.netlify.app/guide/query-builder-setup.html",

packages/qb/pqb/README.md
5:[Read docs here](https://orchid-orm.netlify.app/guide/query-builder-setup.html).

packages/qb/pqb/package.json
5:  "homepage": "https://orchid-orm.netlify.app/guide/query-builder-setup.html",
```

**Comment by romeerez** [comment]
I'll update them, there is no definitive guide for fixing broken links, unfortunately :)

**Comment by romeerez** [comment]
Updated

**Comment by romeerez** [comment]
How do you search for broken links, are you using some tool or a command?

**Comment by IlyaSemenov** [comment]
No, I guess I'm just unlucky. :)
