### ISSUE TITLE
Feature request: transform results

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#93]
### User story

As a developer, I need a type-safe way to transform ORM results as they come from the database, including those that come from subqueries. The idea is similar to how Objection.js [`runAfter`](https://vincit.github.io/objection.js/api/query-builder/other-methods.html#runafter) or zod [`.transform`](https://github.com/colinhacks/zod#transform) work.

### Imaginary use case

With a typical post-comments relation:

```ts
const posts_page = await db.post
  .select("id", "text")
  .select({
    comments: (q) =>
      q.comments
        .select("id", "text")
        .transform((nodes) => ({ nodes, cursor: 1 })),
  })
  .transform((nodes) => ({ nodes, cursor: 2 }))
```

I would like the type of `posts` to be:

```ts
{
  nodes: Array<{
    id: number
    text: string
    comments: {
      nodes: Array<{
        id: number
        text: string
      }>
      cursor: number
    }
  }>
  cursor: number
}
```

**Comment by bingtsingw** [comment]
vote on the transform feature

**Comment by romeerez** [comment]
Nice feature, it seems to be not too complex so I could do it before other features.

**Comment by romeerez** [comment]
Published! [docs](https://orchid-orm.netlify.app/guide/query-methods.html#transform)

**Comment by IlyaSemenov** [comment]
> You can also use the tranform on a nested sub-queries:

Typo: it should be either _"a nested sub-query"_ or _"nested sub-queries"_ without _a_.

**Comment by IlyaSemenov** [comment]
@romeerez I don't think it's working for subqueries. Reproduction:

```ts
import { createBaseTable, orchidORM } from "orchid-orm"

const BaseTable = createBaseTable()

class UserTable extends BaseTable {
  readonly table = "user"

  columns = this.setColumns((t) => ({
    id: t.identity().primaryKey(),
    name: t.string(1, 100),
  }))

  relations = {
    posts: this.hasMany(() => PostTable, {
      primaryKey: "id",
      foreignKey: "author_id",
    }),
  }
}

class PostTable extends BaseTable {
  readonly table = "post"

  columns = this.setColumns((t) => ({
    id: t.identity().primaryKey(),
    text: t.text(1, 10000),
    author_id: t.integer(),
  }))
}

const db = orchidORM(
  {
    databaseURL: process.env.DATABASE_URL,
    log: true,
  },
  {
    user: UserTable,
    post: PostTable,
  }
)

await db.$adapter.query(`
  drop table if exists "user";
  create table "user" (
    id serial primary key,
    name varchar(100) not null
  );
  drop table if exists post;
  create table post (
    id serial primary key,
    text text not null,
    author_id integer not null
  );
`)

await db.user.create({ name: "Alice" })
await db.post.create({ text: "Hello", author_id: 1 })
const user = await db.user
  .find(1)
  .select("name")
  .select({
    posts: (q) =>
      q.posts.select("id", "text").transform((nodes) => ({ nodes })),
  })
console.log(JSON.stringify(user, null, 2))

await db.$close()
```

Result:

```json
{
  "name": "Alice",
  "posts": [
    {
      "id": 1,
      "text": "Hello"
    }
  ]
}
```

Expected: `posts` is wrapped into `nodes`.

**Comment by romeerez** [comment]
A [somewhat simplified test](https://github.com/romeerez/orchid-orm/commit/d16ab35b45eb8c81621ba142acc4bff95a96f1cc#diff-56a64eeba115633c41d9e50924298cffdb1c6bc8f2ecdbdc03c88ae45e7c1b2eR27) worked for this case, but I can see there is a problem when using it for actual relations.

**Comment by romeerez** [comment]
Published a fix.

Thank you for catching it! It was a bug when the relation (`post` in your example) has no column parsers because there was a redundant condition to check for parsers before running a transform. Not should be ok.

**Comment by IlyaSemenov** [comment]
Works now, thanks! This allowed to replace very dirty hacks I've been using with `query.query.handleResult` and `overrideParserInQuery` with a single elegant call.

Unfortunately the new `QueryTransform` types are not exported, any chance for them to be published? I have to type a generic somewhere else and I'd prefer something more concrete than `any` (similar to a problem I have in #106).

Perhaps if this:

```ts
    then: QueryThen<Data>;
    catch: QueryCatch<Data>;
```

could be exported as `QueryPromise<Data>` that would suffice.

**Comment by romeerez** [comment]
Re-opening to not forget exporting them

> copy/pasting the above pair like 5-6 times through the code

Yeah, it's a micro-optimization:

```ts
{
  [K in keyof T]: K extends 'something'
      ? Something
      : K extends 'then'
      ? QueryThen<Data>
      : K extends 'catch'
      ? QueryCatch<Data>
      : T[K]
}
```

It's a much longer version of the equivalent:

```ts
Omit<T, 'something' | 'then' | 'catch'> & { something: Something } & QueryPromise<Data>
```

The first version is constructing a single object from a given T object. The second version is constructing 3 objects, and then TS will sequentially walk through all the keys of these 3 objects to combine them into a 4th object. That's why QueryThen and QueryCatch are always in pairs.

**Comment by romeerez** [comment]
Exported `queryTransform` from `pqb`, and `QueryThen`, `QueryCatch` are exported from `orchid-core`.
