### ISSUE TITLE
[help] Is it safe to assert relation query to `typeof db.relation`

### ISSUE THREAD

**Issue by bingtsingw** [romeerez/orchid-orm#94]
Here is my use case:

I want to DRY for my `select` fileds.

`user.repo.ts`
```ts
const userDefaultSelect = (q: typeof db.user) => {
  return q.select('id', 'name', 'profile');
};
```

`article.repo.ts`
```ts
const repo = createRepo(db.article, {
  queryMethods: {
    defaultSelect: (q) => {
      return q.select('xxx', {
         user: (q) => userDefaultSelect(q.user as unknown as typeof db.user)
      })
    }
  }
})
```

`userDefaultSelect(q.user)` had type error so I have to assert it to `typeof db.user`. Are there any better ways to do this? Or if I have to do type assertion, is it safe?

**Comment by bingtsingw** [comment]
By the way, the result for this simple demo is acting as expected, my concern is whether it can lead to hidden bugs in the future

**Comment by romeerez** [comment]
There is a better way: `userDefaultSelect` should return a function that takes (q: typeof db.user) => ...

```ts
const userDefaultSelect = () => {
  return (q: typeof db.user) => {
    return q.select('id', 'name', 'profile');
  }
};
```

`article.repo`:
```ts
const repo = createRepo(db.article, {
  queryMethods: {
    defaultSelect: (q) => {
      return q.select('xxx', {
         user: userDefaultSelect()
      })
    }
  }
})
```

Let me know if it helps, it may not, I copied this idea from [the long tutorial](https://orchid-orm.netlify.app/guide/building-a-sample-app.html) and there this works.

**Comment by bingtsingw** [comment]
Seems not work, and it has type error and runtime errors.

**Comment by bingtsingw** [comment]
In the tutorial, `selectFavorited` received a `db.article` type handles `q.favorites ` inside the function, but in my case, `userDefaultSelect` received a `db.user` type which is not compatible with `q(as typeof db.article).user`

**Comment by romeerez** [comment]
I don't know and going AFK now, will try to figure out later.

There is a chance that `db.article.user` may be ok:

```ts
const userDefaultSelect = (q: typeof db.article.user) => {
  return q.select('id', 'name', 'profile');
};
```

Because that `q` is not exactly `db.user`, but extended version of it that belongs to `db.article` and the type is different.

**Comment by romeerez** [comment]
> This works but it's wired.

Cool, so at least it works. I'll figure out how to add some kind of helper to un-wire it.

**Comment by romeerez** [comment]
Published a function `makeQuery` for this: [docs](https://orchid-orm.netlify.app/guide/query-methods.html#makehelper).

A type-only helper wouldn't be enough for this case, I tried.
