### ISSUE TITLE
Utility type to extract table interface

### ISSUE THREAD

**Issue by IlyaSemenov** [romeerez/orchid-orm#95]
Currently, extracting interface from a table requires non-obvious repetitive boilerplate:

```ts
// export type of User object:
export type User = UserTable['columns']['type'];
```

I believe this is a very common operation, so perhaps we can have a utility type that allows to express the same more clearly? Something like:

```ts
export type User = TableType<UserTable>;

// implemented like:

export type TableType<T extends ColumnsConfig> = T['columns']['type']
```

(I realise this can be easily implemented in user land, I'm just thinking it's needed often so could deserve a shortcut in the core... I am yet to use orchid in a real project so I could be mistaken.)

**Comment by romeerez** [comment]
Ready, published the `TableType` just in your example, import it from 'orchid-orm'.
